<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>10 Egymintás és Kétmintás próbák | Következtető Statisztika Python Jegyzet</title>
  <meta name="description" content="<p>Lecture notes on BSc level Inferential Statistics in bookdown format.
Mainly for Business Information Systems BSc students at Corvinus University of Budapest.</p>" />
  <meta name="generator" content="bookdown 0.43 and GitBook 2.6.7" />

  <meta property="og:title" content="10 Egymintás és Kétmintás próbák | Következtető Statisztika Python Jegyzet" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="<p>Lecture notes on BSc level Inferential Statistics in bookdown format.
Mainly for Business Information Systems BSc students at Corvinus University of Budapest.</p>" />
  <meta name="github-repo" content="KoLa992/Kovetkezteto-Statisztika-Python-Jegyzet" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="10 Egymintás és Kétmintás próbák | Következtető Statisztika Python Jegyzet" />
  
  <meta name="twitter:description" content="<p>Lecture notes on BSc level Inferential Statistics in bookdown format.
Mainly for Business Information Systems BSc students at Corvinus University of Budapest.</p>" />
  

<meta name="author" content="Kovács László" />


<meta name="date" content="2025-06-30" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="hipotézisvizsgálat-alapjai.html"/>
<link rel="next" href="nemparaméteres-próbák.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Következtető Statisztika Python Jegyzet</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Előhang</a></li>
<li class="chapter" data-level="2" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html"><i class="fa fa-check"></i><b>2</b> Statisztikához szükséges Python nyelvi alapok</a>
<ul>
<li class="chapter" data-level="2.1" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#programozási-alapelvek"><i class="fa fa-check"></i><b>2.1</b> Programozási alapelvek</a></li>
<li class="chapter" data-level="2.2" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#a-pythonról-általában"><i class="fa fa-check"></i><b>2.2</b> A Pythonról általában</a></li>
<li class="chapter" data-level="2.3" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#a-spyder-felülete"><i class="fa fa-check"></i><b>2.3</b> A Spyder felülete</a></li>
<li class="chapter" data-level="2.4" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#working-directory"><i class="fa fa-check"></i><b>2.4</b> Working Directory</a></li>
<li class="chapter" data-level="2.5" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#alapvető-python-adattípusok-és-adatszerkezetek"><i class="fa fa-check"></i><b>2.5</b> Alapvető Python adattípusok és adatszerkezetek</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#egyszerű-adattípusok"><i class="fa fa-check"></i><b>2.5.1</b> Egyszerű adattípusok</a></li>
<li class="chapter" data-level="2.5.2" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#összetett-adatszerkezetek"><i class="fa fa-check"></i><b>2.5.2</b> Összetett adatszerkezetek</a></li>
<li class="chapter" data-level="2.5.3" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#a-numpy-tömb"><i class="fa fa-check"></i><b>2.5.3</b> A <code>numpy</code> tömb</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#vezérlési-szerkezetek"><i class="fa fa-check"></i><b>2.6</b> Vezérlési szerkezetek</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#elágazás-if"><i class="fa fa-check"></i><b>2.6.1</b> Elágazás (<code>if</code>)</a></li>
<li class="chapter" data-level="2.6.2" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#ciklusok-for"><i class="fa fa-check"></i><b>2.6.2</b> Ciklusok (<code>for</code>)</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#a-pandas-data-frame-objektum"><i class="fa fa-check"></i><b>2.7</b> A Pandas data frame objektum</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#hivatkozási-lehetőségek-data-frame-ben"><i class="fa fa-check"></i><b>2.7.1</b> Hivatkozási lehetőségek data frame-ben</a></li>
<li class="chapter" data-level="2.7.2" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#data-frame-k-módosítása"><i class="fa fa-check"></i><b>2.7.2</b> Data frame-k módosítása</a></li>
<li class="chapter" data-level="2.7.3" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#szűrés-data-frame-ben-logikai-indexszálás"><i class="fa fa-check"></i><b>2.7.3</b> Szűrés data frame-ben: logikai indexszálás</a></li>
<li class="chapter" data-level="2.7.4" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#hiányzó-értékek-kezelése-data-frame-ben"><i class="fa fa-check"></i><b>2.7.4</b> Hiányzó értékek kezelése data frame-ben</a></li>
<li class="chapter" data-level="2.7.5" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#adatvizualizáció-data-frame-en-keresztül"><i class="fa fa-check"></i><b>2.7.5</b> Adatvizualizáció data frame-en keresztül</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#aggregálás-data-frame-ben"><i class="fa fa-check"></i><b>2.8</b> Aggregálás data frame-ben</a></li>
<li class="chapter" data-level="2.9" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#egyszerű-leíró-statisztika-data-frame-ben"><i class="fa fa-check"></i><b>2.9</b> Egyszerű leíró statisztika data frame-ben</a></li>
<li class="chapter" data-level="2.10" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#adatminőségi-problémák-felismerése-és-kezelése-leíró-statisztika-segítségével"><i class="fa fa-check"></i><b>2.10</b> Adatminőségi problémák felismerése és kezelése leíró statisztika segítségével</a></li>
<li class="chapter" data-level="2.11" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#data-frame-k-összekapcsolása"><i class="fa fa-check"></i><b>2.11</b> Data frame-k összekapcsolása</a>
<ul>
<li class="chapter" data-level="2.11.1" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#a-kapcsolási-kulcsnak-használt-oszlop-ellenőrzése-és-javítása"><i class="fa fa-check"></i><b>2.11.1</b> A kapcsolási kulcsnak használt oszlop ellenőrzése és javítása</a></li>
</ul></li>
<li class="chapter" data-level="2.12" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#kilógó-értékek-keresése-és-kezelése"><i class="fa fa-check"></i><b>2.12</b> Kilógó értékek keresése és kezelése</a></li>
<li class="chapter" data-level="2.13" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#korrelációs-elemzések-data-frame-ben"><i class="fa fa-check"></i><b>2.13</b> Korrelációs elemzések data frame-ben</a></li>
<li class="chapter" data-level="" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#gyakorló-feladatok"><i class="fa fa-check"></i>Gyakorló feladatok</a></li>
<li class="chapter" data-level="" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#gyakorló-feladatok-megoldása"><i class="fa fa-check"></i>Gyakorló feladatok megoldása</a>
<ul>
<li class="chapter" data-level="" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#feladat"><i class="fa fa-check"></i>1. feladat</a></li>
<li class="chapter" data-level="" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#feladat-1"><i class="fa fa-check"></i>2. feladat</a></li>
<li class="chapter" data-level="" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#feladat-2"><i class="fa fa-check"></i>3. feladat</a></li>
<li class="chapter" data-level="" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#feladat-3"><i class="fa fa-check"></i>4. feladat</a></li>
<li class="chapter" data-level="" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#feladat-4"><i class="fa fa-check"></i>5. feladat</a></li>
<li class="chapter" data-level="" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#feladat-5"><i class="fa fa-check"></i>6. feladat</a></li>
<li class="chapter" data-level="" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#feladat-6"><i class="fa fa-check"></i>7. feladat</a></li>
<li class="chapter" data-level="" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#feladat-7"><i class="fa fa-check"></i>8. feladat</a></li>
<li class="chapter" data-level="" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#feladat-8"><i class="fa fa-check"></i>9. feladat</a></li>
<li class="chapter" data-level="" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#feladat-9"><i class="fa fa-check"></i>10. feladat</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html"><a href="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html"><i class="fa fa-check"></i><b>3</b> Leíró Statisztika ismétlés és Valószínűségszámítás alapok</a>
<ul>
<li class="chapter" data-level="3.1" data-path="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html"><a href="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html#leíró-statisztikai-mutatók"><i class="fa fa-check"></i><b>3.1</b> Leíró statisztikai mutatók</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html"><a href="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html#hisztogram-és-alakmutatók"><i class="fa fa-check"></i><b>3.1.1</b> Hisztogram és Alakmutatók</a></li>
<li class="chapter" data-level="3.1.2" data-path="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html"><a href="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html#gyakorisági-tábla-lekérése"><i class="fa fa-check"></i><b>3.1.2</b> Gyakorisági tábla lekérése</a></li>
<li class="chapter" data-level="3.1.3" data-path="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html"><a href="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html#gyakorisági-tábla-bővítése"><i class="fa fa-check"></i><b>3.1.3</b> Gyakorisági tábla bővítése</a></li>
<li class="chapter" data-level="3.1.4" data-path="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html"><a href="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html#súlyozott-átlag-és-szórás-pythonban"><i class="fa fa-check"></i><b>3.1.4</b> Súlyozott átlag és szórás Pythonban</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html"><a href="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html#a-normális-eloszlás-és-sűrűségfüggvénye"><i class="fa fa-check"></i><b>3.2</b> A normális eloszlás és sűrűségfüggvénye</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html"><a href="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html#a-sűrűségfüggvény-használata"><i class="fa fa-check"></i><b>3.2.1</b> A sűrűségfüggvény használata</a></li>
<li class="chapter" data-level="3.2.2" data-path="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html"><a href="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html#a-sűrűségfüggvény-integrálja"><i class="fa fa-check"></i><b>3.2.2</b> A sűrűségfüggvény integrálja</a></li>
<li class="chapter" data-level="3.2.3" data-path="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html"><a href="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html#valószínűség-vs-relatív-gyakoriság"><i class="fa fa-check"></i><b>3.2.3</b> Valószínűség vs Relatív Gyakoriság</a></li>
<li class="chapter" data-level="3.2.4" data-path="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html"><a href="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html#centrális-határeloszlás-tétel-cht"><i class="fa fa-check"></i><b>3.2.4</b> Centrális Határeloszlás Tétel (CHT)</a></li>
<li class="chapter" data-level="3.2.5" data-path="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html"><a href="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html#inverz-értékek"><i class="fa fa-check"></i><b>3.2.5</b> Inverz Értékek</a></li>
<li class="chapter" data-level="3.2.6" data-path="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html"><a href="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html#a-standard-normális-eloszlás"><i class="fa fa-check"></i><b>3.2.6</b> A Standard Normális Eloszlás</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html"><a href="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html#az-exponenciális-eloszlás"><i class="fa fa-check"></i><b>3.3</b> Az Exponenciális eloszlás</a></li>
<li class="chapter" data-level="3.4" data-path="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html"><a href="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html#a-varianciahányados-pythonban---kokain-a-balatonban"><i class="fa fa-check"></i><b>3.4</b> A Varianciahányados Pythonban - Kokain a Balatonban</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html"><a href="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html#további-minőségi-ismérvek-és-a-kokainmennyiség"><i class="fa fa-check"></i><b>3.4.1</b> További minőségi ismérvek és a kokainmennyiség</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="eloszlások-és-mintavételezés.html"><a href="eloszlások-és-mintavételezés.html"><i class="fa fa-check"></i><b>4</b> Eloszlások és Mintavételezés</a>
<ul>
<li class="chapter" data-level="4.1" data-path="eloszlások-és-mintavételezés.html"><a href="eloszlások-és-mintavételezés.html#véletlenszám-generálás-és-mintavételezés"><i class="fa fa-check"></i><b>4.1</b> Véletlenszám generálás és Mintavételezés</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="eloszlások-és-mintavételezés.html"><a href="eloszlások-és-mintavételezés.html#a-mintagenerálás-általános-elve"><i class="fa fa-check"></i><b>4.1.1</b> A mintagenerálás általános elve</a></li>
<li class="chapter" data-level="4.1.2" data-path="eloszlások-és-mintavételezés.html"><a href="eloszlások-és-mintavételezés.html#nem-egyenletes-eloszlású-minták-generálása"><i class="fa fa-check"></i><b>4.1.2</b> Nem egyenletes eloszlású minták generálása</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="eloszlások-és-mintavételezés.html"><a href="eloszlások-és-mintavételezés.html#elvi-eloszlás-vs-megfigyelt-minta"><i class="fa fa-check"></i><b>4.2</b> Elvi Eloszlás vs Megfigyelt Minta</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="eloszlások-és-mintavételezés.html"><a href="eloszlások-és-mintavételezés.html#az-elvi-eloszlás-alapján-számolt-statisztikai-mutatók"><i class="fa fa-check"></i><b>4.2.1</b> Az elvi eloszlás alapján számolt statisztikai mutatók</a></li>
<li class="chapter" data-level="4.2.2" data-path="eloszlások-és-mintavételezés.html"><a href="eloszlások-és-mintavételezés.html#a-megfigyelt-minta-alapján-számolt-statisztikai-mutatók"><i class="fa fa-check"></i><b>4.2.2</b> A megfigyelt minta alapján számolt statisztikai mutatók</a></li>
<li class="chapter" data-level="4.2.3" data-path="eloszlások-és-mintavételezés.html"><a href="eloszlások-és-mintavételezés.html#a-mintavételi-hiba-mvh-koncepciója"><i class="fa fa-check"></i><b>4.2.3</b> A mintavételi hiba (MVH) koncepciója</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="eloszlások-és-mintavételezés.html"><a href="eloszlások-és-mintavételezés.html#statisztikai-sokaságok-fae-mintavételezése"><i class="fa fa-check"></i><b>4.3</b> Statisztikai sokaságok FAE mintavételezése</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="eloszlások-és-mintavételezés.html"><a href="eloszlások-és-mintavételezés.html#ismételt-mintavételezés-resampling"><i class="fa fa-check"></i><b>4.3.1</b> Ismételt Mintavételezés (<em>Resampling</em>)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="a-becsléselmélet-alapjai.html"><a href="a-becsléselmélet-alapjai.html"><i class="fa fa-check"></i><b>5</b> A becsléselmélet alapjai</a>
<ul>
<li class="chapter" data-level="5.1" data-path="a-becsléselmélet-alapjai.html"><a href="a-becsléselmélet-alapjai.html#ismétlés-balaton-átúszás-eredmények-és-ezek-fae-mintái"><i class="fa fa-check"></i><b>5.1</b> Ismétlés: Balaton átúszás eredmények és ezek FAE mintái</a></li>
<li class="chapter" data-level="5.2" data-path="a-becsléselmélet-alapjai.html"><a href="a-becsléselmélet-alapjai.html#a-torzítatlanság-fogalma"><i class="fa fa-check"></i><b>5.2</b> A torzítatlanság fogalma</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="a-becsléselmélet-alapjai.html"><a href="a-becsléselmélet-alapjai.html#az-aszimptotikus-torzítatlanság-fogalma"><i class="fa fa-check"></i><b>5.2.1</b> Az aszimptotikus torzítatlanság fogalma</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="a-becsléselmélet-alapjai.html"><a href="a-becsléselmélet-alapjai.html#a-korrigált-mintavariancia"><i class="fa fa-check"></i><b>5.3</b> A korrigált mintavariancia</a></li>
<li class="chapter" data-level="5.4" data-path="a-becsléselmélet-alapjai.html"><a href="a-becsléselmélet-alapjai.html#a-medián-torzítatlansága"><i class="fa fa-check"></i><b>5.4</b> A medián torzítatlansága</a></li>
<li class="chapter" data-level="5.5" data-path="a-becsléselmélet-alapjai.html"><a href="a-becsléselmélet-alapjai.html#a-standard-hiba-sh-fogalma"><i class="fa fa-check"></i><b>5.5</b> A Standard Hiba (<em>SH</em>) fogalma</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="a-becsléselmélet-alapjai.html"><a href="a-becsléselmélet-alapjai.html#a-konzisztens-becslés-fogalma"><i class="fa fa-check"></i><b>5.5.1</b> A konzisztens becslés fogalma</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="a-becsléselmélet-alapjai.html"><a href="a-becsléselmélet-alapjai.html#az-átlagos-négyzetes-hiba-mse-fogalma"><i class="fa fa-check"></i><b>5.6</b> Az átlagos négyzetes hiba (<em>MSE</em>) fogalma</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="a-becsléselmélet-alapjai.html"><a href="a-becsléselmélet-alapjai.html#különböző-becslőfüggvények-összehasonlítása"><i class="fa fa-check"></i><b>5.6.1</b> Különböző becslőfüggvények összehasonlítása</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="a-sokasági-átlag-intervallumbecslése.html"><a href="a-sokasági-átlag-intervallumbecslése.html"><i class="fa fa-check"></i><b>6</b> A sokasági átlag intervallumbecslése</a>
<ul>
<li class="chapter" data-level="6.1" data-path="a-sokasági-átlag-intervallumbecslése.html"><a href="a-sokasági-átlag-intervallumbecslése.html#ismétlés-az-átlag-standard-hibája-a-balaton-átúszás-eredményeken"><i class="fa fa-check"></i><b>6.1</b> Ismétlés: Az átlag standard hibája a Balaton átúszás eredményeken</a></li>
<li class="chapter" data-level="6.2" data-path="a-sokasági-átlag-intervallumbecslése.html"><a href="a-sokasági-átlag-intervallumbecslése.html#a-mintaátlagok-eloszlása"><i class="fa fa-check"></i><b>6.2</b> A mintaátlagok eloszlása</a></li>
<li class="chapter" data-level="6.3" data-path="a-sokasági-átlag-intervallumbecslése.html"><a href="a-sokasági-átlag-intervallumbecslése.html#a-sokasági-átlag-konfidencia-intervalluma"><i class="fa fa-check"></i><b>6.3</b> A sokasági átlag konfidencia-intervalluma</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="a-sokasági-átlag-intervallumbecslése.html"><a href="a-sokasági-átlag-intervallumbecslése.html#az-átlag-konfidencia-intervallumának-általános-alakja"><i class="fa fa-check"></i><b>6.3.1</b> Az átlag konfidencia-intervallumának általános alakja</a></li>
<li class="chapter" data-level="6.3.2" data-path="a-sokasági-átlag-intervallumbecslése.html"><a href="a-sokasági-átlag-intervallumbecslése.html#a-konfidencia-intervallum-megbízhatóságának-ellenőrzése"><i class="fa fa-check"></i><b>6.3.2</b> A konfidencia-intervallum megbízhatóságának ellenőrzése</a></li>
<li class="chapter" data-level="6.3.3" data-path="a-sokasági-átlag-intervallumbecslése.html"><a href="a-sokasági-átlag-intervallumbecslése.html#a-konfidencia-intervallum-két-fontos-tulajdonsága"><i class="fa fa-check"></i><b>6.3.3</b> 3.3. A konfidencia-intervallum két fontos tulajdonsága</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="a-sokasági-átlag-intervallumbecslése.html"><a href="a-sokasági-átlag-intervallumbecslése.html#intervallumbecslés-a-gyakorlatban"><i class="fa fa-check"></i><b>6.4</b> Intervallumbecslés a gyakorlatban</a>
<ul>
<li class="chapter" data-level="" data-path="a-sokasági-átlag-intervallumbecslése.html"><a href="a-sokasági-átlag-intervallumbecslése.html#feladat-altatók-hatékonysága"><i class="fa fa-check"></i>1. feladat: Altatók hatékonysága</a></li>
<li class="chapter" data-level="" data-path="a-sokasági-átlag-intervallumbecslése.html"><a href="a-sokasági-átlag-intervallumbecslése.html#a-feladat-megoldás"><i class="fa fa-check"></i>1/a) feladat megoldás</a></li>
<li class="chapter" data-level="" data-path="a-sokasági-átlag-intervallumbecslése.html"><a href="a-sokasági-átlag-intervallumbecslése.html#b-feladat-megoldás"><i class="fa fa-check"></i>1/b) feladat megoldás</a></li>
<li class="chapter" data-level="" data-path="a-sokasági-átlag-intervallumbecslése.html"><a href="a-sokasági-átlag-intervallumbecslése.html#c-feladat-megoldás"><i class="fa fa-check"></i>1/c) feladat megoldás</a></li>
<li class="chapter" data-level="" data-path="a-sokasági-átlag-intervallumbecslése.html"><a href="a-sokasági-átlag-intervallumbecslése.html#feladat-10"><i class="fa fa-check"></i>2. feladat</a></li>
<li class="chapter" data-level="" data-path="a-sokasági-átlag-intervallumbecslése.html"><a href="a-sokasági-átlag-intervallumbecslése.html#feladat-megoldás"><i class="fa fa-check"></i>2. feladat megoldás</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="a-sokasági-átlag-intervallumbecslése.html"><a href="a-sokasági-átlag-intervallumbecslése.html#összefoglalás-az-átlag-konfidencia-intervallumairól"><i class="fa fa-check"></i><b>6.5</b> Összefoglalás az átlag konfidencia-intervallumairól</a></li>
<li class="chapter" data-level="6.6" data-path="a-sokasági-átlag-intervallumbecslése.html"><a href="a-sokasági-átlag-intervallumbecslése.html#esettanulmány"><i class="fa fa-check"></i><b>6.6</b> Esettanulmány</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="további-fae-becslések-és-a-bootstrap-módszer.html"><a href="további-fae-becslések-és-a-bootstrap-módszer.html"><i class="fa fa-check"></i><b>7</b> További FAE becslések és a Bootstrap módszer</a>
<ul>
<li class="chapter" data-level="7.1" data-path="további-fae-becslések-és-a-bootstrap-módszer.html"><a href="további-fae-becslések-és-a-bootstrap-módszer.html#a-konfidencia-intervallumok-két-általános-tulajdonsága"><i class="fa fa-check"></i><b>7.1</b> A Konfidencia-intervallumok két általános tulajdonsága</a></li>
<li class="chapter" data-level="7.2" data-path="további-fae-becslések-és-a-bootstrap-módszer.html"><a href="további-fae-becslések-és-a-bootstrap-módszer.html#arányok-konfidencia-intervalluma"><i class="fa fa-check"></i><b>7.2</b> Arányok konfidencia-intervalluma</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="további-fae-becslések-és-a-bootstrap-módszer.html"><a href="további-fae-becslések-és-a-bootstrap-módszer.html#mintaelemszám-meghatározása-aránybecsléshez"><i class="fa fa-check"></i><b>7.2.1</b> Mintaelemszám meghatározása aránybecsléshez</a></li>
<li class="chapter" data-level="7.2.2" data-path="további-fae-becslések-és-a-bootstrap-módszer.html"><a href="további-fae-becslések-és-a-bootstrap-módszer.html#szükséges-minimális-elemszám-aránybecsléshez"><i class="fa fa-check"></i><b>7.2.2</b> Szükséges minimális elemszám aránybecsléshez</a></li>
<li class="chapter" data-level="7.2.3" data-path="további-fae-becslések-és-a-bootstrap-módszer.html"><a href="további-fae-becslések-és-a-bootstrap-módszer.html#aránybecslés-a-statsmodels-csomaggal"><i class="fa fa-check"></i><b>7.2.3</b> Aránybecslés a <code>statsmodels</code> csomaggal</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="további-fae-becslések-és-a-bootstrap-módszer.html"><a href="további-fae-becslések-és-a-bootstrap-módszer.html#a-bootstrap-becslések-általános-elve"><i class="fa fa-check"></i><b>7.3</b> A Bootstrap becslések általános elve</a></li>
<li class="chapter" data-level="7.4" data-path="további-fae-becslések-és-a-bootstrap-módszer.html"><a href="további-fae-becslések-és-a-bootstrap-módszer.html#a-medián-bootstrap-intervallumbecslése"><i class="fa fa-check"></i><b>7.4</b> A Medián Bootstrap intervallumbecslése</a></li>
<li class="chapter" data-level="7.5" data-path="további-fae-becslések-és-a-bootstrap-módszer.html"><a href="további-fae-becslések-és-a-bootstrap-módszer.html#a-szórás-bootstrap-intervallumbecslése"><i class="fa fa-check"></i><b>7.5</b> A Szórás Bootstrap intervallumbecslése</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="becslések-ev-és-r-mintából.html"><a href="becslések-ev-és-r-mintából.html"><i class="fa fa-check"></i><b>8</b> Becslések EV és R mintából</a>
<ul>
<li class="chapter" data-level="8.1" data-path="becslések-ev-és-r-mintából.html"><a href="becslések-ev-és-r-mintából.html#intervallumbecslés-visszatevés-nélküli-egyszerű-véletlen-ev-mintákból"><i class="fa fa-check"></i><b>8.1</b> Intervallumbecslés visszatevés nélküli egyszerű véletlen (EV) mintákból</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="becslések-ev-és-r-mintából.html"><a href="becslések-ev-és-r-mintából.html#átlag-becslése-ev-mintákból"><i class="fa fa-check"></i><b>8.1.1</b> Átlag becslése EV mintákból</a></li>
<li class="chapter" data-level="8.1.2" data-path="becslések-ev-és-r-mintából.html"><a href="becslések-ev-és-r-mintából.html#arány-becslése-ev-mintákból"><i class="fa fa-check"></i><b>8.1.2</b> Arány becslése EV mintákból</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="becslések-ev-és-r-mintából.html"><a href="becslések-ev-és-r-mintából.html#átlag-becslése-arányosan-rétegzett-ar-mintákból"><i class="fa fa-check"></i><b>8.2</b> Átlag becslése Arányosan Rétegzett (AR) mintákból</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="becslések-ev-és-r-mintából.html"><a href="becslések-ev-és-r-mintából.html#az-ar-mintavételek-hatékonysága"><i class="fa fa-check"></i><b>8.2.1</b> Az AR mintavételek hatékonysága</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="hipotézisvizsgálat-alapjai.html"><a href="hipotézisvizsgálat-alapjai.html"><i class="fa fa-check"></i><b>9</b> Hipotézisvizsgálat alapjai</a>
<ul>
<li class="chapter" data-level="9.1" data-path="hipotézisvizsgálat-alapjai.html"><a href="hipotézisvizsgálat-alapjai.html#a-hipotézisvizsgálat-alapgondolata"><i class="fa fa-check"></i><b>9.1</b> A hipotézisvizsgálat alapgondolata</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="hipotézisvizsgálat-alapjai.html"><a href="hipotézisvizsgálat-alapjai.html#a-p-érték-fogalma"><i class="fa fa-check"></i><b>9.1.1</b> A p-érték fogalma</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="hipotézisvizsgálat-alapjai.html"><a href="hipotézisvizsgálat-alapjai.html#a-sokasági-átlagra-vonatkozó-t-próba"><i class="fa fa-check"></i><b>9.2</b> A sokasági átlagra vonatkozó <em>t-próba</em></a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="hipotézisvizsgálat-alapjai.html"><a href="hipotézisvizsgálat-alapjai.html#a-t-próba-beépített-függvénnyel"><i class="fa fa-check"></i><b>9.2.1</b> A <em>t-próba</em> beépített függvénnyel</a></li>
<li class="chapter" data-level="9.2.2" data-path="hipotézisvizsgálat-alapjai.html"><a href="hipotézisvizsgálat-alapjai.html#a-t-próba-előfeltételei"><i class="fa fa-check"></i><b>9.2.2</b> A <em>t-próba</em> előfeltételei</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="hipotézisvizsgálat-alapjai.html"><a href="hipotézisvizsgálat-alapjai.html#a-sokasági-átlagra-vonatkozó-z-próba"><i class="fa fa-check"></i><b>9.3</b> A sokasági átlagra vonatkozó <em>z-próba</em></a></li>
<li class="chapter" data-level="9.4" data-path="hipotézisvizsgálat-alapjai.html"><a href="hipotézisvizsgálat-alapjai.html#a-sokasági-arányra-vonatkozó-z-próba"><i class="fa fa-check"></i><b>9.4</b> A sokasági arányra vonatkozó <em>z-próba</em></a></li>
<li class="chapter" data-level="9.5" data-path="hipotézisvizsgálat-alapjai.html"><a href="hipotézisvizsgálat-alapjai.html#a-hipotézisvizsgálat-menete-madártávlatból"><i class="fa fa-check"></i><b>9.5</b> A hipotézisvizsgálat menete madártávlatból</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="egymintás-és-kétmintás-próbák.html"><a href="egymintás-és-kétmintás-próbák.html"><i class="fa fa-check"></i><b>10</b> Egymintás és Kétmintás próbák</a>
<ul>
<li class="chapter" data-level="10.1" data-path="egymintás-és-kétmintás-próbák.html"><a href="egymintás-és-kétmintás-próbák.html#a-szórásra-vonatkozó-chi2-próba"><i class="fa fa-check"></i><b>10.1</b> A szórásra vonatkozó <span class="math inline">\(\chi^2\)</span>-próba</a></li>
<li class="chapter" data-level="10.2" data-path="egymintás-és-kétmintás-próbák.html"><a href="egymintás-és-kétmintás-próbák.html#a-kétmintás-hipotézisvizsgálatok-elve"><i class="fa fa-check"></i><b>10.2</b> A kétmintás hipotézisvizsgálatok elve</a></li>
<li class="chapter" data-level="10.3" data-path="egymintás-és-kétmintás-próbák.html"><a href="egymintás-és-kétmintás-próbák.html#az-átlagokra-vonatkozó-kétmintás-z-próba"><i class="fa fa-check"></i><b>10.3</b> Az átlagokra vonatkozó kétmintás <em>z-próba</em></a></li>
<li class="chapter" data-level="10.4" data-path="egymintás-és-kétmintás-próbák.html"><a href="egymintás-és-kétmintás-próbák.html#az-arányokra-vonatkozó-kétmintás-z-próba"><i class="fa fa-check"></i><b>10.4</b> Az arányokra vonatkozó kétmintás <em>z-próba</em></a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="nemparaméteres-próbák.html"><a href="nemparaméteres-próbák.html"><i class="fa fa-check"></i><b>11</b> Nemparaméteres próbák</a>
<ul>
<li class="chapter" data-level="11.1" data-path="nemparaméteres-próbák.html"><a href="nemparaméteres-próbák.html#nemparaméteres-próbák-elve"><i class="fa fa-check"></i><b>11.1</b> Nemparaméteres próbák elve</a></li>
<li class="chapter" data-level="11.2" data-path="nemparaméteres-próbák.html"><a href="nemparaméteres-próbák.html#illeszkedésvizsgálatok"><i class="fa fa-check"></i><b>11.2</b> Illeszkedésvizsgálatok</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="nemparaméteres-próbák.html"><a href="nemparaméteres-próbák.html#reprezentativitás-vizsgálat"><i class="fa fa-check"></i><b>11.2.1</b> Reprezentativitás vizsgálat</a></li>
<li class="chapter" data-level="11.2.2" data-path="nemparaméteres-próbák.html"><a href="nemparaméteres-próbák.html#normalitás-vizsgálat"><i class="fa fa-check"></i><b>11.2.2</b> Normalitás vizsgálat</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="nemparaméteres-próbák.html"><a href="nemparaméteres-próbák.html#függetlenségvizsgálatok-homogenitásvizsgálatok"><i class="fa fa-check"></i><b>11.3</b> Függetlenségvizsgálatok (homogenitásvizsgálatok)</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="kétváltozós-lineáris-regresszió.html"><a href="kétváltozós-lineáris-regresszió.html"><i class="fa fa-check"></i><b>12</b> Kétváltozós lineáris regresszió</a>
<ul>
<li class="chapter" data-level="12.1" data-path="kétváltozós-lineáris-regresszió.html"><a href="kétváltozós-lineáris-regresszió.html#budapesti-lakások-vizsgálata"><i class="fa fa-check"></i><b>12.1</b> Budapesti lakások vizsgálata</a></li>
<li class="chapter" data-level="12.2" data-path="kétváltozós-lineáris-regresszió.html"><a href="kétváltozós-lineáris-regresszió.html#a-kétváltozós-lineáris-regresszió-ols-elvű-becslése"><i class="fa fa-check"></i><b>12.2</b> A Kétváltozós Lineáris Regresszió OLS elvű becslése</a></li>
<li class="chapter" data-level="12.3" data-path="kétváltozós-lineáris-regresszió.html"><a href="kétváltozós-lineáris-regresszió.html#az-ols-regresszió-magyarázóerejének-mérése"><i class="fa fa-check"></i><b>12.3</b> Az OLS Regresszió magyarázóerejének mérése</a></li>
<li class="chapter" data-level="12.4" data-path="kétváltozós-lineáris-regresszió.html"><a href="kétváltozós-lineáris-regresszió.html#a-regresszió-magyarázóereje-nem-megfigyelt-adatok-körében"><i class="fa fa-check"></i><b>12.4</b> A Regresszió magyarázóereje nem megfigyelt adatok körében</a></li>
<li class="chapter" data-level="12.5" data-path="kétváltozós-lineáris-regresszió.html"><a href="kétváltozós-lineáris-regresszió.html#a-modell-együtthatóinak-értelemzése"><i class="fa fa-check"></i><b>12.5</b> A modell együtthatóinak értelemzése</a></li>
<li class="chapter" data-level="12.6" data-path="kétváltozós-lineáris-regresszió.html"><a href="kétváltozós-lineáris-regresszió.html#egy-gyakorló-példa-covid-adatokon"><i class="fa fa-check"></i><b>12.6</b> Egy gyakorló példa COVID adatokon</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="többváltozós-ols-regresszió-alapjai.html"><a href="többváltozós-ols-regresszió-alapjai.html"><i class="fa fa-check"></i><b>13</b> Többváltozós OLS Regresszió alapjai</a>
<ul>
<li class="chapter" data-level="13.1" data-path="többváltozós-ols-regresszió-alapjai.html"><a href="többváltozós-ols-regresszió-alapjai.html#magyar-járások-covid-19-halálozási-arányai"><i class="fa fa-check"></i><b>13.1</b> Magyar járások COVID-19 halálozási arányai</a></li>
<li class="chapter" data-level="13.2" data-path="többváltozós-ols-regresszió-alapjai.html"><a href="többváltozós-ols-regresszió-alapjai.html#a-többváltozós-lineáris-regresszió-ols-elvű-előállítása"><i class="fa fa-check"></i><b>13.2</b> A Többváltozós Lineáris Regresszió OLS elvű előállítása</a></li>
<li class="chapter" data-level="13.3" data-path="többváltozós-ols-regresszió-alapjai.html"><a href="többváltozós-ols-regresszió-alapjai.html#a-magyarázóváltozók-marginális-hatása"><i class="fa fa-check"></i><b>13.3</b> A magyarázóváltozók marginális hatása</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="többváltozós-ols-regresszió-alapjai.html"><a href="többváltozós-ols-regresszió-alapjai.html#útelemzés"><i class="fa fa-check"></i><b>13.3.1</b> Útelemzés</a></li>
<li class="chapter" data-level="13.3.2" data-path="többváltozós-ols-regresszió-alapjai.html"><a href="többváltozós-ols-regresszió-alapjai.html#parciális-t-próba"><i class="fa fa-check"></i><b>13.3.2</b> Parciális t-próba</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="többváltozós-ols-regresszió-alapjai.html"><a href="többváltozós-ols-regresszió-alapjai.html#magyarázóváltozók-fontossági-sorrendjének-megállapítása-t-próba-alapján"><i class="fa fa-check"></i><b>13.4</b> Magyarázóváltozók fontossági sorrendjének megállapítása t-próba alapján</a></li>
<li class="chapter" data-level="13.5" data-path="többváltozós-ols-regresszió-alapjai.html"><a href="többváltozós-ols-regresszió-alapjai.html#konfidencia-intervallumok-és-a-t-próba-kapcsolata"><i class="fa fa-check"></i><b>13.5</b> 5. Konfidencia-intervallumok és a t-próba kapcsolata</a></li>
<li class="chapter" data-level="13.6" data-path="többváltozós-ols-regresszió-alapjai.html"><a href="többváltozós-ols-regresszió-alapjai.html#nominális-magyarázóváltozók---használtautó-adatok"><i class="fa fa-check"></i><b>13.6</b> Nominális magyarázóváltozók - Használtautó adatok</a></li>
<li class="chapter" data-level="13.7" data-path="többváltozós-ols-regresszió-alapjai.html"><a href="többváltozós-ols-regresszió-alapjai.html#dummy-változók-és-működésük-pythonban"><i class="fa fa-check"></i><b>13.7</b> Dummy változók és működésük Pythonban</a>
<ul>
<li class="chapter" data-level="13.7.1" data-path="többváltozós-ols-regresszió-alapjai.html"><a href="többváltozós-ols-regresszió-alapjai.html#referencia-kategória-megváltoztatása"><i class="fa fa-check"></i><b>13.7.1</b> Referencia kategória megváltoztatása</a></li>
</ul></li>
<li class="chapter" data-level="13.8" data-path="többváltozós-ols-regresszió-alapjai.html"><a href="többváltozós-ols-regresszió-alapjai.html#a-korrigált-r-négyzet-mutató"><i class="fa fa-check"></i><b>13.8</b> A korrigált R-négyzet mutató</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Bookdownban szerkesztve</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Következtető Statisztika Python Jegyzet</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="egymintás-és-kétmintás-próbák" class="section level1 hasAnchor" number="10">
<h1><span class="header-section-number">10</span> Egymintás és Kétmintás próbák<a href="egymintás-és-kétmintás-próbák.html#egymintás-és-kétmintás-próbák" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="a-szórásra-vonatkozó-chi2-próba" class="section level2 hasAnchor" number="10.1">
<h2><span class="header-section-number">10.1</span> A szórásra vonatkozó <span class="math inline">\(\chi^2\)</span>-próba<a href="egymintás-és-kétmintás-próbák.html#a-szórásra-vonatkozó-chi2-próba" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Vegyük elő újra a <a href="https://github.com/KoLa992/Kovetkezteto-Statisztika-Python-Jegyzet/blob/main/ESS2020.xlsx" target="_blank">ESS2020.xlsx</a> fájlban található adatbázist! Emlékeztetőül álljon itt, hogy ez az adatbázis a 2020-ban végzett európai szociális felmérés (European Social Survey 2020 = ESS2020) 1849 magyar kitöltöjének válaszait tartalmazza 14 kérdésre (plusz van egy <em>id</em> oszlop).</p>
<p>Ugyebár a <a href="https://kola992.github.io/Kovetkezteto-Statisztika-Python-Jegyzet/a-sokas%C3%A1gi-%C3%A1tlag-intervallumbecsl%C3%A9se.html#feladat-10" target="_blank">6.4. fejezet 2. feladatában</a> azt mondtuk, hogy ha az adatbázis valamelyik oszlopában üres értéket találunk, akkor az azt jelenti, hogy az adott sorban lévő kitöltő nem válaszolt a kérdésre. Az adatbázisban szereplő kitöltők a teljes 18 év feletti magyar népességből vett véletlen mintaként kezelhetők.</p>
<p>Először is töltsök be az adatbázist ismét az Excelből egy <code>pandas</code> data frame-be és nézzük meg az <code>info</code> metódussal milyen oszlopaink (azaz ismérveink) vannak!</p>
<div class="sourceCode" id="cb852"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb852-1"><a href="egymintás-és-kétmintás-próbák.html#cb852-1" tabindex="-1"></a><span class="co"># Elemzéshez és ábrázoláshoz szükséges csomagok betöltése</span></span>
<span id="cb852-2"><a href="egymintás-és-kétmintás-próbák.html#cb852-2" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb852-3"><a href="egymintás-és-kétmintás-próbák.html#cb852-3" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb852-4"><a href="egymintás-és-kétmintás-próbák.html#cb852-4" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb852-5"><a href="egymintás-és-kétmintás-próbák.html#cb852-5" tabindex="-1"></a><span class="im">import</span> scipy.stats <span class="im">as</span> stats</span>
<span id="cb852-6"><a href="egymintás-és-kétmintás-próbák.html#cb852-6" tabindex="-1"></a></span>
<span id="cb852-7"><a href="egymintás-és-kétmintás-próbák.html#cb852-7" tabindex="-1"></a><span class="co"># Adatbeolvasás data frame-be</span></span>
<span id="cb852-8"><a href="egymintás-és-kétmintás-próbák.html#cb852-8" tabindex="-1"></a>ess <span class="op">=</span> pd.read_excel(<span class="st">&quot;ESS2020.xlsx&quot;</span>)</span>
<span id="cb852-9"><a href="egymintás-és-kétmintás-próbák.html#cb852-9" tabindex="-1"></a>ess.info()</span></code></pre></div>
<pre><code>## &lt;class &#39;pandas.core.frame.DataFrame&#39;&gt;
## RangeIndex: 1849 entries, 0 to 1848
## Data columns (total 15 columns):
##  #   Column                          Non-Null Count  Dtype  
## ---  ------                          --------------  -----  
##  0   id                              1849 non-null   int64  
##  1   PoliticalRadioTVPerDay_Minutes  1796 non-null   float64
##  2   NetUsePerDay_Minutes            1099 non-null   float64
##  3   TrustInParlament                1849 non-null   object 
##  4   PoliticalPartyPref              1849 non-null   object 
##  5   Education_Years                 1830 non-null   float64
##  6   WeeklyWork_Hours                685 non-null    float64
##  7   Region                          1849 non-null   object 
##  8   County                          1849 non-null   object 
##  9   SecretGroupInfluenceWorldPol    1849 non-null   object 
##  10  ScientistsDecievePublic         1849 non-null   object 
##  11  COVID19                         1849 non-null   object 
##  12  ContactCOVID19                  1849 non-null   object 
##  13  GetVaccince                     1849 non-null   object 
##  14  SomeContactCOVID19              1849 non-null   object 
## dtypes: float64(4), int64(1), object(10)
## memory usage: 216.8+ KB</code></pre>
<p>Láthatjuk, hogy megvan mind a 14+1 oszlopunk a megfelelő adattípusokkal. Hurrá! :)</p>
<p>Nézzünk most egy olyan <strong>hipotézisvizsgálat</strong>ot, ami <strong>szórásra vonatkozik</strong>.<br>
Lehet egy olyan állításunk, ami szerint a teljes népességben a <strong>heti munkaidő szórása legalább 15 óra</strong>. Ezt a szokásos elvek alapján át tudjuk alakítani null- és alternatív hipotézissé. Ez az álítás a <strong>‘legalább’ kulcsszó miatt engedi az egyenlőséget (<span class="math inline">\(\geq\)</span>), így az állítás maga egy <span class="math inline">\(H_0\)</span> lesz</strong>. Míg <strong>a <span class="math inline">\(H_1\)</span> ennek a tagadása lesz <span class="math inline">\(&lt;\)</span>, hiszen a <span class="math inline">\(H_0\)</span> és <span class="math inline">\(H_1\)</span> egymást kizáró állításként kell megfogalmazni</strong>.<br>
Tehát, ezek alapján az állítás a heti munkaidő sokasági szórásáról, a <span class="math inline">\(\sigma\)</span>-ról az alábbi módon néz ki <span class="math inline">\(H_0\)</span>-al és <span class="math inline">\(H_1\)</span>-el:</p>
<ul>
<li><span class="math inline">\(H_0: \sigma \geq 15\)</span></li>
<li><span class="math inline">\(H_1: \sigma &lt; 15\)</span></li>
<li>Szurkolunk: <span class="math inline">\(H_0\)</span></li>
</ul>
<p>Ebben a felírásban az <strong>elvi szórásunk a <span class="math inline">\(15\)</span> óra</strong>, hiszen a valós sokasági szórásnak a viszonyát ehhez képest vizsgáljuk majd a mintánk alapján. Ezt az elvi szórást <span class="math inline">\(\sigma_0=15\)</span>-nek jelöljük.</p>
<p>Ezzel megvolnánk a hipotézisvizsgálatunk 1. pontjával, a <span class="math inline">\(H_0\)</span> és <span class="math inline">\(H_1\)</span> felírásával. Most ugrunk a 2. és igazából a 3. pontra is, a próbafüggvény meghatározásához, majd a p-érték számolásához. <strong>Szórás esetében a próbafüggvény</strong> a következő alakot ölti: <span class="math display">\[\frac{(n-1)s^2}{\sigma_0^2} \sim \chi^2(n-1)\]</span></p>
<p>A <span class="math inline">\(\sim \chi^2(n-1)\)</span> jelölés azt mondja, hogy a <strong>p-értéket egy <span class="math inline">\(n-1\)</span> szabadságfokú <span class="math inline">\(\chi^2\)</span> eloszlásból</strong> kell majd kiszámolnunk.</p>
<p>Sajnos, <strong>erre a próbafüggvényre és p-értékre nincs Python beépített függvény, így muszáj kiszámolnunk a dolgokat manuálisan!</strong></p>
<p>Viszont, a próbafüggvényben minden betűt ismerünk. Ugye az előbb letisztéztuk, hogy a <span class="math inline">\(\sigma_0\)</span> az elvi szórás, az <span class="math inline">\(n\)</span> szokásos müódon a mintánk elemszáma és az <span class="math inline">\(s\)</span> a korrigált (tehát torzítatlan becslést adó) mintaszórás. Ezeket az értékeket gyorsan ki tudjuk számolni. Az ESS adatbázisban a heti munkaórára vonatkozó adatai a kitöltőknek a <code>WeeklyWork_Hours</code> oszlopban laknak. Arra kell a számolásnél figyelni, hogy az ESS adatbázis <code>info()</code> metódusának eredményéből láthattuk, hogy <strong>ebben a <code>WeeklyWork_Hours</code> oszlopban van egy rakat hiányzó érték</strong>, így <span class="math inline">\(n\)</span>-ünk az nem <span class="math inline">\(1849\)</span> (data frame sorainak a száma), hanem csak <span class="math inline">\(685\)</span>. Ezt úgy tudjuk legkönnyebben figyelembe venni, hogy az <span class="math inline">\(n\)</span>-t a <code>WeeklyWork_Hours</code> oszlop <code>count()</code> metódusával számítjuk ki, ami megadja az oszlopban a nem üres értékek számát.</p>
<div class="sourceCode" id="cb854"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb854-1"><a href="egymintás-és-kétmintás-próbák.html#cb854-1" tabindex="-1"></a>elvi_szórás <span class="op">=</span> <span class="dv">15</span></span>
<span id="cb854-2"><a href="egymintás-és-kétmintás-próbák.html#cb854-2" tabindex="-1"></a>n <span class="op">=</span> ess.WeeklyWork_Hours.count()</span>
<span id="cb854-3"><a href="egymintás-és-kétmintás-próbák.html#cb854-3" tabindex="-1"></a>s <span class="op">=</span> np.std(ess.WeeklyWork_Hours, ddof<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb854-4"><a href="egymintás-és-kétmintás-próbák.html#cb854-4" tabindex="-1"></a>s</span></code></pre></div>
<pre><code>## 15.375457568374705</code></pre>
<p>Láthatjuk, hogy a mintában a szórás <span class="math inline">\(s=15.37\)</span>, ami nagyobb mint a <span class="math inline">\(15\)</span>-ös elvi szórás. De <strong>nem vehetjük automatikusan igaznak <span class="math inline">\(H_0\)</span>-t, hiszen ez a jelenség lehet csak a mintavételi hiba műve!</strong> Épp <strong>azért kell p-értéket számolni, hogy megtudjuk, mekkora valószínűséggel lehet ez a jelenség</strong> (hogy a mintaszórás nagyobb, mint a 15-ös elvi érték) <strong>csak a mintavételi hiba műve</strong>.</p>
<p>Szóval, számoljuk csak ki ezt a próbafüggvényt! :)</p>
<div class="sourceCode" id="cb856"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb856-1"><a href="egymintás-és-kétmintás-próbák.html#cb856-1" tabindex="-1"></a>próbafv <span class="op">=</span> (n<span class="op">-</span><span class="dv">1</span>)<span class="op">*</span>s<span class="op">**</span><span class="dv">2</span><span class="op">/</span>elvi_szórás<span class="op">**</span><span class="dv">2</span></span>
<span id="cb856-2"><a href="egymintás-és-kétmintás-próbák.html#cb856-2" tabindex="-1"></a>próbafv</span></code></pre></div>
<pre><code>## 718.6702741281487</code></pre>
<p>Szép és jó ez az érték, de önmagában nem sokat mond. :) Ugorjunk is a 3. pontra, a p-érték számítására. Ugye azt megállapítottuk már az előbb, hogy a p-értéket most <span class="math inline">\(n-1\)</span> szabadságfokú <span class="math inline">\(\chi^2\)</span> eloszlásból számoljuk. Plusz, <strong>mivel a <span class="math inline">\(H_1\)</span>-ben <span class="math inline">\(&lt;\)</span> jel van, így a számítás balodali módon történik</strong>, azaz <strong>a <span class="math inline">\(\chi^2(n-1)\)</span> eloszlásban a próbafüggvény alá esés valószínűsége érdekel</strong>. Az <strong>elv itt ugyan az, amit láttunk a <a href="https://kola992.github.io/Kovetkezteto-Statisztika-Python-Jegyzet/hipot%C3%A9zisvizsg%C3%A1lat-alapjai.html#a-sokas%C3%A1gi-%C3%A1tlagra-vonatkoz%C3%B3-t-pr%C3%B3ba" target="_blank">9.2. fejezetben</a>.</strong></p>
<p>Ezek alapján meg is van a p-értékünk a <code>stats.chi2.cdf</code> függvénnyel.</p>
<div class="sourceCode" id="cb858"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb858-1"><a href="egymintás-és-kétmintás-próbák.html#cb858-1" tabindex="-1"></a>stats.chi2.cdf(próbafv, df<span class="op">=</span>n<span class="op">-</span><span class="dv">1</span>)</span></code></pre></div>
<pre><code>## 0.8263764489186204</code></pre>
<p>A p-érték = <span class="math inline">\(82.6\%\)</span> lett, ami szerint a megfigyelt minta alapján a <span class="math inline">\(H_0\)</span>-t elutasítani <span class="math inline">\(82.6\%\)</span> hibavalószínűséggel jár. Ez jó magas hibavalószínűség így “szabad szemmel” is, de technikailag ha nézem, akkor <strong>ez a p-érték magasabb még a legmagasabb szokásos szignifikancia-szintnél</strong>, a <span class="math inline">\(10\%\)</span>-nál <strong>is</strong>, így <strong>a <span class="math inline">\(H_0\)</span>-t nem utasítjuk el</strong>, mert ez a döntés túl nagy hibával járna. Ez alapján pedig azt mondhatjuk, hogy <strong>a heti munkaidők szórása a teljes népességben (sokaságban) is legalább 15 órának kinéz</strong>.</p>
<p>Sajnos ennek a <span class="math inline">\(\chi^2\)</span> próbának ugyan az a baja, mint a <span class="math inline">\(\chi^2\)</span> eloszlásos intervallumbecslésnek volt a <a href="https://kola992.github.io/Kovetkezteto-Statisztika-Python-Jegyzet/tov%C3%A1bbi-fae-becsl%C3%A9sek-%C3%A9s-a-bootstrap-m%C3%B3dszer.html#a-sz%C3%B3r%C3%A1s-bootstrap-intervallumbecsl%C3%A9se" target="_blank">7.5. fejezetben</a>: A próba elvégézésének <strong>előfeltétele, hogy az adataink normális eloszlásúak legyenek</strong>. tehát, a számított p-értékünk, a <span class="math inline">\(82.6\%\)</span>, az akkor valid, ha az adatsor, aminek a szórását vizsgáljuk normális eloszlást követ.<br>
Ezt egy hisztogrammal gyorsan ellenőrizni is tudjuk.</p>
<div class="sourceCode" id="cb860"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb860-1"><a href="egymintás-és-kétmintás-próbák.html#cb860-1" tabindex="-1"></a>ess.WeeklyWork_Hours.hist()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-357-29.png" width="672" /></p>
<p>Ajjaj, a munkaórák eloszlása csúcsosnak tűnik, mint a fene. Ez így nem egy normális eloszlás, az előfeltételünk nem teljesül, a számított p-értékünk nem megbízható … <em>BigRIP</em> :(<br>
Esetleg próbálkozhatunk az estrém outlier <span class="math inline">\(160\)</span> óra kiszűrésével, hátha csak az okozza a csúcsosságot, de sajnos nem járunk sikerrel, ez a hisztogram az outlier szűrés után is elég csúcsos.</p>
<div class="sourceCode" id="cb861"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb861-1"><a href="egymintás-és-kétmintás-próbák.html#cb861-1" tabindex="-1"></a>ess.WeeklyWork_Hours[ess.WeeklyWork_Hours <span class="op">&lt;</span> <span class="dv">160</span>].hist()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-358-31.png" width="672" /></p>
<p>De amúgy ez nem meglepő: a legtöbb kitöltő valószínűleg a “standard” heti 40 órát (vagy ahhoz közeli értéket) adott meg válaszként, és ez okozza a csúcsosságot.</p>
<p>Amúgy, ez az <strong>előfeltétel az oka, hogy nincs erre a hipotézisvizsgálatra beépített függvény Pythonban: nagyon ritka, hogy egy adatsor szép normális eloszlású legyen</strong>, így a legtöbb esetben a próba nem megbízható, mivel a <span class="math inline">\(\chi^2(n-1)\)</span> eloszlásból számított p-érték mögötti feltételek nem teljesülnek a legtöbb esetben.<br>
Emiatt ritka, hogy a próba valid eredményeket produkál, így egy programozó sem kódolta le Pythonban, mert ritkán kell ez a hipotézisvizsgálat gyakorlatban. Mi is inkább “történelmi okokból” tanítjuk. Meg hogy minél több dolgot lehessen számonkérni. :)</p>
</div>
<div id="a-kétmintás-hipotézisvizsgálatok-elve" class="section level2 hasAnchor" number="10.2">
<h2><span class="header-section-number">10.2</span> A kétmintás hipotézisvizsgálatok elve<a href="egymintás-és-kétmintás-próbák.html#a-kétmintás-hipotézisvizsgálatok-elve" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Az <strong>eddig</strong> tanult hipotézisvizsgálatok az átlagra, arányra és szórásra úgynevezett <strong>egymintás hipotézisvizsgálatok</strong> voltak. Ez azt jelentette, hogy egy db statisztikai mutató (egy db átlag, egy db arány vagy éppen egy db szórás) viszonyát vizsgáltuk valami elvi értékhez képest. Ez alapján fogalmaztuk meg az előfeltevéseinket, azaz hipotéziseinket.</p>
<p><strong>Mostantól</strong> viszont úgynevezett <strong>kétmintás hipotézisvizsgálatok</strong>kal vagy más néven <strong>kétmintás próbák</strong>kal foglalkoznunk. Ez pedig azt fogja jelenti, hogy a <strong>hipotéziseinkben</strong> (előfeltevéseinkben) mindig <strong>két db statisztikai mutató</strong> (két db átlag, két db arány, stb.) <strong>viszonyát vizsgáljuk majd egymáshoz képest</strong>.</p>
<p>Tehát, ha <strong>példának az átlagot veszem</strong>, mint statisztikai mutatót, akkor <strong>egy</strong> olyan <strong>kétmintás állítás</strong>t mondhatok, hogy <strong>“a férfi átlagfizetés magasabb, mint a női átlagfizetés Magyarországon”</strong>.<br>
Kicsit matekosabban felírva: <strong>Átlagfizu(Férfi) &gt; Átlagfizu(Nő)</strong></p>
<p><strong>Azért lesznek az ilyen két statisztikai mutatós állításokhoz tartozó hipotézisvizsgálatok kétmintás próbák, mert az a logika, hogy 1 db mintánka van a férfi átlaghoz és 1 db mintánk van a női átlaghoz</strong>. Tehát, összességében 2 db mintával dolgozunk. :)</p>
<p>A kérdés, hogyan lesznek ezekből a kétmintás állításokból null- és alternatív hipotézisek. A <strong>trükk</strong>ünk az, hogy <strong>átrendezzük az állítást</strong> leíró egyenlőtlenséget <strong>úgy, hogy a két statisztikai mutató KÜLÖNBSÉGÉNEK a viszonyát vizsgáljuk egy elvi értékhez</strong> képest. Ez az elvi érték lesz az elvi eltérés, általában <span class="math inline">\(\delta_0\)</span>-nak jelöljük. Arányok esetében néha szokás <span class="math inline">\(\epsilon_0\)</span>-t is használni az elvi eltérés jelölésére.</p>
<p>Az előbbi átlagfizetéses példában, ha a sokasági átlagokat továbbra is <span class="math inline">\(\mu\)</span>-vel jelölöm, mint a korábbi hetek tananyagaiban, akkor az <strong>átrendezett állítás</strong> a következő lesz: <span class="math display">\[\mu_{Férfi} - \mu_{Női} &gt; 0\]</span></p>
<p>És akkor itt <span class="math inline">\(\delta_0=0\)</span> esetünk van. Ebből az <strong>eddigi elvek mentén lehet a különbségre felírni <span class="math inline">\(H_0\)</span>-t és <span class="math inline">\(H_1\)</span>-et</strong>:</p>
<ol style="list-style-type: decimal">
<li>Ha az <strong>állítás megengedi az egyenlőséget, akkor az <span class="math inline">\(H_0\)</span>, egyébként <span class="math inline">\(H_1\)</span>-be</strong> megy.</li>
<li><strong>A <span class="math inline">\(H_0\)</span> és <span class="math inline">\(H_1\)</span> egymást kizáró, ellentétes állítások</strong>.</li>
</ol>
<p>Szóval, a férfi-női átlagkeresetes példánkon a <span class="math inline">\(H_0\)</span> és <span class="math inline">\(H_1\)</span> állítások a következők:</p>
<ul>
<li><span class="math inline">\(H_0:\mu_{Férfi} - \mu_{Női} \leq 0\)</span></li>
<li><span class="math inline">\(H_1:\mu_{Férfi} - \mu_{Női} &gt; 0\)</span></li>
<li>Szurkolunk: <span class="math inline">\(H_1\)</span></li>
</ul>
<p>Nézzünk egy olyan példát, amikor a <span class="math inline">\(\delta_0 \neq 0\)</span>! Legyen az az állításunk, hogy <strong>“a férfi átlagkereset legalább 100 ezer Ft-tal magasabb, mint a női”</strong>. Ekkor azt csináljuk, hogy első körben írjuk fel úgy az állítást, mintha csak annyi lenne, hogy <em>“a férfi átlagkereset legalább annyi, mint a női”</em>. Tehát, mintha a különbségre adott számértékünk (a 100 ezer Ft) ott sem lenne. A <em>“legalább”</em> kifejezés miatt ez egy <span class="math inline">\(\geq\)</span>-s állítás lesz: <span class="math display">\[\mu_{Férfi} \geq  \mu_{Női}\]</span></p>
<p>És ezt a fenti egyenlőtlenséget egészítsük úgy ki, hogy belevesszük a 100 ezer Ft-os különbséget. A <em>“férfi átlagkereset legalább 100 ezer Ft-tal magasabb, mint a női”</em> azt jelenti másképpen, hogy ha a <strong>női átlagkeresethez még 100 ezret hozzáadok, akkor is nagyobb vagy egyenlő ennél a férfi átlagkereset</strong>. Ez a megfogalmazás pedig alábbi módon néz ki az egyenlőtlenségünkben: <span class="math display">\[\mu_{Férfi} \geq  \mu_{Női} + 100\]</span></p>
<p>Innentől kezdve megvan az állításom, amit már könnyű <strong>átrendezni</strong> úgy, hogy <strong>azt vizsgálja az egyenlőtlenség, hogy az átlagok különbsége hogyan viszonyul valami elvi, <span class="math inline">\(\delta_0\)</span> eltéréshez</strong>, ami most nekem a 100-as érték: <span class="math display">\[\mu_{Férfi} -  \mu_{Női} \geq 100\]</span></p>
<p>Tehát, ebben az állításban akkor <span class="math inline">\(\delta_0=100\)</span>. És ezt az állítást a szokásos két alapelv mellett már gyorsan tudom <span class="math inline">\(H_0\)</span>-ra és <span class="math inline">\(H_1\)</span>-re szétszedni. Mivel az állítás engedi az egyenlőséget most, így az állításunkból egy nullhipotézis lesz, és az alternatív hipotézisben ezt az állítást meg tagadjuk, és vélgül a <span class="math inline">\(H_0\)</span>-nak szurkolunk, mert abban lakik az eredeti állításunk:</p>
<ul>
<li><span class="math inline">\(H_0:\mu_{Férfi} - \mu_{Női} \geq 100\)</span></li>
<li><span class="math inline">\(H_1:\mu_{Férfi} - \mu_{Női} &lt; 100\)</span></li>
<li>Szurkolunk: <span class="math inline">\(H_0\)</span></li>
</ul>
<p>Akkor, lássuk hogy működik a kétmintás <span class="math inline">\(H_0\)</span> és <span class="math inline">\(H_1\)</span> párokhoz a p-érték számolás pár gyakorlati példán! :)</p>
</div>
<div id="az-átlagokra-vonatkozó-kétmintás-z-próba" class="section level2 hasAnchor" number="10.3">
<h2><span class="header-section-number">10.3</span> Az átlagokra vonatkozó kétmintás <em>z-próba</em><a href="egymintás-és-kétmintás-próbák.html#az-átlagokra-vonatkozó-kétmintás-z-próba" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Az ESS adatbázis <code>SecretGroupInfluenceWorldPol</code> és <code>Education_Years</code> című oszlopait felhasználva ellenőrizhetünk egy olyan állítást a teljes magyar népességre (azaz sokaságra), ami szerint <strong>“átlagban jobban iskolázottak</strong> (több évet töltöttek tanulással), <strong>akik nem hisznek abban, hogy egy titkos társaság irányítja a világpolitikát”</strong>.</p>
<p>Ezt az alááítást úgy írhatjuk fel matematika egyenlőtlenségként mint <span class="math inline">\(\mu_{NemHisz} &gt; \mu_{Hisz}\)</span>. Ha ezt az állítást az átlagok különbségére rendezzük át, akkor a <span class="math inline">\(H_1:\mu_{NemHisz} - \mu_{Hisz} &gt; 0\)</span> egyenlőtlenséget kapjuk. Ez alapján pedig már látjuk is, hogy az átlagok elvi eltérése a sokaságban <span class="math inline">\(\delta_0=0\)</span>.<br>
Ezt az állítást a szokásos két alapelv mellett már gyorsan tudom <span class="math inline">\(H_0\)</span>-ra és <span class="math inline">\(H_1\)</span>-re szétszedni. Mivel az állítás <em>nem</em> engedi az egyenlőséget most, így az állításunkból egy <span class="math inline">\(H_1\)</span> lesz, és a <span class="math inline">\(H_0\)</span>-ban ezt az állítást meg tagadjuk, és vélgül a <span class="math inline">\(H_1\)</span>-nek szurkolunk, mert abban lakik az eredeti állításunk:</p>
<ul>
<li><span class="math inline">\(H_0:\mu_{NemHisz} - \mu_{Hisz} \leq 0\)</span></li>
<li><span class="math inline">\(H_1:\mu_{NemHisz} - \mu_{Hisz} &gt; 0\)</span></li>
<li>Szurkolunk: <span class="math inline">\(H_1\)</span></li>
</ul>
<p>A hipotézisvizsgálatok 2. pontja alapján most kezdjük el megvizsgálni a megfigyelt mintánk adatait. Esetünkben az átlagos oktatási évek eltérését a két csoport (<em>Hisz</em> és <em>NemHisz</em> a titkos társaságok uralmában a világpolitika felett) között könnyen ki tudjuk számolni egy data frame <code>groupby</code> metódussal. Közben az elvi eltérés (<span class="math inline">\(\delta_0\)</span>) <span class="math inline">\(0\)</span>-ás értékét is elrakom egy külön objektumba.</p>
<div class="sourceCode" id="cb862"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb862-1"><a href="egymintás-és-kétmintás-próbák.html#cb862-1" tabindex="-1"></a>elvi_eltérés_átlagban <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb862-2"><a href="egymintás-és-kétmintás-próbák.html#cb862-2" tabindex="-1"></a></span>
<span id="cb862-3"><a href="egymintás-és-kétmintás-próbák.html#cb862-3" tabindex="-1"></a><span class="co"># két mintaátlag</span></span>
<span id="cb862-4"><a href="egymintás-és-kétmintás-próbák.html#cb862-4" tabindex="-1"></a>ess.groupby(<span class="st">&#39;SecretGroupInfluenceWorldPol&#39;</span>).Education_Years.mean()</span></code></pre></div>
<pre><code>## SecretGroupInfluenceWorldPol
## No     12.289596
## Yes    11.966790
## Name: Education_Years, dtype: float64</code></pre>
<p>Láthatjuk, hogy a mintában a <em>NemHisz</em> csoport átlagos oktatásban töltött éveinek száma némileg magasabb, mint a <em>Hisz</em> csoport esetén ez az átlag. De <strong>nem vehetjük automatikusan igaznak <span class="math inline">\(H_1\)</span>-et, hiszen ez a jelenség lehet csak a mintavételi hiba műve!</strong> Épp <strong>azért kell p-értéket számolni, hogy megtudjuk, mekkora valószínűséggel lehet ez a jelenség</strong> (hogy a <em>NemHisz</em> csoport esetén magasabb az átlag) <strong>csak a mintavételi hiba műve</strong>.</p>
<p>Szóval, számoljuk csak ki ezt a próbafüggvényt! :)</p>
<p>A próbafüggvényünk formulája alább látható, és azt is megfigyelhetjük az következő képletből, hogy a nevezetes eloszlásunk a p-érték számításához standard normális (<span class="math inline">\(N(0,1)\)</span>): <span class="math display">\[\frac{(\bar{y_1}-\bar{y_2})-\delta_0}{\sqrt{\frac{s_1^2}{n_1}+\frac{s_2^2}{n_2}}} \sim N(0,1)\]</span></p>
<p>Láthatjuk, hogy a próbafüggvény képlete nem egy bonyolult konstrukció. Fogjuk a két mintaátlag különbségét (<span class="math inline">\(\bar{y_1}-\bar{y_2}\)</span>) és megnézzük, hogy ez mennyire tér el az elvi különbségtől (<span class="math inline">\(\delta_0\)</span>) és ezt arányítjuk a kétféle átlaghoz tartozó standard hiba négyzetek összegéhez a gyök alatt. Viszont, van erre az úgynevezett <strong>kétmintás z-próbára beépített függvény</strong> a <code>statsmodels</code> csomagban, ami a próbafüggvényt és a p-értéket kiszámolja, így <strong>nem kell ezzel manuálisan szórakoznunk</strong> majd. :)<br>
Ugye ismét azért lesz <em>z-próba</em> a hipotézisvizsgálatunk neve, mert a pórbafüggvényből standard normális, azaz <span class="math inline">\(z\)</span> eloszláson keresztül lesz p-értékünk.</p>
<p>Viszont, azt <strong>mindenképpen látnunk kell, hogy mivel a p-érték számításhoz vett eloszlás standard normális</strong> (<span class="math inline">\(N(0,1)\)</span>), így <strong>mindkét mintának</strong> (<em>Hisz</em> és <em>Nem Hisz</em> is) <strong>nagynak</strong> (<span class="math inline">\(n&gt;30\)</span>) <strong>kell lennie</strong>!<br>
Ezt a <code>SecretGroupInfluenceWorldPol</code> oszlop <code>value_counts()</code> metódusával tudjuk talán a legkönnyebben ellenőrizni.</p>
<div class="sourceCode" id="cb864"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb864-1"><a href="egymintás-és-kétmintás-próbák.html#cb864-1" tabindex="-1"></a>ess.SecretGroupInfluenceWorldPol.value_counts()</span></code></pre></div>
<pre><code>## SecretGroupInfluenceWorldPol
## No     1301
## Yes     548
## Name: count, dtype: int64</code></pre>
<p>Mivel <span class="math inline">\(1301&gt;30\)</span> és <span class="math inline">\(548&gt;30\)</span>, így a <strong>nagy minta előfeltételünk teljesült</strong>.</p>
<p>Lássuk hát a <strong>p-érték számolás</strong>át a <code>ztest</code> beépített függvénnyel a <code>statsmodels</code> csomagból.<br>
A <strong>függvényben a következő paraméterek</strong>et kell megadni:</p>
<ul>
<li><code>x1</code> és <code>x2</code>: A két minta elemeit tartalmazó tömbök <em>hiányzó értékek nélkül</em>.
<ul>
<li>Tehát, a biztonság kedvéért, miután leszűrjük az <code>Education_Years</code> oszlop értékeit a <em>Hisz</em> és <em>NemHisz</em> csoportokra a <code>SecretGroupInfluenceWorldPol</code> oszlop alapján, még a biztonság kedvéért megkínáljuk a dolgot egy <code>dropna()</code> metódussal is.</li>
<li>Arra kell figyelni, hogy a függvényben a kivonás iránya <code>x1 - x2</code>. Tehát, a két csoport átadásának sorrendje következetes kell legyen a <span class="math inline">\(H_0\)</span> és <span class="math inline">\(H_1\)</span>-ben alkalmazott kivonások irányával. Nekünk ez most azt jelenti, hogy elsőnek a <em>NemHisz</em> csoport <code>Education_Years</code> értékeit adjuk át (az <code>x1</code> paraméteren), mert a hipotéziseinkben <span class="math inline">\(\mu_{NemHisz} - \mu_{Hisz}\)</span> kivonás szerepel.</li>
</ul></li>
<li><code>value</code>: Az átlagok közti elvi eltérés értéke a hipotéziseinkben. Ez most nekünk <span class="math inline">\(\delta_0=0\)</span>.</li>
<li><code>alternative</code>: Az alteranítv hipotézisben lévő relációs jelet adjuk meg szövegesen.
<ul>
<li>lehetséges értékek: <code>‘two-sided’, ‘smaller’, ‘larger’</code>, rendre a <span class="math inline">\(\neq\)</span>, <span class="math inline">\(&lt;\)</span>, <span class="math inline">\(&gt;\)</span> relációs jeleket jelölik <span class="math inline">\(H_1\)</span>-ben</li>
</ul></li>
</ul>
<p>Ezzel a működés a következőképpen néz ki.</p>
<div class="sourceCode" id="cb866"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb866-1"><a href="egymintás-és-kétmintás-próbák.html#cb866-1" tabindex="-1"></a><span class="co"># függvény importja</span></span>
<span id="cb866-2"><a href="egymintás-és-kétmintás-próbák.html#cb866-2" tabindex="-1"></a><span class="im">from</span> statsmodels.stats.weightstats <span class="im">import</span> ztest</span>
<span id="cb866-3"><a href="egymintás-és-kétmintás-próbák.html#cb866-3" tabindex="-1"></a></span>
<span id="cb866-4"><a href="egymintás-és-kétmintás-próbák.html#cb866-4" tabindex="-1"></a>ztest(x1<span class="op">=</span> ess.Education_Years[ess.SecretGroupInfluenceWorldPol<span class="op">==</span><span class="st">&#39;No&#39;</span>].dropna(),</span>
<span id="cb866-5"><a href="egymintás-és-kétmintás-próbák.html#cb866-5" tabindex="-1"></a>      x2<span class="op">=</span> ess.Education_Years[ess.SecretGroupInfluenceWorldPol<span class="op">==</span><span class="st">&#39;Yes&#39;</span>].dropna(),</span>
<span id="cb866-6"><a href="egymintás-és-kétmintás-próbák.html#cb866-6" tabindex="-1"></a>      value<span class="op">=</span>elvi_eltérés_átlagban,</span>
<span id="cb866-7"><a href="egymintás-és-kétmintás-próbák.html#cb866-7" tabindex="-1"></a>      alternative<span class="op">=</span><span class="st">&#39;larger&#39;</span>)</span></code></pre></div>
<pre><code>## (1.8415694788119368, 0.03276907446405458)</code></pre>
<p>Az eredményül kapott lista első eleme a próbafüggvény, és a második elem a p-érték. Tehát, a <strong>p-értékünk most <span class="math inline">\(3.3\%\)</span> lett</strong>. Tehát, a <span class="math inline">\(H_0\)</span> elutasításával <span class="math inline">\(3.3\%\)</span> a hibavalószínűségem. Ha a megengedett hibavalószínűségem (<span class="math inline">\(\alpha\)</span> szignifikansia-szintem) <span class="math inline">\(1\%\)</span> akkor így nem tudom elutasítani a <span class="math inline">\(H_0\)</span>-t, mert többet hibáznék vele, mint a megengedett, de ha a szignifikancia-szintem <span class="math inline">\(\alpha = 5\%\)</span>, akkor már <span class="math inline">\(H_0\)</span> elutasítható, hiszen kevesebb hibával jár, mint a megengedett.<br>
Azaz, itt most a p-értékkel <strong>bekerültem a szokásos szignifikancia szintek tartományába</strong> (1% és 10% közé), így a <strong>felelős “mondás” most az, hogy nem döntök és inkább kérek egy NAGYOBB mintát, mert a döntés túl érzékeny lenne a konkrét szignifikancia-szint megválasztására</strong>.<br>
Végső soron tehát <strong>NEM tudom egyértelműen kijelenteni, hogy a megfigyelt mintában mért eltérés az átlagos iskolaévekben</strong> a <em>Hisz</em> és <em>NemHisz</em> csoportok között <strong>szignifikáns volna</strong> (azaz, hogy az eltérés nem csak a mintavételi hiba műve). A kérdés <strong>eldöntésére még nagyobb mintát kellene vizsgálni</strong>.</p>
</div>
<div id="az-arányokra-vonatkozó-kétmintás-z-próba" class="section level2 hasAnchor" number="10.4">
<h2><span class="header-section-number">10.4</span> Az arányokra vonatkozó kétmintás <em>z-próba</em><a href="egymintás-és-kétmintás-próbák.html#az-arányokra-vonatkozó-kétmintás-z-próba" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Az ESS adatbázis <code>SecretGroupInfluenceWorldPol</code> és <code>TrustInParlament</code> című oszlopait felhasználva ellenőrizhetünk egy olyan állítást a teljes magyar népességre (azaz sokaságra), ami szerint <strong>“több, mint 2 %-ponttal alacsonyabb a parlamentben bízók aránya azok körében, akik hisznek a titkos társaságokban”</strong>.</p>
<p>A fentri bekezdésben félkövérrel szedett állítás elég agymegsüllyesztő lehet első olvasatra, de talán az élből <strong>látszik, hogy valamiknek a sokasági arányairól</strong>, azaz <span class="math inline">\(P\)</span>-ről szól az állítás. Ha <strong>ilyen arányokra vonatkozó állítást látunk, akkor két dolgot érdemes kihámozni</strong> a szövegből:</p>
<ol style="list-style-type: decimal">
<li><strong>Mi a vizsgált arányunk?</strong> <span class="math inline">\(\rightarrow\)</span> Ez most nekünk a <strong>parlamentben bízók aránya</strong>.</li>
<li><strong>Mi a 2 minta?</strong> <span class="math inline">\(\rightarrow\)</span> Ez most nekünk az, hogy valaki <strong>hisz / nem hisz a titkos társaságok uralmában</strong> a világpolitika felett.</li>
</ol>
<p>Ezek alapján az <strong>állítás matematikailag megadva</strong> a parlamentben bízók arányára vonatkozóan: <span class="math display">\[P_{Hisz} &lt; P_{NemHisz} - 0.02\]</span></p>
<p>Ugye itt <strong>az volt az elv, amit a 2. fejezetben is láttunk</strong>. Ha simán az állítás szövegének <em>“alacsonyabb”</em> kifejezésére koncentrálunk, akkor az egyenlőtlenség <span class="math inline">\(P_{Hisz} &lt; P_{NemHisz}\)</span> lenne. De a <em>“több, mint 2 %-ponttal”</em> rész miatt azt mondjuk, hogy ha a <span class="math inline">\(P_{NemHisz}\)</span>-ből levonok még 2 %-pontot (<span class="math inline">\(0.02\)</span>-t), még akkor is alacsonyabb (azaz kisebb) marad a <span class="math inline">\(P_{Hisz}\)</span>. És így lett a végső egyenlőtlenségünk, ami leírja matenatikailag az alapállításunk <span class="math inline">\(P_{Hisz} &lt; P_{NemHisz} - 0.02\)</span>.</p>
<p>Ezt a kiinduló egeynlőtlenséget, ha <strong>átrendezünk az arányok különbségére</strong>, akkor a <span class="math inline">\(P_{Hisz} - P_{NemHisz} &lt; -0.02\)</span> egyenlőtlenséget kapjuk.</p>
<p>Ezt az állítást a szokásos két alapelv mellett már gyorsan tudom <span class="math inline">\(H_0\)</span>-ra és <span class="math inline">\(H_1\)</span>-re szétszedni. Mivel az állítás <em>nem</em> engedi az egyenlőséget most, így az állításunkból egy <span class="math inline">\(H_1\)</span> lesz, és a <span class="math inline">\(H_0\)</span>-ban ezt az állítást meg tagadjuk, és vélgül a <span class="math inline">\(H_1\)</span>-nek szurkolunk, mert abban lakik az eredeti állításunk:</p>
<ul>
<li><span class="math inline">\(H_0:P_{Hisz} - P_{NemHisz} \geq -0.02\)</span></li>
<li><span class="math inline">\(H_1:P_{Hisz} - P_{NemHisz} &lt; -0.02\)</span></li>
<li>Szurkolunk: <span class="math inline">\(H_1\)</span></li>
</ul>
<p>Jöhet is a hipotézisvizsgálatok 2. pontja, ami szerint elkezdjük megvizsgálni a megfigyelt mintánk adatait. <strong>Számoljuk mindkét mintában (<span class="math inline">\(1=Hisz\)</span> és <span class="math inline">\(2=NemHisz\)</span>) a parlamentben bízók arányát (<span class="math inline">\(p_1\)</span> és <span class="math inline">\(p_2\)</span>)!</strong> Ehhez <strong>mindkét mintában meg kell nézni a teljes elemszámokat</strong> (<span class="math inline">\(n_1\)</span> és <span class="math inline">\(n_2\)</span>), és <strong>az arány szempontjából kedvező esetek</strong> (<span class="math inline">\(k_1\)</span>, <span class="math inline">\(k_2\)</span>) <strong>számát</strong> is.</p>
<div class="sourceCode" id="cb868"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb868-1"><a href="egymintás-és-kétmintás-próbák.html#cb868-1" tabindex="-1"></a>k_1 <span class="op">=</span> np.<span class="bu">sum</span>((ess.TrustInParlament<span class="op">==</span><span class="st">&#39;Yes&#39;</span>) <span class="op">&amp;</span></span>
<span id="cb868-2"><a href="egymintás-és-kétmintás-próbák.html#cb868-2" tabindex="-1"></a>             (ess.SecretGroupInfluenceWorldPol<span class="op">==</span><span class="st">&#39;Yes&#39;</span>))</span>
<span id="cb868-3"><a href="egymintás-és-kétmintás-próbák.html#cb868-3" tabindex="-1"></a>n_1 <span class="op">=</span> np.<span class="bu">sum</span>(ess.SecretGroupInfluenceWorldPol<span class="op">==</span><span class="st">&#39;Yes&#39;</span>)</span>
<span id="cb868-4"><a href="egymintás-és-kétmintás-próbák.html#cb868-4" tabindex="-1"></a></span>
<span id="cb868-5"><a href="egymintás-és-kétmintás-próbák.html#cb868-5" tabindex="-1"></a>k_2 <span class="op">=</span> np.<span class="bu">sum</span>((ess.TrustInParlament<span class="op">==</span><span class="st">&#39;Yes&#39;</span>) <span class="op">&amp;</span></span>
<span id="cb868-6"><a href="egymintás-és-kétmintás-próbák.html#cb868-6" tabindex="-1"></a>             (ess.SecretGroupInfluenceWorldPol<span class="op">==</span><span class="st">&#39;No&#39;</span>))</span>
<span id="cb868-7"><a href="egymintás-és-kétmintás-próbák.html#cb868-7" tabindex="-1"></a>n_2 <span class="op">=</span> np.<span class="bu">sum</span>(ess.SecretGroupInfluenceWorldPol<span class="op">==</span><span class="st">&#39;No&#39;</span>)</span>
<span id="cb868-8"><a href="egymintás-és-kétmintás-próbák.html#cb868-8" tabindex="-1"></a></span>
<span id="cb868-9"><a href="egymintás-és-kétmintás-próbák.html#cb868-9" tabindex="-1"></a><span class="co"># mintaarányok</span></span>
<span id="cb868-10"><a href="egymintás-és-kétmintás-próbák.html#cb868-10" tabindex="-1"></a></span>
<span id="cb868-11"><a href="egymintás-és-kétmintás-próbák.html#cb868-11" tabindex="-1"></a>k_1<span class="op">/</span>n_1 <span class="co"># Hívők mintája</span></span></code></pre></div>
<pre><code>## 0.11131386861313869</code></pre>
<div class="sourceCode" id="cb870"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb870-1"><a href="egymintás-és-kétmintás-próbák.html#cb870-1" tabindex="-1"></a>k_2<span class="op">/</span>n_2 <span class="co"># Nem hívők mintája</span></span></code></pre></div>
<pre><code>## 0.14681014604150652</code></pre>
<p>Láthatjuk, hogy a mintában a <em>Hisz</em> csoportban a parlamentben bízók aránya tényleg több, mint 2 %-ponttal alacsonyabb, mint a <em>NemHisz</em> csoport esetén ez az arány (<span class="math inline">\(11.1-14.68=-3.58\)</span>). De <strong>nem vehetjük automatikusan igaznak <span class="math inline">\(H_1\)</span>-et, hiszen ez a jelenség lehet csak a mintavételi hiba műve!</strong> Épp <strong>azért kell p-értéket számolni, hogy megtudjuk, mekkora valószínűséggel lehet ez a jelenség</strong> (hogy a <em>Hisz</em> csoport esetén ennyivel alacsonyabb a parlamentben bízók aránya) <strong>csak a mintavételi hiba műve</strong>.</p>
<p>A próbafüggvényünk formulája alább látható, és azt is megfigyelhetjük az következő képletből, hogy a nevezetes eloszlásunk a p-érték számításához standard normális (<span class="math inline">\(N(0,1)\)</span>): <span class="math display">\[\frac{(p_1-p_2)-\epsilon_0}{\sqrt{\frac{p_1(1-p_1)}{n_1}+\frac{p_2(1-p_2)}{n_2}}} \sim N(0,1)\]</span></p>
<p>Láthatjuk, hogy a próbafüggvény képlete itt sem egy bonyolult konstrukció. Fogjuk a két mintaarány különbségét (<span class="math inline">\(p_1-p_2\)</span>) és megnézzük, hogy ez mennyire tér el az elvi különbségtől (<span class="math inline">\(\epsilon_0\)</span>) és ezt arányítjuk a kétféle átlaghoz tartozó standard hiba négyzetek összegéhez a gyök alatt. Viszont, van erre az <strong>arányos kétmintás z-próbára is beépített függvény</strong> a <code>statsmodels</code> csomagban, ami a próbafüggvényt és a p-értéket kiszámolja, így <strong>nem kell ezzel manuálisan szórakoznunk</strong> majd. :)<br>
Ugye ismét azért lesz <em>z-próba</em> a hipotézisvizsgálatunk neve, mert a pórbafüggvényből standard normális, azaz <span class="math inline">\(z\)</span> eloszláson keresztül lesz p-értékünk.</p>
<p>Viszont, azt <strong>mindenképpen látnunk kell, hogy mivel a p-érték számításhoz vett eloszlás standard normális</strong> (<span class="math inline">\(N(0,1)\)</span>), így <strong>mindkét mintának nagynak kell lennie</strong>! Ez itt <strong>kétmintás arányra vonatkozó hipotézisvizsgálat esetén</strong> azt jelenti, hogy <strong>mindkét mintában legyen legalább <span class="math inline">\(10\)</span> db arány szempontjából kedvező és kedvezőtlen eset is</strong>.</p>
<p>Ezt a korábban kiszámolt <span class="math inline">\(k_1\)</span>, <span class="math inline">\(k_2\)</span> és <span class="math inline">\(n_1\)</span>, <span class="math inline">\(n_2\)</span> értékekből már könnyen tudjuk ellenőrizni.</p>
<p>Nézzük az arány szempontjából kedvező eseteket.</p>
<div class="sourceCode" id="cb872"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb872-1"><a href="egymintás-és-kétmintás-próbák.html#cb872-1" tabindex="-1"></a>k_1 <span class="op">&gt;</span> <span class="dv">10</span></span></code></pre></div>
<pre><code>## True</code></pre>
<div class="sourceCode" id="cb874"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb874-1"><a href="egymintás-és-kétmintás-próbák.html#cb874-1" tabindex="-1"></a>k_2 <span class="op">&gt;</span> <span class="dv">10</span></span></code></pre></div>
<pre><code>## True</code></pre>
<p>Mindkét mintára igaz a feltétel, rendben vagyunk.</p>
<p>S most az arány szempontjából kedvezőtlen esetek jönnek. Nyilván itt az az alapelv, hogy ami a mintában <em>nem</em> arány szempontjából kedvező eset, az mind kedvezőtlennek minősül.</p>
<div class="sourceCode" id="cb876"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb876-1"><a href="egymintás-és-kétmintás-próbák.html#cb876-1" tabindex="-1"></a>n_1 <span class="op">-</span> k_1 <span class="op">&gt;</span> <span class="dv">10</span></span></code></pre></div>
<pre><code>## True</code></pre>
<div class="sourceCode" id="cb878"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb878-1"><a href="egymintás-és-kétmintás-próbák.html#cb878-1" tabindex="-1"></a>n_2 <span class="op">-</span> k_2 <span class="op">&gt;</span> <span class="dv">10</span></span></code></pre></div>
<pre><code>## True</code></pre>
<p>Itt is mindkét mintára igaz a feltétel, rendben vagyunk. Juhé! :)</p>
<p>Lássuk hát a <strong>p-érték számolás</strong>át a <code>test_proportions_2indep</code> beépített függvénnyel a <code>statsmodels</code> csomagból.<br>
A <strong>függvényben a következő paraméterek</strong>et kell megadni:</p>
<ul>
<li><code>count1</code>, <code>count2</code> + <code>nobs1</code>, <code>nobs2</code>: A két minta arány szempontjából kedvező eseteinek száma (<code>count1</code>, <code>count2</code>) és a két minta teljes elemszámai (<code>nobs1</code>, <code>nobs2</code>).
<ul>
<li>Arra kell figyelni, hogy a függvényben a kivonás iránya <code>1 - 2</code>. Tehát, a két csoport átadásának sorrendje következetes kell legyen a <span class="math inline">\(H_0\)</span> és <span class="math inline">\(H_1\)</span>-ben alkalmazott kivonások irányával. Nekünk ez most azt jelenti, hogy elsőnek a <em>Hisz</em> csoport esetszámait adjuk át (a <code>count1</code> és <code>nobs1</code> paramétereken), mert a hipotéziseinkben <span class="math inline">\(P_{Hisz} - P_{NemHisz}\)</span> kivonás szerepel.</li>
</ul></li>
<li><code>value</code>: Az arányok közti elvi eltérés értéke a hipotéziseinkben. Ez most nekünk <span class="math inline">\(\epsilon_0=-0.02\)</span>.</li>
<li><code>alternative</code>: Az alteranítv hipotézisben lévő relációs jelet adjuk meg szövegesen.
<ul>
<li>lehetséges értékek: <code>‘two-sided’, ‘smaller’, ‘larger’</code>, rendre a <span class="math inline">\(\neq\)</span>, <span class="math inline">\(&lt;\)</span>, <span class="math inline">\(&gt;\)</span> relációs jeleket jelölik <span class="math inline">\(H_1\)</span>-ben</li>
</ul></li>
</ul>
<p>Ezzel a működés a következőképpen néz ki.</p>
<div class="sourceCode" id="cb880"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb880-1"><a href="egymintás-és-kétmintás-próbák.html#cb880-1" tabindex="-1"></a><span class="co"># függvény importja</span></span>
<span id="cb880-2"><a href="egymintás-és-kétmintás-próbák.html#cb880-2" tabindex="-1"></a><span class="im">from</span> statsmodels.stats.proportion <span class="im">import</span> test_proportions_2indep</span>
<span id="cb880-3"><a href="egymintás-és-kétmintás-próbák.html#cb880-3" tabindex="-1"></a></span>
<span id="cb880-4"><a href="egymintás-és-kétmintás-próbák.html#cb880-4" tabindex="-1"></a>test_proportions_2indep(count1 <span class="op">=</span> k_1, nobs1<span class="op">=</span>n_1,</span>
<span id="cb880-5"><a href="egymintás-és-kétmintás-próbák.html#cb880-5" tabindex="-1"></a>                        count2<span class="op">=</span>k_2, nobs2<span class="op">=</span>n_2,</span>
<span id="cb880-6"><a href="egymintás-és-kétmintás-próbák.html#cb880-6" tabindex="-1"></a>                        value <span class="op">=</span> <span class="op">-</span><span class="fl">0.02</span>, alternative<span class="op">=</span><span class="st">&#39;smaller&#39;</span>)</span></code></pre></div>
<pre><code>## &lt;class &#39;statsmodels.stats.base.HolderTuple&#39;&gt;
## statistic = -0.8767111411557769
## pvalue = 0.19032177690414032
## compare = &#39;diff&#39;
## method = &#39;agresti-caffo&#39;
## diff = -0.035496277428367834
## ratio = 0.7582164558413269
## odds_ratio = 0.7279314533902407
## variance = 0.0002782775559788205
## alternative = &#39;smaller&#39;
## value = -0.02
## tuple = (-0.8767111411557769, 0.19032177690414032)</code></pre>
<p>Szépen látszik, hogy a próbafüggvény (az outoutban <code>statistics</code>) <span class="math inline">\(-0.8767\)</span>, de ami fontosabb, hogy a p-értékünk <span class="math inline">\(19\%\)</span>-ra jön ki. Tehát <strong>a <span class="math inline">\(H_0\)</span>-t elutastíani <span class="math inline">\(19\%\)</span>-os valószínűséggel eredményez hibát</strong>. Ez <strong>magasabb, mint a legnagyobb megengedett szokásos szignifikancia-szint</strong>, az <span class="math inline">\(\alpha=10\%\)</span>, így a <span class="math inline">\(H_0\)</span>-t nem utasítom el. Mivel nagyobb hibával járna a <span class="math inline">\(H_0\)</span> eluatsítása, mínt a mengedett hiba. Tehát, <strong>végső soron a két arány közti különbség a népességben kisebbnek vehető, mint 2%-pont</strong>.<br>
Azaz, <strong>a mintaarányok között tapasztalt, 2 %-pontnál nagyobb eltérés NEM szignifikáns</strong> a megfigyelt mintánk alapján!</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="hipotézisvizsgálat-alapjai.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="nemparaméteres-próbák.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "night",
"family": "sans",
"size": 1
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/09-Tobbmintas.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
