<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>13 Többváltozós OLS Regresszió alapjai | Következtető Statisztika Python Jegyzet</title>
  <meta name="description" content="<p>Lecture notes on BSc level Inferential Statistics in bookdown format.
Mainly for Business Information Systems BSc students at Corvinus University of Budapest.</p>" />
  <meta name="generator" content="bookdown 0.43 and GitBook 2.6.7" />

  <meta property="og:title" content="13 Többváltozós OLS Regresszió alapjai | Következtető Statisztika Python Jegyzet" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="<p>Lecture notes on BSc level Inferential Statistics in bookdown format.
Mainly for Business Information Systems BSc students at Corvinus University of Budapest.</p>" />
  <meta name="github-repo" content="KoLa992/Kovetkezteto-Statisztika-Python-Jegyzet" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="13 Többváltozós OLS Regresszió alapjai | Következtető Statisztika Python Jegyzet" />
  
  <meta name="twitter:description" content="<p>Lecture notes on BSc level Inferential Statistics in bookdown format.
Mainly for Business Information Systems BSc students at Corvinus University of Budapest.</p>" />
  

<meta name="author" content="Kovács László" />


<meta name="date" content="2025-06-30" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="kétváltozós-lineáris-regresszió.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Következtető Statisztika Python Jegyzet</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Előhang</a></li>
<li class="chapter" data-level="2" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html"><i class="fa fa-check"></i><b>2</b> Statisztikához szükséges Python nyelvi alapok</a>
<ul>
<li class="chapter" data-level="2.1" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#programozási-alapelvek"><i class="fa fa-check"></i><b>2.1</b> Programozási alapelvek</a></li>
<li class="chapter" data-level="2.2" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#a-pythonról-általában"><i class="fa fa-check"></i><b>2.2</b> A Pythonról általában</a></li>
<li class="chapter" data-level="2.3" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#a-spyder-felülete"><i class="fa fa-check"></i><b>2.3</b> A Spyder felülete</a></li>
<li class="chapter" data-level="2.4" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#working-directory"><i class="fa fa-check"></i><b>2.4</b> Working Directory</a></li>
<li class="chapter" data-level="2.5" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#alapvető-python-adattípusok-és-adatszerkezetek"><i class="fa fa-check"></i><b>2.5</b> Alapvető Python adattípusok és adatszerkezetek</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#egyszerű-adattípusok"><i class="fa fa-check"></i><b>2.5.1</b> Egyszerű adattípusok</a></li>
<li class="chapter" data-level="2.5.2" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#összetett-adatszerkezetek"><i class="fa fa-check"></i><b>2.5.2</b> Összetett adatszerkezetek</a></li>
<li class="chapter" data-level="2.5.3" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#a-numpy-tömb"><i class="fa fa-check"></i><b>2.5.3</b> A <code>numpy</code> tömb</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#vezérlési-szerkezetek"><i class="fa fa-check"></i><b>2.6</b> Vezérlési szerkezetek</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#elágazás-if"><i class="fa fa-check"></i><b>2.6.1</b> Elágazás (<code>if</code>)</a></li>
<li class="chapter" data-level="2.6.2" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#ciklusok-for"><i class="fa fa-check"></i><b>2.6.2</b> Ciklusok (<code>for</code>)</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#a-pandas-data-frame-objektum"><i class="fa fa-check"></i><b>2.7</b> A Pandas data frame objektum</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#hivatkozási-lehetőségek-data-frame-ben"><i class="fa fa-check"></i><b>2.7.1</b> Hivatkozási lehetőségek data frame-ben</a></li>
<li class="chapter" data-level="2.7.2" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#data-frame-k-módosítása"><i class="fa fa-check"></i><b>2.7.2</b> Data frame-k módosítása</a></li>
<li class="chapter" data-level="2.7.3" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#szűrés-data-frame-ben-logikai-indexszálás"><i class="fa fa-check"></i><b>2.7.3</b> Szűrés data frame-ben: logikai indexszálás</a></li>
<li class="chapter" data-level="2.7.4" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#hiányzó-értékek-kezelése-data-frame-ben"><i class="fa fa-check"></i><b>2.7.4</b> Hiányzó értékek kezelése data frame-ben</a></li>
<li class="chapter" data-level="2.7.5" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#adatvizualizáció-data-frame-en-keresztül"><i class="fa fa-check"></i><b>2.7.5</b> Adatvizualizáció data frame-en keresztül</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#aggregálás-data-frame-ben"><i class="fa fa-check"></i><b>2.8</b> Aggregálás data frame-ben</a></li>
<li class="chapter" data-level="2.9" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#egyszerű-leíró-statisztika-data-frame-ben"><i class="fa fa-check"></i><b>2.9</b> Egyszerű leíró statisztika data frame-ben</a></li>
<li class="chapter" data-level="2.10" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#adatminőségi-problémák-felismerése-és-kezelése-leíró-statisztika-segítségével"><i class="fa fa-check"></i><b>2.10</b> Adatminőségi problémák felismerése és kezelése leíró statisztika segítségével</a></li>
<li class="chapter" data-level="2.11" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#data-frame-k-összekapcsolása"><i class="fa fa-check"></i><b>2.11</b> Data frame-k összekapcsolása</a>
<ul>
<li class="chapter" data-level="2.11.1" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#a-kapcsolási-kulcsnak-használt-oszlop-ellenőrzése-és-javítása"><i class="fa fa-check"></i><b>2.11.1</b> A kapcsolási kulcsnak használt oszlop ellenőrzése és javítása</a></li>
</ul></li>
<li class="chapter" data-level="2.12" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#kilógó-értékek-keresése-és-kezelése"><i class="fa fa-check"></i><b>2.12</b> Kilógó értékek keresése és kezelése</a></li>
<li class="chapter" data-level="2.13" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#korrelációs-elemzések-data-frame-ben"><i class="fa fa-check"></i><b>2.13</b> Korrelációs elemzések data frame-ben</a></li>
<li class="chapter" data-level="" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#gyakorló-feladatok"><i class="fa fa-check"></i>Gyakorló feladatok</a></li>
<li class="chapter" data-level="" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#gyakorló-feladatok-megoldása"><i class="fa fa-check"></i>Gyakorló feladatok megoldása</a>
<ul>
<li class="chapter" data-level="" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#feladat"><i class="fa fa-check"></i>1. feladat</a></li>
<li class="chapter" data-level="" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#feladat-1"><i class="fa fa-check"></i>2. feladat</a></li>
<li class="chapter" data-level="" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#feladat-2"><i class="fa fa-check"></i>3. feladat</a></li>
<li class="chapter" data-level="" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#feladat-3"><i class="fa fa-check"></i>4. feladat</a></li>
<li class="chapter" data-level="" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#feladat-4"><i class="fa fa-check"></i>5. feladat</a></li>
<li class="chapter" data-level="" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#feladat-5"><i class="fa fa-check"></i>6. feladat</a></li>
<li class="chapter" data-level="" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#feladat-6"><i class="fa fa-check"></i>7. feladat</a></li>
<li class="chapter" data-level="" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#feladat-7"><i class="fa fa-check"></i>8. feladat</a></li>
<li class="chapter" data-level="" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#feladat-8"><i class="fa fa-check"></i>9. feladat</a></li>
<li class="chapter" data-level="" data-path="statisztikához-szükséges-python-nyelvi-alapok.html"><a href="statisztikához-szükséges-python-nyelvi-alapok.html#feladat-9"><i class="fa fa-check"></i>10. feladat</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html"><a href="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html"><i class="fa fa-check"></i><b>3</b> Leíró Statisztika ismétlés és Valószínűségszámítás alapok</a>
<ul>
<li class="chapter" data-level="3.1" data-path="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html"><a href="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html#leíró-statisztikai-mutatók"><i class="fa fa-check"></i><b>3.1</b> Leíró statisztikai mutatók</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html"><a href="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html#hisztogram-és-alakmutatók"><i class="fa fa-check"></i><b>3.1.1</b> Hisztogram és Alakmutatók</a></li>
<li class="chapter" data-level="3.1.2" data-path="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html"><a href="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html#gyakorisági-tábla-lekérése"><i class="fa fa-check"></i><b>3.1.2</b> Gyakorisági tábla lekérése</a></li>
<li class="chapter" data-level="3.1.3" data-path="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html"><a href="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html#gyakorisági-tábla-bővítése"><i class="fa fa-check"></i><b>3.1.3</b> Gyakorisági tábla bővítése</a></li>
<li class="chapter" data-level="3.1.4" data-path="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html"><a href="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html#súlyozott-átlag-és-szórás-pythonban"><i class="fa fa-check"></i><b>3.1.4</b> Súlyozott átlag és szórás Pythonban</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html"><a href="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html#a-normális-eloszlás-és-sűrűségfüggvénye"><i class="fa fa-check"></i><b>3.2</b> A normális eloszlás és sűrűségfüggvénye</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html"><a href="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html#a-sűrűségfüggvény-használata"><i class="fa fa-check"></i><b>3.2.1</b> A sűrűségfüggvény használata</a></li>
<li class="chapter" data-level="3.2.2" data-path="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html"><a href="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html#a-sűrűségfüggvény-integrálja"><i class="fa fa-check"></i><b>3.2.2</b> A sűrűségfüggvény integrálja</a></li>
<li class="chapter" data-level="3.2.3" data-path="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html"><a href="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html#valószínűség-vs-relatív-gyakoriság"><i class="fa fa-check"></i><b>3.2.3</b> Valószínűség vs Relatív Gyakoriság</a></li>
<li class="chapter" data-level="3.2.4" data-path="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html"><a href="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html#centrális-határeloszlás-tétel-cht"><i class="fa fa-check"></i><b>3.2.4</b> Centrális Határeloszlás Tétel (CHT)</a></li>
<li class="chapter" data-level="3.2.5" data-path="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html"><a href="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html#inverz-értékek"><i class="fa fa-check"></i><b>3.2.5</b> Inverz Értékek</a></li>
<li class="chapter" data-level="3.2.6" data-path="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html"><a href="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html#a-standard-normális-eloszlás"><i class="fa fa-check"></i><b>3.2.6</b> A Standard Normális Eloszlás</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html"><a href="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html#az-exponenciális-eloszlás"><i class="fa fa-check"></i><b>3.3</b> Az Exponenciális eloszlás</a></li>
<li class="chapter" data-level="3.4" data-path="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html"><a href="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html#a-varianciahányados-pythonban---kokain-a-balatonban"><i class="fa fa-check"></i><b>3.4</b> A Varianciahányados Pythonban - Kokain a Balatonban</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html"><a href="leíró-statisztika-ismétlés-és-valószínűségszámítás-alapok.html#további-minőségi-ismérvek-és-a-kokainmennyiség"><i class="fa fa-check"></i><b>3.4.1</b> További minőségi ismérvek és a kokainmennyiség</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="eloszlások-és-mintavételezés.html"><a href="eloszlások-és-mintavételezés.html"><i class="fa fa-check"></i><b>4</b> Eloszlások és Mintavételezés</a>
<ul>
<li class="chapter" data-level="4.1" data-path="eloszlások-és-mintavételezés.html"><a href="eloszlások-és-mintavételezés.html#véletlenszám-generálás-és-mintavételezés"><i class="fa fa-check"></i><b>4.1</b> Véletlenszám generálás és Mintavételezés</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="eloszlások-és-mintavételezés.html"><a href="eloszlások-és-mintavételezés.html#a-mintagenerálás-általános-elve"><i class="fa fa-check"></i><b>4.1.1</b> A mintagenerálás általános elve</a></li>
<li class="chapter" data-level="4.1.2" data-path="eloszlások-és-mintavételezés.html"><a href="eloszlások-és-mintavételezés.html#nem-egyenletes-eloszlású-minták-generálása"><i class="fa fa-check"></i><b>4.1.2</b> Nem egyenletes eloszlású minták generálása</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="eloszlások-és-mintavételezés.html"><a href="eloszlások-és-mintavételezés.html#elvi-eloszlás-vs-megfigyelt-minta"><i class="fa fa-check"></i><b>4.2</b> Elvi Eloszlás vs Megfigyelt Minta</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="eloszlások-és-mintavételezés.html"><a href="eloszlások-és-mintavételezés.html#az-elvi-eloszlás-alapján-számolt-statisztikai-mutatók"><i class="fa fa-check"></i><b>4.2.1</b> Az elvi eloszlás alapján számolt statisztikai mutatók</a></li>
<li class="chapter" data-level="4.2.2" data-path="eloszlások-és-mintavételezés.html"><a href="eloszlások-és-mintavételezés.html#a-megfigyelt-minta-alapján-számolt-statisztikai-mutatók"><i class="fa fa-check"></i><b>4.2.2</b> A megfigyelt minta alapján számolt statisztikai mutatók</a></li>
<li class="chapter" data-level="4.2.3" data-path="eloszlások-és-mintavételezés.html"><a href="eloszlások-és-mintavételezés.html#a-mintavételi-hiba-mvh-koncepciója"><i class="fa fa-check"></i><b>4.2.3</b> A mintavételi hiba (MVH) koncepciója</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="eloszlások-és-mintavételezés.html"><a href="eloszlások-és-mintavételezés.html#statisztikai-sokaságok-fae-mintavételezése"><i class="fa fa-check"></i><b>4.3</b> Statisztikai sokaságok FAE mintavételezése</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="eloszlások-és-mintavételezés.html"><a href="eloszlások-és-mintavételezés.html#ismételt-mintavételezés-resampling"><i class="fa fa-check"></i><b>4.3.1</b> Ismételt Mintavételezés (<em>Resampling</em>)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="a-becsléselmélet-alapjai.html"><a href="a-becsléselmélet-alapjai.html"><i class="fa fa-check"></i><b>5</b> A becsléselmélet alapjai</a>
<ul>
<li class="chapter" data-level="5.1" data-path="a-becsléselmélet-alapjai.html"><a href="a-becsléselmélet-alapjai.html#ismétlés-balaton-átúszás-eredmények-és-ezek-fae-mintái"><i class="fa fa-check"></i><b>5.1</b> Ismétlés: Balaton átúszás eredmények és ezek FAE mintái</a></li>
<li class="chapter" data-level="5.2" data-path="a-becsléselmélet-alapjai.html"><a href="a-becsléselmélet-alapjai.html#a-torzítatlanság-fogalma"><i class="fa fa-check"></i><b>5.2</b> A torzítatlanság fogalma</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="a-becsléselmélet-alapjai.html"><a href="a-becsléselmélet-alapjai.html#az-aszimptotikus-torzítatlanság-fogalma"><i class="fa fa-check"></i><b>5.2.1</b> Az aszimptotikus torzítatlanság fogalma</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="a-becsléselmélet-alapjai.html"><a href="a-becsléselmélet-alapjai.html#a-korrigált-mintavariancia"><i class="fa fa-check"></i><b>5.3</b> A korrigált mintavariancia</a></li>
<li class="chapter" data-level="5.4" data-path="a-becsléselmélet-alapjai.html"><a href="a-becsléselmélet-alapjai.html#a-medián-torzítatlansága"><i class="fa fa-check"></i><b>5.4</b> A medián torzítatlansága</a></li>
<li class="chapter" data-level="5.5" data-path="a-becsléselmélet-alapjai.html"><a href="a-becsléselmélet-alapjai.html#a-standard-hiba-sh-fogalma"><i class="fa fa-check"></i><b>5.5</b> A Standard Hiba (<em>SH</em>) fogalma</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="a-becsléselmélet-alapjai.html"><a href="a-becsléselmélet-alapjai.html#a-konzisztens-becslés-fogalma"><i class="fa fa-check"></i><b>5.5.1</b> A konzisztens becslés fogalma</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="a-becsléselmélet-alapjai.html"><a href="a-becsléselmélet-alapjai.html#az-átlagos-négyzetes-hiba-mse-fogalma"><i class="fa fa-check"></i><b>5.6</b> Az átlagos négyzetes hiba (<em>MSE</em>) fogalma</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="a-becsléselmélet-alapjai.html"><a href="a-becsléselmélet-alapjai.html#különböző-becslőfüggvények-összehasonlítása"><i class="fa fa-check"></i><b>5.6.1</b> Különböző becslőfüggvények összehasonlítása</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="a-sokasági-átlag-intervallumbecslése.html"><a href="a-sokasági-átlag-intervallumbecslése.html"><i class="fa fa-check"></i><b>6</b> A sokasági átlag intervallumbecslése</a>
<ul>
<li class="chapter" data-level="6.1" data-path="a-sokasági-átlag-intervallumbecslése.html"><a href="a-sokasági-átlag-intervallumbecslése.html#ismétlés-az-átlag-standard-hibája-a-balaton-átúszás-eredményeken"><i class="fa fa-check"></i><b>6.1</b> Ismétlés: Az átlag standard hibája a Balaton átúszás eredményeken</a></li>
<li class="chapter" data-level="6.2" data-path="a-sokasági-átlag-intervallumbecslése.html"><a href="a-sokasági-átlag-intervallumbecslése.html#a-mintaátlagok-eloszlása"><i class="fa fa-check"></i><b>6.2</b> A mintaátlagok eloszlása</a></li>
<li class="chapter" data-level="6.3" data-path="a-sokasági-átlag-intervallumbecslése.html"><a href="a-sokasági-átlag-intervallumbecslése.html#a-sokasági-átlag-konfidencia-intervalluma"><i class="fa fa-check"></i><b>6.3</b> A sokasági átlag konfidencia-intervalluma</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="a-sokasági-átlag-intervallumbecslése.html"><a href="a-sokasági-átlag-intervallumbecslése.html#az-átlag-konfidencia-intervallumának-általános-alakja"><i class="fa fa-check"></i><b>6.3.1</b> Az átlag konfidencia-intervallumának általános alakja</a></li>
<li class="chapter" data-level="6.3.2" data-path="a-sokasági-átlag-intervallumbecslése.html"><a href="a-sokasági-átlag-intervallumbecslése.html#a-konfidencia-intervallum-megbízhatóságának-ellenőrzése"><i class="fa fa-check"></i><b>6.3.2</b> A konfidencia-intervallum megbízhatóságának ellenőrzése</a></li>
<li class="chapter" data-level="6.3.3" data-path="a-sokasági-átlag-intervallumbecslése.html"><a href="a-sokasági-átlag-intervallumbecslése.html#a-konfidencia-intervallum-két-fontos-tulajdonsága"><i class="fa fa-check"></i><b>6.3.3</b> 3.3. A konfidencia-intervallum két fontos tulajdonsága</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="a-sokasági-átlag-intervallumbecslése.html"><a href="a-sokasági-átlag-intervallumbecslése.html#intervallumbecslés-a-gyakorlatban"><i class="fa fa-check"></i><b>6.4</b> Intervallumbecslés a gyakorlatban</a>
<ul>
<li class="chapter" data-level="" data-path="a-sokasági-átlag-intervallumbecslése.html"><a href="a-sokasági-átlag-intervallumbecslése.html#feladat-altatók-hatékonysága"><i class="fa fa-check"></i>1. feladat: Altatók hatékonysága</a></li>
<li class="chapter" data-level="" data-path="a-sokasági-átlag-intervallumbecslése.html"><a href="a-sokasági-átlag-intervallumbecslése.html#a-feladat-megoldás"><i class="fa fa-check"></i>1/a) feladat megoldás</a></li>
<li class="chapter" data-level="" data-path="a-sokasági-átlag-intervallumbecslése.html"><a href="a-sokasági-átlag-intervallumbecslése.html#b-feladat-megoldás"><i class="fa fa-check"></i>1/b) feladat megoldás</a></li>
<li class="chapter" data-level="" data-path="a-sokasági-átlag-intervallumbecslése.html"><a href="a-sokasági-átlag-intervallumbecslése.html#c-feladat-megoldás"><i class="fa fa-check"></i>1/c) feladat megoldás</a></li>
<li class="chapter" data-level="" data-path="a-sokasági-átlag-intervallumbecslése.html"><a href="a-sokasági-átlag-intervallumbecslése.html#feladat-10"><i class="fa fa-check"></i>2. feladat</a></li>
<li class="chapter" data-level="" data-path="a-sokasági-átlag-intervallumbecslése.html"><a href="a-sokasági-átlag-intervallumbecslése.html#feladat-megoldás"><i class="fa fa-check"></i>2. feladat megoldás</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="a-sokasági-átlag-intervallumbecslése.html"><a href="a-sokasági-átlag-intervallumbecslése.html#összefoglalás-az-átlag-konfidencia-intervallumairól"><i class="fa fa-check"></i><b>6.5</b> Összefoglalás az átlag konfidencia-intervallumairól</a></li>
<li class="chapter" data-level="6.6" data-path="a-sokasági-átlag-intervallumbecslése.html"><a href="a-sokasági-átlag-intervallumbecslése.html#esettanulmány"><i class="fa fa-check"></i><b>6.6</b> Esettanulmány</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="további-fae-becslések-és-a-bootstrap-módszer.html"><a href="további-fae-becslések-és-a-bootstrap-módszer.html"><i class="fa fa-check"></i><b>7</b> További FAE becslések és a Bootstrap módszer</a>
<ul>
<li class="chapter" data-level="7.1" data-path="további-fae-becslések-és-a-bootstrap-módszer.html"><a href="további-fae-becslések-és-a-bootstrap-módszer.html#a-konfidencia-intervallumok-két-általános-tulajdonsága"><i class="fa fa-check"></i><b>7.1</b> A Konfidencia-intervallumok két általános tulajdonsága</a></li>
<li class="chapter" data-level="7.2" data-path="további-fae-becslések-és-a-bootstrap-módszer.html"><a href="további-fae-becslések-és-a-bootstrap-módszer.html#arányok-konfidencia-intervalluma"><i class="fa fa-check"></i><b>7.2</b> Arányok konfidencia-intervalluma</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="további-fae-becslések-és-a-bootstrap-módszer.html"><a href="további-fae-becslések-és-a-bootstrap-módszer.html#mintaelemszám-meghatározása-aránybecsléshez"><i class="fa fa-check"></i><b>7.2.1</b> Mintaelemszám meghatározása aránybecsléshez</a></li>
<li class="chapter" data-level="7.2.2" data-path="további-fae-becslések-és-a-bootstrap-módszer.html"><a href="további-fae-becslések-és-a-bootstrap-módszer.html#szükséges-minimális-elemszám-aránybecsléshez"><i class="fa fa-check"></i><b>7.2.2</b> Szükséges minimális elemszám aránybecsléshez</a></li>
<li class="chapter" data-level="7.2.3" data-path="további-fae-becslések-és-a-bootstrap-módszer.html"><a href="további-fae-becslések-és-a-bootstrap-módszer.html#aránybecslés-a-statsmodels-csomaggal"><i class="fa fa-check"></i><b>7.2.3</b> Aránybecslés a <code>statsmodels</code> csomaggal</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="további-fae-becslések-és-a-bootstrap-módszer.html"><a href="további-fae-becslések-és-a-bootstrap-módszer.html#a-bootstrap-becslések-általános-elve"><i class="fa fa-check"></i><b>7.3</b> A Bootstrap becslések általános elve</a></li>
<li class="chapter" data-level="7.4" data-path="további-fae-becslések-és-a-bootstrap-módszer.html"><a href="további-fae-becslések-és-a-bootstrap-módszer.html#a-medián-bootstrap-intervallumbecslése"><i class="fa fa-check"></i><b>7.4</b> A Medián Bootstrap intervallumbecslése</a></li>
<li class="chapter" data-level="7.5" data-path="további-fae-becslések-és-a-bootstrap-módszer.html"><a href="további-fae-becslések-és-a-bootstrap-módszer.html#a-szórás-bootstrap-intervallumbecslése"><i class="fa fa-check"></i><b>7.5</b> A Szórás Bootstrap intervallumbecslése</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="becslések-ev-és-r-mintából.html"><a href="becslések-ev-és-r-mintából.html"><i class="fa fa-check"></i><b>8</b> Becslések EV és R mintából</a>
<ul>
<li class="chapter" data-level="8.1" data-path="becslések-ev-és-r-mintából.html"><a href="becslések-ev-és-r-mintából.html#intervallumbecslés-visszatevés-nélküli-egyszerű-véletlen-ev-mintákból"><i class="fa fa-check"></i><b>8.1</b> Intervallumbecslés visszatevés nélküli egyszerű véletlen (EV) mintákból</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="becslések-ev-és-r-mintából.html"><a href="becslések-ev-és-r-mintából.html#átlag-becslése-ev-mintákból"><i class="fa fa-check"></i><b>8.1.1</b> Átlag becslése EV mintákból</a></li>
<li class="chapter" data-level="8.1.2" data-path="becslések-ev-és-r-mintából.html"><a href="becslések-ev-és-r-mintából.html#arány-becslése-ev-mintákból"><i class="fa fa-check"></i><b>8.1.2</b> Arány becslése EV mintákból</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="becslések-ev-és-r-mintából.html"><a href="becslések-ev-és-r-mintából.html#átlag-becslése-arányosan-rétegzett-ar-mintákból"><i class="fa fa-check"></i><b>8.2</b> Átlag becslése Arányosan Rétegzett (AR) mintákból</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="becslések-ev-és-r-mintából.html"><a href="becslések-ev-és-r-mintából.html#az-ar-mintavételek-hatékonysága"><i class="fa fa-check"></i><b>8.2.1</b> Az AR mintavételek hatékonysága</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="hipotézisvizsgálat-alapjai.html"><a href="hipotézisvizsgálat-alapjai.html"><i class="fa fa-check"></i><b>9</b> Hipotézisvizsgálat alapjai</a>
<ul>
<li class="chapter" data-level="9.1" data-path="hipotézisvizsgálat-alapjai.html"><a href="hipotézisvizsgálat-alapjai.html#a-hipotézisvizsgálat-alapgondolata"><i class="fa fa-check"></i><b>9.1</b> A hipotézisvizsgálat alapgondolata</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="hipotézisvizsgálat-alapjai.html"><a href="hipotézisvizsgálat-alapjai.html#a-p-érték-fogalma"><i class="fa fa-check"></i><b>9.1.1</b> A p-érték fogalma</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="hipotézisvizsgálat-alapjai.html"><a href="hipotézisvizsgálat-alapjai.html#a-sokasági-átlagra-vonatkozó-t-próba"><i class="fa fa-check"></i><b>9.2</b> A sokasági átlagra vonatkozó <em>t-próba</em></a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="hipotézisvizsgálat-alapjai.html"><a href="hipotézisvizsgálat-alapjai.html#a-t-próba-beépített-függvénnyel"><i class="fa fa-check"></i><b>9.2.1</b> A <em>t-próba</em> beépített függvénnyel</a></li>
<li class="chapter" data-level="9.2.2" data-path="hipotézisvizsgálat-alapjai.html"><a href="hipotézisvizsgálat-alapjai.html#a-t-próba-előfeltételei"><i class="fa fa-check"></i><b>9.2.2</b> A <em>t-próba</em> előfeltételei</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="hipotézisvizsgálat-alapjai.html"><a href="hipotézisvizsgálat-alapjai.html#a-sokasági-átlagra-vonatkozó-z-próba"><i class="fa fa-check"></i><b>9.3</b> A sokasági átlagra vonatkozó <em>z-próba</em></a></li>
<li class="chapter" data-level="9.4" data-path="hipotézisvizsgálat-alapjai.html"><a href="hipotézisvizsgálat-alapjai.html#a-sokasági-arányra-vonatkozó-z-próba"><i class="fa fa-check"></i><b>9.4</b> A sokasági arányra vonatkozó <em>z-próba</em></a></li>
<li class="chapter" data-level="9.5" data-path="hipotézisvizsgálat-alapjai.html"><a href="hipotézisvizsgálat-alapjai.html#a-hipotézisvizsgálat-menete-madártávlatból"><i class="fa fa-check"></i><b>9.5</b> A hipotézisvizsgálat menete madártávlatból</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="egymintás-és-kétmintás-próbák.html"><a href="egymintás-és-kétmintás-próbák.html"><i class="fa fa-check"></i><b>10</b> Egymintás és Kétmintás próbák</a>
<ul>
<li class="chapter" data-level="10.1" data-path="egymintás-és-kétmintás-próbák.html"><a href="egymintás-és-kétmintás-próbák.html#a-szórásra-vonatkozó-chi2-próba"><i class="fa fa-check"></i><b>10.1</b> A szórásra vonatkozó <span class="math inline">\(\chi^2\)</span>-próba</a></li>
<li class="chapter" data-level="10.2" data-path="egymintás-és-kétmintás-próbák.html"><a href="egymintás-és-kétmintás-próbák.html#a-kétmintás-hipotézisvizsgálatok-elve"><i class="fa fa-check"></i><b>10.2</b> A kétmintás hipotézisvizsgálatok elve</a></li>
<li class="chapter" data-level="10.3" data-path="egymintás-és-kétmintás-próbák.html"><a href="egymintás-és-kétmintás-próbák.html#az-átlagokra-vonatkozó-kétmintás-z-próba"><i class="fa fa-check"></i><b>10.3</b> Az átlagokra vonatkozó kétmintás <em>z-próba</em></a></li>
<li class="chapter" data-level="10.4" data-path="egymintás-és-kétmintás-próbák.html"><a href="egymintás-és-kétmintás-próbák.html#az-arányokra-vonatkozó-kétmintás-z-próba"><i class="fa fa-check"></i><b>10.4</b> Az arányokra vonatkozó kétmintás <em>z-próba</em></a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="nemparaméteres-próbák.html"><a href="nemparaméteres-próbák.html"><i class="fa fa-check"></i><b>11</b> Nemparaméteres próbák</a>
<ul>
<li class="chapter" data-level="11.1" data-path="nemparaméteres-próbák.html"><a href="nemparaméteres-próbák.html#nemparaméteres-próbák-elve"><i class="fa fa-check"></i><b>11.1</b> Nemparaméteres próbák elve</a></li>
<li class="chapter" data-level="11.2" data-path="nemparaméteres-próbák.html"><a href="nemparaméteres-próbák.html#illeszkedésvizsgálatok"><i class="fa fa-check"></i><b>11.2</b> Illeszkedésvizsgálatok</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="nemparaméteres-próbák.html"><a href="nemparaméteres-próbák.html#reprezentativitás-vizsgálat"><i class="fa fa-check"></i><b>11.2.1</b> Reprezentativitás vizsgálat</a></li>
<li class="chapter" data-level="11.2.2" data-path="nemparaméteres-próbák.html"><a href="nemparaméteres-próbák.html#normalitás-vizsgálat"><i class="fa fa-check"></i><b>11.2.2</b> Normalitás vizsgálat</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="nemparaméteres-próbák.html"><a href="nemparaméteres-próbák.html#függetlenségvizsgálatok-homogenitásvizsgálatok"><i class="fa fa-check"></i><b>11.3</b> Függetlenségvizsgálatok (homogenitásvizsgálatok)</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="kétváltozós-lineáris-regresszió.html"><a href="kétváltozós-lineáris-regresszió.html"><i class="fa fa-check"></i><b>12</b> Kétváltozós lineáris regresszió</a>
<ul>
<li class="chapter" data-level="12.1" data-path="kétváltozós-lineáris-regresszió.html"><a href="kétváltozós-lineáris-regresszió.html#budapesti-lakások-vizsgálata"><i class="fa fa-check"></i><b>12.1</b> Budapesti lakások vizsgálata</a></li>
<li class="chapter" data-level="12.2" data-path="kétváltozós-lineáris-regresszió.html"><a href="kétváltozós-lineáris-regresszió.html#a-kétváltozós-lineáris-regresszió-ols-elvű-becslése"><i class="fa fa-check"></i><b>12.2</b> A Kétváltozós Lineáris Regresszió OLS elvű becslése</a></li>
<li class="chapter" data-level="12.3" data-path="kétváltozós-lineáris-regresszió.html"><a href="kétváltozós-lineáris-regresszió.html#az-ols-regresszió-magyarázóerejének-mérése"><i class="fa fa-check"></i><b>12.3</b> Az OLS Regresszió magyarázóerejének mérése</a></li>
<li class="chapter" data-level="12.4" data-path="kétváltozós-lineáris-regresszió.html"><a href="kétváltozós-lineáris-regresszió.html#a-regresszió-magyarázóereje-nem-megfigyelt-adatok-körében"><i class="fa fa-check"></i><b>12.4</b> A Regresszió magyarázóereje nem megfigyelt adatok körében</a></li>
<li class="chapter" data-level="12.5" data-path="kétváltozós-lineáris-regresszió.html"><a href="kétváltozós-lineáris-regresszió.html#a-modell-együtthatóinak-értelemzése"><i class="fa fa-check"></i><b>12.5</b> A modell együtthatóinak értelemzése</a></li>
<li class="chapter" data-level="12.6" data-path="kétváltozós-lineáris-regresszió.html"><a href="kétváltozós-lineáris-regresszió.html#egy-gyakorló-példa-covid-adatokon"><i class="fa fa-check"></i><b>12.6</b> Egy gyakorló példa COVID adatokon</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="többváltozós-ols-regresszió-alapjai.html"><a href="többváltozós-ols-regresszió-alapjai.html"><i class="fa fa-check"></i><b>13</b> Többváltozós OLS Regresszió alapjai</a>
<ul>
<li class="chapter" data-level="13.1" data-path="többváltozós-ols-regresszió-alapjai.html"><a href="többváltozós-ols-regresszió-alapjai.html#magyar-járások-covid-19-halálozási-arányai"><i class="fa fa-check"></i><b>13.1</b> Magyar járások COVID-19 halálozási arányai</a></li>
<li class="chapter" data-level="13.2" data-path="többváltozós-ols-regresszió-alapjai.html"><a href="többváltozós-ols-regresszió-alapjai.html#a-többváltozós-lineáris-regresszió-ols-elvű-előállítása"><i class="fa fa-check"></i><b>13.2</b> A Többváltozós Lineáris Regresszió OLS elvű előállítása</a></li>
<li class="chapter" data-level="13.3" data-path="többváltozós-ols-regresszió-alapjai.html"><a href="többváltozós-ols-regresszió-alapjai.html#a-magyarázóváltozók-marginális-hatása"><i class="fa fa-check"></i><b>13.3</b> A magyarázóváltozók marginális hatása</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="többváltozós-ols-regresszió-alapjai.html"><a href="többváltozós-ols-regresszió-alapjai.html#útelemzés"><i class="fa fa-check"></i><b>13.3.1</b> Útelemzés</a></li>
<li class="chapter" data-level="13.3.2" data-path="többváltozós-ols-regresszió-alapjai.html"><a href="többváltozós-ols-regresszió-alapjai.html#parciális-t-próba"><i class="fa fa-check"></i><b>13.3.2</b> Parciális t-próba</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="többváltozós-ols-regresszió-alapjai.html"><a href="többváltozós-ols-regresszió-alapjai.html#magyarázóváltozók-fontossági-sorrendjének-megállapítása-t-próba-alapján"><i class="fa fa-check"></i><b>13.4</b> Magyarázóváltozók fontossági sorrendjének megállapítása t-próba alapján</a></li>
<li class="chapter" data-level="13.5" data-path="többváltozós-ols-regresszió-alapjai.html"><a href="többváltozós-ols-regresszió-alapjai.html#konfidencia-intervallumok-és-a-t-próba-kapcsolata"><i class="fa fa-check"></i><b>13.5</b> 5. Konfidencia-intervallumok és a t-próba kapcsolata</a></li>
<li class="chapter" data-level="13.6" data-path="többváltozós-ols-regresszió-alapjai.html"><a href="többváltozós-ols-regresszió-alapjai.html#nominális-magyarázóváltozók---használtautó-adatok"><i class="fa fa-check"></i><b>13.6</b> Nominális magyarázóváltozók - Használtautó adatok</a></li>
<li class="chapter" data-level="13.7" data-path="többváltozós-ols-regresszió-alapjai.html"><a href="többváltozós-ols-regresszió-alapjai.html#dummy-változók-és-működésük-pythonban"><i class="fa fa-check"></i><b>13.7</b> Dummy változók és működésük Pythonban</a>
<ul>
<li class="chapter" data-level="13.7.1" data-path="többváltozós-ols-regresszió-alapjai.html"><a href="többváltozós-ols-regresszió-alapjai.html#referencia-kategória-megváltoztatása"><i class="fa fa-check"></i><b>13.7.1</b> Referencia kategória megváltoztatása</a></li>
</ul></li>
<li class="chapter" data-level="13.8" data-path="többváltozós-ols-regresszió-alapjai.html"><a href="többváltozós-ols-regresszió-alapjai.html#a-korrigált-r-négyzet-mutató"><i class="fa fa-check"></i><b>13.8</b> A korrigált R-négyzet mutató</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Bookdownban szerkesztve</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Következtető Statisztika Python Jegyzet</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="többváltozós-ols-regresszió-alapjai" class="section level1 hasAnchor" number="13">
<h1><span class="header-section-number">13</span> Többváltozós OLS Regresszió alapjai<a href="többváltozós-ols-regresszió-alapjai.html#többváltozós-ols-regresszió-alapjai" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="magyar-járások-covid-19-halálozási-arányai" class="section level2 hasAnchor" number="13.1">
<h2><span class="header-section-number">13.1</span> Magyar járások COVID-19 halálozási arányai<a href="többváltozós-ols-regresszió-alapjai.html#magyar-járások-covid-19-halálozási-arányai" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A <a href="https://github.com/KoLa992/Kovetkezteto-Statisztika-Python-Jegyzet/blob/main/COVID_JarasData.xlsx" target="_blank">COVID_JarasData.xlsx</a> fájl egy olyan adattábla, ami 102 magyar járásról (azokról, ahol a kórházak 2019-ben átlagos vagy átlag alatti leterheltségűek voltak a <a href="http://www.neak.gov.hu/data/cms1026624/Korhazi_agyszamkimutatas_2019.pdf">NEAK adatai</a> alapján) 5 változó (oszlop) adatát tárolja:</p>
<ul>
<li><strong>Jaras</strong>: A járás neve</li>
<li><strong>COVIDHalal</strong>: COVID-19 halálozási arány: elhunytak / fertőzöttek hányadosa (%) 2021.03.04-én. Forrás: <a href="https://bit.ly/COVID-adatok">atlatszo.hu</a></li>
<li><strong>Apolok</strong>: Háziorvosi szakápolók/ápolók száma 10000 főre (2019) Forrás: KSH</li>
<li><strong>Munkanelkuliseg</strong>: Nyilvántartott álláskeresők száma 10000 főre (2019) Forrás: KSH</li>
<li><strong>Nok65Felett</strong>: Lakónépességből a 65 éves és idősebb nők aránya (%) (2019) Forrás: KSH</li>
</ul>
<p>Olvassuk be a fájlt egy pandas <code>data frame</code>-be a pandas sima <code>read_excel</code> függvényével:</p>
<div class="sourceCode" id="cb950"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb950-1"><a href="többváltozós-ols-regresszió-alapjai.html#cb950-1" tabindex="-1"></a><span class="co"># Elemzéshez és ábrázoláshoz szükséges csomagok betöltése</span></span>
<span id="cb950-2"><a href="többváltozós-ols-regresszió-alapjai.html#cb950-2" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb950-3"><a href="többváltozós-ols-regresszió-alapjai.html#cb950-3" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb950-4"><a href="többváltozós-ols-regresszió-alapjai.html#cb950-4" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb950-5"><a href="többváltozós-ols-regresszió-alapjai.html#cb950-5" tabindex="-1"></a><span class="im">import</span> scipy.stats <span class="im">as</span> stats</span>
<span id="cb950-6"><a href="többváltozós-ols-regresszió-alapjai.html#cb950-6" tabindex="-1"></a></span>
<span id="cb950-7"><a href="többváltozós-ols-regresszió-alapjai.html#cb950-7" tabindex="-1"></a><span class="co"># 102 járás adatainak beolvasása</span></span>
<span id="cb950-8"><a href="többváltozós-ols-regresszió-alapjai.html#cb950-8" tabindex="-1"></a>covid <span class="op">=</span> pd.read_excel(<span class="st">&quot;COVID_JarasData.xlsx&quot;</span>)</span>
<span id="cb950-9"><a href="többváltozós-ols-regresszió-alapjai.html#cb950-9" tabindex="-1"></a>covid.info()</span></code></pre></div>
<pre><code>## &lt;class &#39;pandas.core.frame.DataFrame&#39;&gt;
## RangeIndex: 102 entries, 0 to 101
## Data columns (total 5 columns):
##  #   Column           Non-Null Count  Dtype  
## ---  ------           --------------  -----  
##  0   Jaras            102 non-null    object 
##  1   COVIDHalal       102 non-null    float64
##  2   Apolok           102 non-null    float64
##  3   Munkanelkuliseg  102 non-null    float64
##  4   Nok65Felett      102 non-null    float64
## dtypes: float64(4), object(1)
## memory usage: 4.1+ KB</code></pre>
<p>Láthatjuk, hogy megvan minden oszlop, amit a leírásban megadtunk. Megvan mind a négy numerikus (azaz <code>float</code>, mert törtszámokról van szó) típusú oszlopunk, és a <strong>Jaras</strong> oszlop maradhat <code>object</code>, azaz “szöveges” adattípusban, hiszen ez a járások azonosítója, minden név csak egyszer fordul elő a táblában, statisztikai elemzéseknek értelemszerűen nem vetjük alá ezt a változót. :)</p>
<p>Adja magát a dolog, hogy megpróbáljuk <strong>kétváltozós regressziókkal</strong> elemezni azt, hogy miképpen függ a vizsgált járásokban a COVID halálozási arány a másik három változótól (ápolók, munkanélküliek száma 10 ezer főre, 65 éven felüli nők aránya).</p>
<p>Első logikus gondolat azt diktálja, hogy hát minél több ápolója van népességarányosan egy járásnak, annál kevesebb lesz a COVID halálozási arány, hiszen a több ápoló jobba ellátást tud biztosítani. Teszteljük is le az elméletünket: csináljunk egy regressziót, ahol eredményváltozó (<span class="math inline">\(Y\)</span>) a <strong>COVIDHalal</strong>, magyarázóváltozó (<span class="math inline">\(X\)</span>) pedig az <strong>Apolok</strong>!</p>
<p>Első körben nézzük meg egy <span class="math inline">\(R^2\)</span> segítségével milyen szoros a két változónk köztü kapcsolat:</p>
<div class="sourceCode" id="cb952"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb952-1"><a href="többváltozós-ols-regresszió-alapjai.html#cb952-1" tabindex="-1"></a>(stats.pearsonr(covid.Apolok, covid.COVIDHalal)[<span class="dv">0</span>]<span class="op">**</span><span class="dv">2</span>)<span class="op">*</span><span class="dv">100</span></span></code></pre></div>
<pre><code>## 17.627405081896164</code></pre>
<p>Alapvetően az <span class="math inline">\(R^2\)</span> szép, korrekt dolgokat mutat. Az ápolók száma kb. 18 %-ban megmagyarázza a COVID halálozás alakulását a vizsgált járások körében (<span class="math inline">\(R^2=17.6\%\)</span>), ami egy közepes magyarázóerőnek minősíthető, hiszen <span class="math inline">\(10\% &lt; R^2 &lt; 50\%\)</span>.</p>
<p>Nézzük meg, hogy néz ki a regressziós egyenes egyenlete! Használjuk nyugodtan a <a href="https://kola992.github.io/Kovetkezteto-Statisztika-Python-Jegyzet/k%C3%A9tv%C3%A1ltoz%C3%B3s-line%C3%A1ris-regresszi%C3%B3.html#egy-gyakorl%C3%B3-p%C3%A9lda-covid-adatokon" target="_blank">12.6. fejezetben</a> megismert <code>polyfit</code> függvényét a <code>numpy</code> csomagnak:</p>
<div class="sourceCode" id="cb954"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb954-1"><a href="többváltozós-ols-regresszió-alapjai.html#cb954-1" tabindex="-1"></a>Beta1, Beta0 <span class="op">=</span> np.polyfit(covid.Apolok, covid.COVIDHalal, deg <span class="op">=</span> <span class="dv">1</span>)</span>
<span id="cb954-2"><a href="többváltozós-ols-regresszió-alapjai.html#cb954-2" tabindex="-1"></a><span class="bu">print</span>([Beta1, Beta0])</span></code></pre></div>
<pre><code>## [0.3629321944430193, 2.02043692521212]</code></pre>
<p>A 102 járás adatából illesztett regressziós modell szerint tehát: <span class="math display">\[Becsult COVIDHalal= 0.36 \times Apolok + 2.02\]</span></p>
<p><strong>Ajjajjaj!</strong> A modell <strong>meredeksége pozitív</strong>!! Konkrétan, ha a járásban az ápolók száma 10 ezer főre nő 1-gyel, akkor várhatóan a COVID halálozási arány is <strong>növekedni</strong> fog 0.36 százalékponttal! Ez alapján úgy tűnik, hogy mintha megérné kevesebb ápolót tartani, mert akkor fog csökkenni a COVID halálozás a járásban. Ezt az eredményt így nagyon nem eszi meg a gyomrunk!</p>
<p>A fura eredmény háttérben egy úgynevezett <strong>confunding</strong> nevű jelenség áll!</p>
<p>Lessük csak meg a minden <strong>covid</strong> <code>data frame</code>-ben lévő numerikus változó korrelációmátrixát! Ez egy oylan táblázat, amiben az egyes numerikus változók közti korrelációkat mutatja meg nekünk a gépállat. Simán egy <code>data frame</code> numerikus változóiból a <code>data frame</code> numerikus oszlopain (mindegyik kivéve az elsőt) elsütött <code>cor</code> metódussal hívható elő.</p>
<div class="sourceCode" id="cb956"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb956-1"><a href="többváltozós-ols-regresszió-alapjai.html#cb956-1" tabindex="-1"></a>covid.iloc[:,<span class="dv">1</span>:<span class="dv">5</span>].corr()</span></code></pre></div>
<pre><code>##                  COVIDHalal    Apolok  Munkanelkuliseg  Nok65Felett
## COVIDHalal         1.000000  0.419850         0.495429     0.411443
## Apolok             0.419850  1.000000         0.540570     0.517462
## Munkanelkuliseg    0.495429  0.540570         1.000000     0.228315
## Nok65Felett        0.411443  0.517462         0.228315     1.000000</code></pre>
<p>A korrelációkból látszik, hogy a <strong>COVIDHalal</strong> változóval a másik három változó egyirányú, és közepes erősségű kapcsolatban állnak (mindegyik korreláció a COVIDHalal oszlopában, ami nem az önmagával vett korrelációt jelenti az +0.4 körüli érték). Ez a <strong>Munkanelkuliseg</strong> és <strong>Nok65Felett</strong> változók esetén logikus is, hiszen a COVID elsősorban a 65 év felettiek körében halálos, illetve azok körében ahol eleve több alapbetegség jelen volt. Ahol magas a munkanélküliség, ott pedig eleve rosszabb az egészségi állapot: alkoholizmus, szív- és érrendszeri problémák gyakoriak a magas munkanélküliségű járásokban (lásd pl. <a href="https://reader.elsevier.com/reader/sd/pii/S0927537120300609?token=E1AD2E1805FB5308BC40754433D867BE2D6F2FEC1EECA824AFAFC2F37BF35723550C07B43E62BE53CD9F6822494FF445&amp;originRegion=eu-west-1&amp;originCreation=20211005092903">ezt a tanulmányt</a>).<br>
NODE, az <strong>Apolok</strong> egyirányú módon és közepes erősségben összefügg a <strong>Munkanelkuliseg</strong> és <strong>Nok65Felett</strong> változókkal is! Tehát, valószínűleg a magas 10 ezer főre jutó ápolószámmal bíró járásokban <em>csak azért magas a COVID halálozás</em>, mert ezekben a járásokban magas a munkanélküliség és az idős népesség aránya is! Tehát a népesség egészségi állapota ezen járásokban <strong>eleve rosszabb</strong>!<br>
Na, ez a jelenség a <strong>confunding</strong>: amikor egy változó csak azért korrelál egy másikkal, mert <strong>valójában egy vagy több másik változó hatását közvetíti a saját hatásán túl</strong>.</p>
<p>Szóval, a feladat adott: fejtsük meg, hogy ha leválasztjuk az <strong>Apolok</strong> változóról a <strong>Munkanelkuliseg</strong> és <strong>Nok65Felett</strong> változók hatását (azaz kiszűrjük/megtisztítjuk a <em>confunding</em> hatást), akkor hogyan hat az <strong>Apolok</strong> változó <strong>önállóan</strong> a <strong>COVIDHalal</strong>-ra!<br>
Erre a feladatra eszözünk a <strong>többváltozós lineáris regresszió</strong>! Ami egyszerűen a sima <span class="math inline">\(\hat{Y}=\beta_1 X + \beta_0\)</span> kétváltozós regresszió kiterjesztése úgy, hogy az egyenletbe tetszőleges, konkrétan <span class="math inline">\(k\)</span> db magyarázóváltozót rakunk be, és mindenkinek meglesz a maga <span class="math inline">\(\beta\)</span>-ja:
<span class="math display">\[\hat{Y}=\beta_1 X_1 + \beta_2 X_2 + ... + \beta_k X_k + \beta_0\]</span></p>
<p>Az előbbi egyenlet alapján a <strong>többváltozós lineáris regresszió</strong>t úgy is értelmezhetjük, mint egy olyan statisztikai modellt, ami a COVID halálozási arányokat akarja előrejelezni <strong>egyszerre az ápolószám, munkanélküliség és 65 év feletti női népesség aránya</strong> segítségével!</p>
</div>
<div id="a-többváltozós-lineáris-regresszió-ols-elvű-előállítása" class="section level2 hasAnchor" number="13.2">
<h2><span class="header-section-number">13.2</span> A Többváltozós Lineáris Regresszió OLS elvű előállítása<a href="többváltozós-ols-regresszió-alapjai.html#a-többváltozós-lineáris-regresszió-ols-elvű-előállítása" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A nagy szerencsénk, hogy a többváltozós regresszióban is lényegében változtatás nélkül működik a <span class="math inline">\(\beta_j\)</span>-k OLS elvű meghatározási módja.<br>
Azaz, úgy választjuk meg a <span class="math inline">\(\beta_j\)</span>-ket, hogy az COVID halálozási arányokra (<span class="math inline">\(Y\)</span>) adott becsléseink hibája minimális legyen. A becslési hibát az ún. SSE mutatóval mérjük továbbra is: <span class="math inline">\(Sum of Squared Errors (SSE) = \sum_{i=1}^n(y_i-\hat{y_i})^2\)</span>.<br></p>
<p>Az továbbra is igaz lesz, hogy négyzetesen mért hiba esetében a gép itt <strong>sem vaktában keresi</strong> a <span class="math inline">\(\beta\)</span>-kat! Az OLS feladat megoldása (tehát a legkisebb <span class="math inline">\(SSE\)</span>-t adó <span class="math inline">\(\beta\)</span>-k) kifejezhetők egy fix képlettel itt is!</p>
<p>Az <span class="math inline">\(SSE=\sum_{i=1}^n(y_i-\hat{y_i})^2=\sum_{i}(y_i-\sum_{j}\beta_jx_j)^2\)</span> képlet kifejezhető mátrixosan is, ha bevezetjük az <span class="math inline">\(X\)</span> mátrikot, aminek az első oszlopa csupa 1-et tartalmaz (a tengelymetszet miatt) és a többi oszlopaiba az <span class="math inline">\(X_j\)</span>-ket rakjuk, akkor az <span class="math inline">\(SSE\)</span>-t így is fel tudjuk írni: <span class="math inline">\(SSE=||y-X\beta||^2\)</span>. Ha ezt a mátrixosan kifejezett függvényt deriváljuk a <span class="math inline">\(\beta\)</span>-k szerint, és a deriváltakat egyenlővé tesszük 0-val, akkor kifejezhető az a fix formula, amivel az OLS elven számított <span class="math inline">\(\beta\)</span>-k vektora megadható: <span class="math inline">\(\beta=(X^TX)^{-1}X^Ty\)</span>.</p>
<p>Azt, hogy konkrétan hogyan jön ki ez a csodaszép mátrixos formula, nekünk annyira nem fontos. A gyakorlati szempontból azt kell látni, hogy minimalizálási feladathoz többváltozós regresszió esetén sem kell a 3. gyakorlaton látott <code>optim</code> függvény, mert a megoldása egy fix mátrixos képlet. <strong>Emiatt használják az OLS regressziót mai napig előszeretettel: fix képlettel megadhatók a <span class="math inline">\(\beta\)</span> együtthatók többváltozós esetben is!</strong></p>
<p>Az a nagy szerencse, hogy a mi három magyarázóváltozót használó modellünk együtthatóit ilyen OLS elven meg lehet becsültetni Pythonban a <code>statsmodels</code> csomag <code>OLS</code> nevű függvényével. Ehhez először importáljuk a csomag függvényeit egy <code>sm</code> c. névtérbe.</p>
<div class="sourceCode" id="cb958"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb958-1"><a href="többváltozós-ols-regresszió-alapjai.html#cb958-1" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span></code></pre></div>
<p>A függvény használatához először el kell különíteni egy külön objektumba az eredményváltozó oszlopát a vizsgált <code>data frame</code>-ből. Hívjuk most ezt az objetktumot <code>Y</code>-nak.</p>
<div class="sourceCode" id="cb959"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb959-1"><a href="többváltozós-ols-regresszió-alapjai.html#cb959-1" tabindex="-1"></a>Y <span class="op">=</span> covid.COVIDHalal</span></code></pre></div>
<p>Majd ezek után egy külön <code>data frame</code>-be összegyűjtöm csak a magyarázóváltozókat, hívjuk ezt az új <code>data frame</code>-t most szimplán <code>X</code>-nek. Utána a <code>statsmodels</code> csomag <code>add_constant</code> függvényével hozzáadunk egy csupa <span class="math inline">\(1\)</span>-ből álló oszlopot, ahogy a regresszió korábban látott mátrixos felírásában is vettük az <span class="math inline">\(X\)</span> mátrixot.</p>
<div class="sourceCode" id="cb960"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb960-1"><a href="többváltozós-ols-regresszió-alapjai.html#cb960-1" tabindex="-1"></a>X <span class="op">=</span> covid.loc[:,[<span class="st">&#39;Apolok&#39;</span>,<span class="st">&#39;Munkanelkuliseg&#39;</span>,<span class="st">&#39;Nok65Felett&#39;</span>]]</span>
<span id="cb960-2"><a href="többváltozós-ols-regresszió-alapjai.html#cb960-2" tabindex="-1"></a>X <span class="op">=</span> sm.add_constant(X)</span>
<span id="cb960-3"><a href="többváltozós-ols-regresszió-alapjai.html#cb960-3" tabindex="-1"></a>X</span></code></pre></div>
<pre><code>##      const     Apolok  Munkanelkuliseg  Nok65Felett
## 0      1.0   7.354416       369.057966    14.735575
## 1      1.0  10.385919       227.396961    14.873729
## 2      1.0   6.256924       227.403274    13.129282
## 3      1.0   4.421334        65.454965    11.351294
## 4      1.0   6.876948       676.691729    12.350999
## ..     ...        ...              ...          ...
## 97     1.0   7.377035       625.503954    14.313164
## 98     1.0   7.567731       586.751425    14.237425
## 99     1.0   5.884826       287.876058    13.452231
## 100    1.0   8.136283       520.722095    16.730231
## 101    1.0   8.535544       338.983051    15.522497
## 
## [102 rows x 4 columns]</code></pre>
<p>És végül akkor az <code>sm</code> névtér <code>OLS</code> függvényébe berakjuk ezeket az újonnan létrehozott <code>Y</code> és <code>X</code> Python objektumokat (kötelezően ebben a sorrendben), és végül meghívunk az egészen egy <code>fit()</code> metódust. Az eredményt pedig egy külön Python objektumba kell elmenteni.</p>
<div class="sourceCode" id="cb962"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb962-1"><a href="többváltozós-ols-regresszió-alapjai.html#cb962-1" tabindex="-1"></a>sokvalt_modell <span class="op">=</span> sm.OLS(Y,X).fit()</span></code></pre></div>
<p>A többváltozós regressziós modell legfontosabb statisztikai mutatóit egy nap összefoglaló táblázatban az az újonnan létrehozott <code>sokvalt_modell</code> objektum <code>summary()</code> metódusával lehet lekérdezni.</p>
<div class="sourceCode" id="cb963"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb963-1"><a href="többváltozós-ols-regresszió-alapjai.html#cb963-1" tabindex="-1"></a><span class="bu">print</span>(sokvalt_modell.summary())</span></code></pre></div>
<pre><code>##                             OLS Regression Results                            
## ==============================================================================
## Dep. Variable:             COVIDHalal   R-squared:                       0.341
## Model:                            OLS   Adj. R-squared:                  0.321
## Method:                 Least Squares   F-statistic:                     16.89
## Date:                 H, 30 jún. 2025   Prob (F-statistic):           6.42e-09
## Time:                        15:22:28   Log-Likelihood:                -152.39
## No. Observations:                 102   AIC:                             312.8
## Df Residuals:                      98   BIC:                             323.3
## Df Model:                           3                                         
## Covariance Type:            nonrobust                                         
## ===================================================================================
##                       coef    std err          t      P&gt;|t|      [0.025      0.975]
## -----------------------------------------------------------------------------------
## const              -0.1542      0.937     -0.165      0.870      -2.015       1.706
## Apolok              0.0445      0.096      0.463      0.644      -0.146       0.235
## Munkanelkuliseg     0.0028      0.001      4.099      0.000       0.001       0.004
## Nok65Felett         0.2656      0.087      3.053      0.003       0.093       0.438
## ==============================================================================
## Omnibus:                       25.226   Durbin-Watson:                   1.957
## Prob(Omnibus):                  0.000   Jarque-Bera (JB):               36.179
## Skew:                           1.173   Prob(JB):                     1.39e-08
## Kurtosis:                       4.735   Cond. No.                     3.10e+03
## ==============================================================================
## 
## Notes:
## [1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
## [2] The condition number is large, 3.1e+03. This might indicate that there are
## strong multicollinearity or other numerical problems.</code></pre>
<p>Nézzük meg mit látunk a <code>summary</code> eredményeként:</p>
<ul>
<li>Mivel az OLS elvű becslése, tehát a teljes modellhiba <span class="math inline">\(SSE\)</span> elvű mérése megmaradt, így <span class="math inline">\(R^2\)</span>-et továbbra is tudunk számolni <span class="math inline">\(R^2=1-\frac{SSE}{SST}\)</span> módon. Az értelmezése pedig annyiban módosul, hogy azt adja meg <strong>hány százalékban magyarázza az eredményváltozót a magyarázóváltozók összessége</strong>. Arra figyeljünk, az előbbi értelmezés miatt, hogy korreláció négyzeteként már <strong>NEM</strong> számolható a mutató, hiszen korreláció <em>egyszerre csak két változó kapcsolatát tudja leírni</em>, kettőnél több több változóét már nem. Ez alapján jelen szituációban azt mondhatjuk el, hogy az ápolók száma, 65 feletti női népesség aránya és munkanélküliség <strong>együtt</strong> <span class="math inline">\(34\%\)</span>-ban magyarázzák a COVID halálozási arányok ingadozását a járások között. Ez érezhető magyarázóerő növekedés a kétváltozós modellhez képest, ahol csak az <strong>Apolok</strong> hatását vizsgáltuk.</li>
<li>A Globális F-próba p-értéke most is jó alacsony, mivel <code>Prob (F-statistic)</code> = <span class="math inline">\(6.42 \times 10^{-9}\)</span>. Tehát, nem meglepő módon azt mondhatjuk, hogy minden szokásos <span class="math inline">\(\alpha\)</span>-n elutasíthatjuk, azt a <span class="math inline">\(H_0\)</span>-t, hogy az <span class="math inline">\(R^2\)</span> összeomlik 0-ba a mintán kívüli világban. Amit itt érdemes megfigyelni az a p-érték számoláshoz használt F-eloszlás szabadságfokai. Most nekünk ugye <span class="math inline">\(k=3\)</span> magyarázóváltozónk van, az azt jelenti, hogy a regresszióban <span class="math inline">\(p=4\)</span> paramétert, azaz <span class="math inline">\(\beta_j\)</span>-t kellett megbecsülnie az OLS-nek a tengelymetszet miatt. Ez alapján az F-eloszlás első szabadságfoka <span class="math inline">\(p-1=3=k\)</span>, míg a második szabadságfok <span class="math inline">\(n-p=102-4=98=n-k-1\)</span>.</li>
<li>Ezen kívül az F-próba hipotéziseit úgy is fel lehet írni, mint: <span class="math inline">\(H_0: \beta_j=0 \forall j\)</span>, azaz minden <span class="math inline">\(\beta\)</span> a mintán kívüli világban 0-nak vehető, semminek nincs magyarázóereje <span class="math inline">\(Y\)</span>-ra. És <span class="math inline">\(H_1: \exists j:\beta_j \neq 0\)</span>, tehát van legalább egy darab <span class="math inline">\(\beta\)</span>, ami nem nulla a mintán kívüli világban, és a hozzá tartozó <span class="math inline">\(X_j\)</span>-nek van hatása <span class="math inline">\(Y\)</span>-ra a mintán kívüli világban is.</li>
</ul>
<p>A <code>Coefficients</code> táblából ismét felírható a megbecsült modell egyenlete: <span class="math display">\[BecsultCOVIDHalal=0.04 \times Apolok + 0.003 \times Munkanelkuliseg + 0.27 \times Nok65Felett - 0.15\]</span></p>
<p>Az egyenlet olyan szempontból furának tűnik, hogy az <strong>Apolok</strong> együtthatója még mindig pozitív, bár tény, hogy már csak <span class="math inline">\(0.04\)</span> az értéke a kétváltozós modell <span class="math inline">\(0.36\)</span>-os meredeksége helyett.<br>
Ahhoz, hogy pontosan megértsük mit is takar ez a <span class="math inline">\(0.04\)</span> és megadjuk hogyan lehet megmérni egy magyarázóváltozó (<span class="math inline">\(X_j\)</span>) fontosságát a regressziós modellünk előrejelzéseiben, egy kicsit alaposabban meg kell érteni mit is takarnak ezek a <span class="math inline">\(\beta_j\)</span> értékek a többváltozós regresszióban.</p>
</div>
<div id="a-magyarázóváltozók-marginális-hatása" class="section level2 hasAnchor" number="13.3">
<h2><span class="header-section-number">13.3</span> A magyarázóváltozók marginális hatása<a href="többváltozós-ols-regresszió-alapjai.html#a-magyarázóváltozók-marginális-hatása" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Ahogyan a 2. fejezetben írtam, a az OLS regressziót azért használják a mai napig előszeretettel, mert fix képlettel megadhatók a <span class="math inline">\(\beta_j\)</span> együtthatók. De ez csak az egyik oka a modell népszerűségének. A másik az, hogy a <span class="math inline">\(\beta_j\)</span> együtthatók megfeleltethetők a hozzájuk tartozó <span class="math inline">\(X_j\)</span> magyarázóváltozók <strong>marginális hatásának</strong>.</p>
<p>Az <span class="math inline">\(X_j\)</span> magyarázóváltozó marginális hatása az a hatás, amit ő <strong>egyedül és közvetlenül</strong> fejt ki az <span class="math inline">\(Y\)</span> eredményváltozó alakulására. OLS regresszióban ez a marginális hatás <span class="math inline">\(X_j\)</span> magyarázóváltozó esetében épp a <span class="math inline">\(\beta_j\)</span> együttható lesz.</p>
<p>Most ez alapján egy <span class="math inline">\(\beta_j\)</span> általános értelmezése a következő: <strong>Ha az adott bétához tartozó magyarázóváltozó értéke egy egységgel nő a többi magyarázóváltozó értékének változatlansága mellett, akkor az eredményváltozó értéke várhatóan bétányit változik.</strong></p>
<p>Ennek az értelmezésnek <strong>3 kötelező eposzi kelléke</strong> van:</p>
<ol style="list-style-type: decimal">
<li>Minden változás az eredményváltozó és az éppen vizsgált magyarázóváltozó <strong>saját mértékegységében</strong> értendő</li>
<li>Az éppen nem vizsgált magyarázóváltozók értékéről feltesszük, hogy nem változnak. Ezzel az éppen vizsgált <span class="math inline">\(X_j\)</span> közvetlen hatását mérjük meg <span class="math inline">\(Y\)</span>-ra. Ez a <strong>ceteris paribus elv</strong>.</li>
<li>A <span class="math inline">\(\beta_j\)</span> az <span class="math inline">\(Y\)</span>-ban okozott <strong>várható</strong> változást mutatja csak! Ez a változás akkor lenne egész biztosan épp <span class="math inline">\(\beta_j\)</span>-nyi, ha <span class="math inline">\(R^2=100\%\)</span> lenne.</li>
</ol>
<p>Ha ez az értelemzés így általánosságban igaz, akkor az <strong>Apolok</strong> <span class="math inline">\(+0.04\)</span>-es <span class="math inline">\(\beta\)</span>-ja a többváltozós regressziónkban már megtisztult a munkanélküliség és a 65 év feletti népesség <strong>confunding</strong> hatásától, hiszen a <span class="math inline">\(0.04\)</span> egy ezek megváltozása <em>nélküli</em> +1 egység <strong>Apolok</strong> növekedés esetén mutatja be a COVID halálozás várható változását.</p>
<p>Ezek alapján nézzük meg a jelenlegi modellünkben vett <span class="math inline">\(\beta_j\)</span>-k értelmezése! Ha csak a modell <span class="math inline">\(\beta_j\)</span>-it akarom lekérdezni és semmi egyebet, akkor azt a modellt tartalmazó Python objektum <code>params</code> tulajdonságának lekérdezésével tudom megtenni.</p>
<div class="sourceCode" id="cb965"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb965-1"><a href="többváltozós-ols-regresszió-alapjai.html#cb965-1" tabindex="-1"></a>sokvalt_modell.params</span></code></pre></div>
<pre><code>## const             -0.154215
## Apolok             0.044522
## Munkanelkuliseg    0.002819
## Nok65Felett        0.265567
## dtype: float64</code></pre>
<ul>
<li><span class="math inline">\(\beta_1=0.04\)</span>: Ha egy járásban a 10 ezer főre jutó ápolók száma nő 1 fővel változatlan munkanélküliség és 65 év feletti női népesség mellett, akkor a járás COVID halálozási aránya várhatóan 0.04 százalékponttal emelkedik. Ez még mindig nem tűnik szimpatikusnak, de majd mindjárt a végére járunk.</li>
<li><span class="math inline">\(\beta_2=0.003\)</span>: Ha egy járásban az álláskeresők száma 10 ezer fővel (azaz a 10 ezer főre jutó álláskeresők száma 1 fővel) nő változatlan ápolószám és 65 év feletti női népesség mellett, akkor a járás COVID halálozási aránya várhatóan 0.003 százalékponttal emelkedik. Egy fokkal magyarosabban: Ha két azonos ápolószámú és azonos 65 év feletti női népességgel bíró járás közül az egyiknek 10 ezer fővel több munkanélkülije van, akkor ott várhatóan 0.003 százalékponttal nagyobb esélye van egy COVID fertőzöttnek meghalni.</li>
<li><span class="math inline">\(\beta_3=0.27\)</span>: Ha egy járásban a 65 év feletti női népesség aránya 1 százalékponttal nő változatlan ápolószám és munkanélküliség mellett, akkor a járás COVID halálozási aránya várhatóan 0.27 százalékponttal emelkedik. Egy fokkal magyarosabban: Ha két azonos ápolószámú és munkanélüliségű járás közül az egyik népességében 1 százalékponttal több lesz a 65 év feletti nők aránya, akkor ott várhatóan 0.27 százalékponttal nagyobb esélye van egy COVID fertőzöttnek meghalni.</li>
</ul>
<p>Persze van még <strong>egy <span class="math inline">\(\beta_0\)</span> tengelymetszetünk, ami hivatalosan azt mutatja meg, hogy mennyi lenne az <span class="math inline">\(\hat{Y}\)</span>, ha a modellben minden magyarázóváltozó (<span class="math inline">\(X_j\)</span>) 0 értéket venne fel</strong>.<br>
Ez esetünkben azt jelenti, hogy egy 0 ápolójú, 65 év feletti nők nélküli és teljes foglalkoztatottságú járás COVID halálozási aránya a modellünk alapján <span class="math inline">\(-0.15\%\)</span>. Nyilván ezzel az értelmezéssel most nem kell foglalkozni, mivel a <span class="math inline">\(\forall X_j=0\)</span> hely jelen tématerületen nem létezik. Ha valaki talál egy ilyen <em>csupa 0</em> járást, akkor viszont meneküljön onnan, mert jönnek a zombik :) (negatív halálozási arány :))</p>
<div id="útelemzés" class="section level3 hasAnchor" number="13.3.1">
<h3><span class="header-section-number">13.3.1</span> Útelemzés<a href="többváltozós-ols-regresszió-alapjai.html#útelemzés" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Az a tény, hogy többváltozós regresszióban a <span class="math inline">\(\beta_j\)</span> együtthatók megfeleltethetők a hozzájuk tartozó <span class="math inline">\(X_j\)</span> magyarázóváltozók <strong>marginális hatásának</strong>, elvezet minket az egyes <span class="math inline">\(X_j\)</span> magyarázóváltozók közvetlen és közvetett hatásának fogalmához. Egy tetszőleges <span class="math inline">\(X_j\)</span> magyarázóváltozó közvetlen és közvetett hatásait konkrétan, számszerűen is ki lehet fejezni a regressziós <span class="math inline">\(\beta\)</span>-k segítségével.</p>
<p>Vegyük az eddig is vizsgált <strong>Apolok</strong> változó közvetlen és közvetett hatásait az alábbi ábrán szemléltetve az 1. fejezet korrelációmátrixából alapján kiindulva. Ugye a korrelációk alapján az volt az elképzelésünk, hogy <strong>az ápolók száma csak azért lehet magas pozitív korrelációban a COVID halálozással, mert a nagyobb munkanélküliség jellemzően nagyobb ápolószámmal jár együtt, és a magas munkanélküliség megnövelte a COVID halálozást, az ápolószámnak meg lehet, hogy önállóan semmi hatása nincs</strong>. Lássuk, hogy a <strong>regressziós együtthatók igazolják-e ezt az elképzelést</strong>!</p>
<center>
<img src="Utelemzes.png" style="width:50.0%" />
</center>
<p>Itt a <em>piros</em> nyíl jelöli az <strong>Apolok</strong> közvetlen hatását a <strong>COVIDHalal</strong>-ra, míg a <em>kék</em> nyíl a <strong>Munkanelkuliseg</strong> közvetlen hatását a <strong>COVIDHalal</strong>-ra. A <em>zöld</em> nyíl pedig az <strong>Apolok</strong> hatása a <strong>Munkanelkuliseg</strong>-re.</p>
<p>A piros és kék nyilakon lévő közvetlen hatások nagyságát megadja a <span class="math inline">\(BecsultCOVIDHalal=\beta_1 \times Apolok + \beta_2 \times Munkanelkuliseg + \beta_0\)</span> regresszió <span class="math inline">\(\beta_1\)</span> és <span class="math inline">\(\beta_2\)</span> együtthatója. Szóval nyejük is ki ezeket a <span class="math inline">\(\beta\)</span>-kat külön R objektumokba:</p>
<div class="sourceCode" id="cb967"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb967-1"><a href="többváltozós-ols-regresszió-alapjai.html#cb967-1" tabindex="-1"></a><span class="co"># először legyártjuk a két magyarázóváltozós regressziót</span></span>
<span id="cb967-2"><a href="többváltozós-ols-regresszió-alapjai.html#cb967-2" tabindex="-1"></a>X_ketvalt <span class="op">=</span> covid.loc[:,[<span class="st">&#39;Apolok&#39;</span>, <span class="st">&#39;Munkanelkuliseg&#39;</span>]]</span>
<span id="cb967-3"><a href="többváltozós-ols-regresszió-alapjai.html#cb967-3" tabindex="-1"></a>X_ketvalt <span class="op">=</span> sm.add_constant(X_ketvalt)</span>
<span id="cb967-4"><a href="többváltozós-ols-regresszió-alapjai.html#cb967-4" tabindex="-1"></a>ketmagyvalt_modell <span class="op">=</span> sm.OLS(Y, X_ketvalt).fit()</span>
<span id="cb967-5"><a href="többváltozós-ols-regresszió-alapjai.html#cb967-5" tabindex="-1"></a></span>
<span id="cb967-6"><a href="többváltozós-ols-regresszió-alapjai.html#cb967-6" tabindex="-1"></a><span class="co"># megnézzük az együtthatókat tartalmazó tömböt</span></span>
<span id="cb967-7"><a href="többváltozós-ols-regresszió-alapjai.html#cb967-7" tabindex="-1"></a>ketmagyvalt_modell.params</span></code></pre></div>
<pre><code>## const              2.326507
## Apolok             0.185685
## Munkanelkuliseg    0.002669
## dtype: float64</code></pre>
<div class="sourceCode" id="cb969"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb969-1"><a href="többváltozós-ols-regresszió-alapjai.html#cb969-1" tabindex="-1"></a></span>
<span id="cb969-2"><a href="többváltozós-ols-regresszió-alapjai.html#cb969-2" tabindex="-1"></a><span class="co"># a tömb 2. és 3. elemét a neveik alapján elmentjük: figyeljünk, hogy a 0. indexű elem a Béta_0!</span></span>
<span id="cb969-3"><a href="többváltozós-ols-regresszió-alapjai.html#cb969-3" tabindex="-1"></a>Beta_Apolok_COVID <span class="op">=</span> ketmagyvalt_modell.params[<span class="st">&#39;Apolok&#39;</span>]</span>
<span id="cb969-4"><a href="többváltozós-ols-regresszió-alapjai.html#cb969-4" tabindex="-1"></a>Beta_Munkanelk_COVID <span class="op">=</span> ketmagyvalt_modell.params[<span class="st">&#39;Munkanelkuliseg&#39;</span>]</span></code></pre></div>
<p>A zöld nyílon található hatás nagyságát pedig egyszerűen a <span class="math inline">\(BecsultMunkanelkuliseg = \beta_1 \times Apolok + \beta_0\)</span> kétváltozós regresszió <span class="math inline">\(\beta_1\)</span> együtthatója adja meg. Ezt is mentsük le külön Python objektumokba:</p>
<div class="sourceCode" id="cb970"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb970-1"><a href="többváltozós-ols-regresszió-alapjai.html#cb970-1" tabindex="-1"></a><span class="co"># legyártjuk a két magyarázóváltozós regresszió együtthatóit, és a meredekség lesz a &quot;zöld nyíl&quot; értéke</span></span>
<span id="cb970-2"><a href="többváltozós-ols-regresszió-alapjai.html#cb970-2" tabindex="-1"></a>Beta1_Apolok_Munkanelk, Beta0_Apolok_Munkanelk <span class="op">=</span> np.polyfit(covid.Apolok, covid.Munkanelkuliseg, deg<span class="op">=</span><span class="dv">1</span>)</span></code></pre></div>
<p>Ezzel pedig megadható az <span class="math inline">\(Apolok \rightarrow COVIDHalal\)</span> kapcsolat <em>közvetlen és közvetett</em> hatásai:</p>
<div class="sourceCode" id="cb971"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb971-1"><a href="többváltozós-ols-regresszió-alapjai.html#cb971-1" tabindex="-1"></a><span class="co"># közvetlen hatása az ápolók számának a COVID halálozásra (piros nyíl)</span></span>
<span id="cb971-2"><a href="többváltozós-ols-regresszió-alapjai.html#cb971-2" tabindex="-1"></a>Kozvetlen_Apolok_COVID <span class="op">=</span> Beta_Apolok_COVID</span>
<span id="cb971-3"><a href="többváltozós-ols-regresszió-alapjai.html#cb971-3" tabindex="-1"></a>Kozvetlen_Apolok_COVID</span></code></pre></div>
<pre><code>## 0.18568467374999392</code></pre>
<div class="sourceCode" id="cb973"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb973-1"><a href="többváltozós-ols-regresszió-alapjai.html#cb973-1" tabindex="-1"></a><span class="co"># közvetett hatása az ápolók számának a COVID halálozásra (zöld*kék nyíl)</span></span>
<span id="cb973-2"><a href="többváltozós-ols-regresszió-alapjai.html#cb973-2" tabindex="-1"></a>Kozvetett_Apolok_COVID <span class="op">=</span> Beta1_Apolok_Munkanelk <span class="op">*</span> Beta_Munkanelk_COVID</span>
<span id="cb973-3"><a href="többváltozós-ols-regresszió-alapjai.html#cb973-3" tabindex="-1"></a>Kozvetett_Apolok_COVID</span></code></pre></div>
<pre><code>## 0.17724752069302113</code></pre>
<p>Hiszen a <strong>közvetett</strong> hatás csupán annyi, hogy annyiszor kell venni a <span class="math inline">\(Munkanelkuliseg \rightarrow COVIDHalal\)</span> közvetlen hatást (kék nyíl), ahányszor megváltozik a <strong>Munkanelkuliseg</strong> egy egység <strong>Apolok</strong> növekedésre (zöld nyíl). Ezt pedig éppen a <code>Beta_Apolok_Munkanelk</code> adja meg!</p>
<p>Ezzel pedig megadható a <span class="math inline">\(Apolok \rightarrow COVIDHalal\)</span> kapcsolat <em>teljes</em> hatása:</p>
<div class="sourceCode" id="cb975"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb975-1"><a href="többváltozós-ols-regresszió-alapjai.html#cb975-1" tabindex="-1"></a><span class="co"># teljes hatás = közvetlen + közvetett hatás</span></span>
<span id="cb975-2"><a href="többváltozós-ols-regresszió-alapjai.html#cb975-2" tabindex="-1"></a>Teljes_Apolok_COVID <span class="op">=</span> Kozvetlen_Apolok_COVID <span class="op">+</span> Kozvetett_Apolok_COVID</span>
<span id="cb975-3"><a href="többváltozós-ols-regresszió-alapjai.html#cb975-3" tabindex="-1"></a>Teljes_Apolok_COVID</span></code></pre></div>
<pre><code>## 0.36293219444301505</code></pre>
<p>És jé, ez az érték pont ugyan az, mint *az eredeti <span class="math inline">\(BecsultCOVIDHalal = \beta_1 \times Apolok + \beta_0\)</span> kétváltozós regresszió <span class="math inline">\(\beta_1\)</span> meredeksége! :)</p>
<div class="sourceCode" id="cb977"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb977-1"><a href="többváltozós-ols-regresszió-alapjai.html#cb977-1" tabindex="-1"></a>Beta1 <span class="co"># Ezt ugye még az 1. fejezetben hoztuk létre!</span></span></code></pre></div>
<pre><code>## 0.3629321944430193</code></pre>
<p>Tehát, tényleg az eredeti kétváltozós regresszióban lévő <strong>confunding</strong> hatást tudtuk letisztítani a többváltozós regresszióval az <strong>Apolok</strong> változóra nézve!</p>
<p>Nyilván hasonló módon lehetne megmérni, hogy mennyi az <span class="math inline">\(Apolok \rightarrow COVIDHalal\)</span> kapcsolatban a <strong>Nok65Felett</strong> változó <em>közvetett hatása</em> miatt fellépő <strong>confunding</strong> hatása a <span class="math inline">\(BecsultCOVIDHalal = \beta_1 \times Apolok + \beta_0\)</span> kétváltozós regresszió <span class="math inline">\(\beta_1\)</span> meredekségében.</p>
</div>
<div id="parciális-t-próba" class="section level3 hasAnchor" number="13.3.2">
<h3><span class="header-section-number">13.3.2</span> Parciális t-próba<a href="többváltozós-ols-regresszió-alapjai.html#parciális-t-próba" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A magyarázóváltozók fontosságát hipotézisvizsgálattal is meg tudjuk mérni. Egy tetszőleges <span class="math inline">\(X_j\)</span> magyarázóváltozó fontosságát az alábbi null- alteranatív hipotézis páros tesztelésével tudjuk megállapítani:</p>
<ul>
<li><span class="math inline">\(H_0: \beta_j=0\)</span> ~ <span class="math inline">\(X_j\)</span> hatása <span class="math inline">\(Y\)</span>-ra a mintán kívül <strong>nem szignifikáns</strong></li>
<li><span class="math inline">\(H_1: \beta_j\neq0\)</span> ~ <span class="math inline">\(X_j\)</span> hatása <span class="math inline">\(Y\)</span>-ra a mintán kívül <strong>szignifikáns</strong></li>
</ul>
<p>Tehát ebben a hipotézisvizsgálatban, amit <em>parciális t-próbának</em> fogunk hívni, <strong>azt mondja a <span class="math inline">\(H_0\)</span>, hogy <span class="math inline">\(X_j\)</span> hatása az eredményváltozóra csak egy mintavételi hiba, ha megfigyelnék új egyedeket (azaz új járásokat), akkor a mintában mért hatás megszűnne, azaz <span class="math inline">\(\beta_j\)</span> kinullázódna</strong>.</p>
<p>Ehhez a hipotézisvizsgálathoz kell nekünk a Globális F-próbánál látottak alapján egy próbafüggvény és p-érték is.</p>
<p>A próbafüggvényhez ad nekünk a Python egy <strong>standard mintavételi hibát, angolul standard errort</strong>. Ez van a <code>summary</code> metódus által kigenerált együtthatótábla 2. oszlopában:</p>
<div class="sourceCode" id="cb979"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb979-1"><a href="többváltozós-ols-regresszió-alapjai.html#cb979-1" tabindex="-1"></a><span class="bu">print</span>(sokvalt_modell.summary())</span></code></pre></div>
<pre><code>##                             OLS Regression Results                            
## ==============================================================================
## Dep. Variable:             COVIDHalal   R-squared:                       0.341
## Model:                            OLS   Adj. R-squared:                  0.321
## Method:                 Least Squares   F-statistic:                     16.89
## Date:                 H, 30 jún. 2025   Prob (F-statistic):           6.42e-09
## Time:                        15:22:29   Log-Likelihood:                -152.39
## No. Observations:                 102   AIC:                             312.8
## Df Residuals:                      98   BIC:                             323.3
## Df Model:                           3                                         
## Covariance Type:            nonrobust                                         
## ===================================================================================
##                       coef    std err          t      P&gt;|t|      [0.025      0.975]
## -----------------------------------------------------------------------------------
## const              -0.1542      0.937     -0.165      0.870      -2.015       1.706
## Apolok              0.0445      0.096      0.463      0.644      -0.146       0.235
## Munkanelkuliseg     0.0028      0.001      4.099      0.000       0.001       0.004
## Nok65Felett         0.2656      0.087      3.053      0.003       0.093       0.438
## ==============================================================================
## Omnibus:                       25.226   Durbin-Watson:                   1.957
## Prob(Omnibus):                  0.000   Jarque-Bera (JB):               36.179
## Skew:                           1.173   Prob(JB):                     1.39e-08
## Kurtosis:                       4.735   Cond. No.                     3.10e+03
## ==============================================================================
## 
## Notes:
## [1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
## [2] The condition number is large, 3.1e+03. This might indicate that there are
## strong multicollinearity or other numerical problems.</code></pre>
<p>Itt pl. a <span class="math inline">\(0.096\)</span> érték azt jelenti, hogy az <strong>Apolok</strong> bétája a mintában 0.04, de ez az érték a megfigyelt mintán kívül, új járásokra is futtatva a regressziót, ingadozhat a 0.04 körül, <em>várhatóan</em> +- 0.096-tal. A <span class="math inline">\(\beta_j\)</span> és standard hibájának (<span class="math inline">\(SH_j\)</span>) hányadosa lesz az ún. <em>t-érték = t value</em>, ami a parciális t-próba c. hipotézisvizsgálat próbafüggvénye. Az <strong>Apolok</strong> változó esetében ez 0.463</p>
<p>A próbafüggvény eloszlása sok-sok mintavételt vizsgálva igaz <span class="math inline">\(H_0\)</span> esetén t-eloszlású, aminek a pontos alakját egy darab szabadságfok szabályozza, ami most <span class="math inline">\(df=n-p=n-k-1\)</span>, ami a Globális F-próbában a 2. szabadságfok volt.</p>
<p>Itt <span class="math inline">\(H_0\)</span> szempontjából a legjobb eset, ha <span class="math inline">\(\beta_j=0\)</span> a mintában is, hiszen <span class="math inline">\(t=\frac{\beta_j}{SH_j}\)</span>. A t-eloszlás alakja miatt viszont így a p-értéket úgy kell számolni a 0 ponttól lefelé és felfelé vett eltérések esetén is csökkenjen a <span class="math inline">\(H_0\)</span> elutasításának hibavalószínűsége:</p>
<center>
<img src="pt.jpg" style="width:50.0%" />
</center>
<p><br>Így Pythonban a p-érték: <code>2*stats.t.cdf(-abs(0.0445/0.096), df = 102-4)</code><span class="math inline">\(= 0.644\)</span>. Ezt adja meg a <code>summary</code> metódus eredménytáblája a <code>P&gt;|t|</code> oszlopban.</p>
<p>A <code>P&gt;|t|</code> oszlopot nézegetve arra a kijelentésre juthatunk, hogy a COVID halálozásra a munkanélküliség és a 65 év feletti női népesség aránya is szignifikáns hatással van a <em>megfigyelt lakásokon kívüli világban is</em>, hiszen a parciális t-próba p-értéke az <span class="math inline">\(\alpha=1\%\)</span>-os szignifikancia-szintnél is kisebb. Azaz a <span class="math inline">\(H_0\)</span> elvetésével mindkét magyarázóváltozó esetén elég alacsony valószínűséggel hibáznék. Ez a <strong>Nok65Felett</strong> változó esetében azt jelenti, hogy az a közepes-gyenge közvetlen hatása az árakra, amit a parciális korreláció (+0.29) kimutatott megmarad új járások vizsgálata esetén is. Ugyanakkor, azt is látni, hogy az <strong>Apolok</strong> változóhoz rendelt p-érték jóval nagyobb, mint a <strong>Munkanelkuliseg</strong> és <strong>Nok65Felett</strong> változóké. Konkrétan <span class="math inline">\(64.4\%\)</span> a p-érték, ami olyan magas, hogy a legmagasabb szokásos <span class="math inline">\(\alpha\)</span>-nál, a <span class="math inline">\(10\%\)</span>-nál is nagyobb, így stabilan elfogadhatom a próba <span class="math inline">\(H_0\)</span>-ját! Tehát a parciális t-próba is azt mondja, hogy az <strong>Apolok</strong> változók hatása a COVID halálozásra a mintén kívüli filágban <strong>nem szignifikáns</strong>.</p>
<p>Végkonklúzióként, tehát azt vonhatjuk le a modellünk alapján, hogy az <strong>ápolók számának COVID halálozásra gyakorolt pozitív hatása a kétváltozós regresszióban látszólagos volt csupán, és a munkanélküliség valamint 65 feletti női népesség arányának COVID halálozást növelő hatásait közvetítette csak, és semmi önálló szignifikáns marginális hatása nem volt</strong>!</p>
<p>Ezek a változónkénti t-próba p-értékek azért nagyon jók, mert ezek alapján nagyon könnyű egy fontossági sorrendet felállítani a regressziónk magyarázóváltozói között. Az eddigiek alapján röviden-tömören: minél kisebb a parciális t-próba p-értéke, annál fontosabb az adott magyraázóváltozó az eredményváltozó előrejelezésében (annál kevésbé vehető marginális hatása <span class="math inline">\(0\)</span>-nak a sokaságban)</p>
</div>
</div>
<div id="magyarázóváltozók-fontossági-sorrendjének-megállapítása-t-próba-alapján" class="section level2 hasAnchor" number="13.4">
<h2><span class="header-section-number">13.4</span> Magyarázóváltozók fontossági sorrendjének megállapítása t-próba alapján<a href="többváltozós-ols-regresszió-alapjai.html#magyarázóváltozók-fontossági-sorrendjének-megállapítása-t-próba-alapján" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Vegyük elő újra a <a href="https://github.com/KoLa992/Kovetkezteto-Statisztika-Python-Jegyzet/blob/main/BP_Lakas.csv" target="_blank">BP_Lakas.csv</a> fájlt, és töltsük be újra egy <code>pandas</code> data frame-be, ahogy a <a href="https://kola992.github.io/Kovetkezteto-Statisztika-Python-Jegyzet/k%C3%A9tv%C3%A1ltoz%C3%B3s-line%C3%A1ris-regresszi%C3%B3.html" target="_blank">12. fejezet</a> elején is tettük!</p>
<p>Előtte egy kis emlékeztető az adattábla tartalmáról, változóiról. A tábla 1406 budapesti lakásról 10 ismérv/változó (oszlop) adatát tárolja:</p>
<ul>
<li>KinArMFt: lakás ára millió Ft-ban (MFt)</li>
<li>Terulet: lakás területe négyzetméterben</li>
<li>Terasz: teraszok száma a lakásban</li>
<li>Szoba: szobák száma a lakásban</li>
<li>Felszoba: félszobák száma a lakásban</li>
<li>Furdoszoba: fürdőszobák száma a lakásban</li>
<li>Emelet: emeletek száma a lakásban</li>
<li>DeliTaj: lakás déli fekvésű-e? (1 = igen; 0 = nem)</li>
<li>Buda: lakás déli fekvésű-e? (1 = igen; 0 = nem)</li>
<li>Kerulet: lakás kerülete (1 - 22)</li>
</ul>
<p>Majd a konkrét beolvasás:</p>
<div class="sourceCode" id="cb981"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb981-1"><a href="többváltozós-ols-regresszió-alapjai.html#cb981-1" tabindex="-1"></a>BP_Lakas <span class="op">=</span> pd.read_csv(<span class="st">&quot;BP_Lakas.csv&quot;</span>)</span>
<span id="cb981-2"><a href="többváltozós-ols-regresszió-alapjai.html#cb981-2" tabindex="-1"></a>BP_Lakas.info()</span></code></pre></div>
<pre><code>## &lt;class &#39;pandas.core.frame.DataFrame&#39;&gt;
## RangeIndex: 1406 entries, 0 to 1405
## Data columns (total 10 columns):
##  #   Column      Non-Null Count  Dtype  
## ---  ------      --------------  -----  
##  0   KinArMFt    1406 non-null   float64
##  1   Terulet     1406 non-null   float64
##  2   Terasz      1406 non-null   float64
##  3   Szoba       1406 non-null   int64  
##  4   Felszoba    1406 non-null   int64  
##  5   Furdoszoba  1406 non-null   int64  
##  6   Emelet      1406 non-null   int64  
##  7   DeliTaj     1406 non-null   int64  
##  8   Buda        1406 non-null   int64  
##  9   Kerulet     1406 non-null   int64  
## dtypes: float64(3), int64(7)
## memory usage: 110.0 KB</code></pre>
<p>Most nem szenvedünk az adattípusokkal, mindent hagyunk numerikusan.</p>
<p>Nézzünk most meg egy olyan modellt a lakásárak becslésére, amiben a <strong>BP_Lakas</strong> <code>data frame</code> minden változója szerepel magyarázóváltozóként a <strong>Kerulet</strong> kivételével:</p>
<div class="sourceCode" id="cb983"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb983-1"><a href="többváltozós-ols-regresszió-alapjai.html#cb983-1" tabindex="-1"></a><span class="co"># eredményváltozó megadása</span></span>
<span id="cb983-2"><a href="többváltozós-ols-regresszió-alapjai.html#cb983-2" tabindex="-1"></a>Y <span class="op">=</span> BP_Lakas.KinArMFt</span>
<span id="cb983-3"><a href="többváltozós-ols-regresszió-alapjai.html#cb983-3" tabindex="-1"></a></span>
<span id="cb983-4"><a href="többváltozós-ols-regresszió-alapjai.html#cb983-4" tabindex="-1"></a><span class="co"># magyarázóváltozók megadása a konstanshoz szükséges csupa 1 oszlop hozzáadásával</span></span>
<span id="cb983-5"><a href="többváltozós-ols-regresszió-alapjai.html#cb983-5" tabindex="-1"></a>X <span class="op">=</span> BP_Lakas.iloc[:,<span class="dv">1</span>:<span class="dv">9</span>]</span>
<span id="cb983-6"><a href="többváltozós-ols-regresszió-alapjai.html#cb983-6" tabindex="-1"></a>X <span class="op">=</span> sm.add_constant(X)</span>
<span id="cb983-7"><a href="többváltozós-ols-regresszió-alapjai.html#cb983-7" tabindex="-1"></a></span>
<span id="cb983-8"><a href="többváltozós-ols-regresszió-alapjai.html#cb983-8" tabindex="-1"></a><span class="co"># létrehozzuk az új regressziót</span></span>
<span id="cb983-9"><a href="többváltozós-ols-regresszió-alapjai.html#cb983-9" tabindex="-1"></a>nagymodell <span class="op">=</span> sm.OLS(Y, X).fit()</span>
<span id="cb983-10"><a href="többváltozós-ols-regresszió-alapjai.html#cb983-10" tabindex="-1"></a></span>
<span id="cb983-11"><a href="többváltozós-ols-regresszió-alapjai.html#cb983-11" tabindex="-1"></a><span class="co"># lássuk az eredménytáblát</span></span>
<span id="cb983-12"><a href="többváltozós-ols-regresszió-alapjai.html#cb983-12" tabindex="-1"></a><span class="bu">print</span>(nagymodell.summary())</span></code></pre></div>
<pre><code>##                             OLS Regression Results                            
## ==============================================================================
## Dep. Variable:               KinArMFt   R-squared:                       0.818
## Model:                            OLS   Adj. R-squared:                  0.817
## Method:                 Least Squares   F-statistic:                     783.3
## Date:                 H, 30 jún. 2025   Prob (F-statistic):               0.00
## Time:                        15:22:29   Log-Likelihood:                -4984.1
## No. Observations:                1406   AIC:                             9986.
## Df Residuals:                    1397   BIC:                         1.003e+04
## Df Model:                           8                                         
## Covariance Type:            nonrobust                                         
## ==============================================================================
##                  coef    std err          t      P&gt;|t|      [0.025      0.975]
## ------------------------------------------------------------------------------
## const         -9.0189      0.779    -11.580      0.000     -10.547      -7.491
## Terulet        0.2975      0.010     29.153      0.000       0.277       0.318
## Terasz         0.3105      0.021     15.022      0.000       0.270       0.351
## Szoba          0.6898      0.349      1.977      0.048       0.005       1.374
## Felszoba      -0.3851      0.406     -0.949      0.343      -1.181       0.411
## Furdoszoba     5.1301      0.682      7.526      0.000       3.793       6.467
## Emelet         0.0545      0.132      0.412      0.680      -0.205       0.314
## DeliTaj        1.1916      0.458      2.604      0.009       0.294       2.089
## Buda           6.2197      0.475     13.091      0.000       5.288       7.152
## ==============================================================================
## Omnibus:                      421.833   Durbin-Watson:                   1.271
## Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2922.930
## Skew:                           1.211   Prob(JB):                         0.00
## Kurtosis:                       9.635   Cond. No.                         363.
## ==============================================================================
## 
## Notes:
## [1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
<p>Látjuk, hogy a modell magyarázóereje a mintában 81.76%, azaz a modellben lévő magyarázóváltozók együttesen kb. 82%-ban magyarázzák a lakásárak alakulását a megfigyelt 1406 lakás esetében. Ha a többi egyéb változó hatását is kiszűrjük, akkor a szobaszám közvetlen hatása <span class="math inline">\(\alpha = 5\%\)</span>-on még éppen szignifikáns, de <span class="math inline">\(\alpha = 1\%\)</span>-on már nem! A félszobák száma és az emeletek száma pedig egyik szokásos <span class="math inline">\(\alpha\)</span>-n sem szignifikáns magyarázóváltozó már a megfigyelt lakásokon túli világban.</p>
<p>A magyarázóváltozók fontossági sorrendjét a változók p-értéke alapján növekvő sorba rendezéssel tudom megadni, mert minél kisebb a p-érték annál kisebb az esélye, hogy az adott <span class="math inline">\(X_j\)</span>-t nem szignifikáns magyarázóváltozónak venni hibás döntés.</p>
Ennek a folyamata egy kicsit macerás Pythonban. Először elmentjük a <code>summary</code> függvény eredményét egy külön Python változóba, és ennek a <code>tables</code> tulajdonságának a második (azaz 1. indexű) elemét olvasom ki egy következő külön változóba **html kódként, azaz
<table>
<p>tagekkel!!**<br>
Ezt utána arra tudom használni, hogy a <code>pandas</code> csomag <code>read_html</code> függvényével be tudom olvasni a regresszió nagy együtthatótábláját a p-értékekkel együtt egy <code>data frame</code>-be. Arra kell még figyelni, hogy a <em>html</em> tábla 0. indexű sora legyen a <code>read_html</code>-el beolvasott <code>data frame</code> sorindexe (<code>index_col</code> paraméter) és ugyan ezen tábla 0. indexű oszlopa pedig legyen ugyanitt az oszlopfejléc (<code>header</code> paraméter).<br>
Annyi technikai dologra kell még odafigyelni, hogy a <code>read_html</code> függvény egy egyelemű listaként adja vissza az eredményt, így ahhoz, hogy közvetlenül a <code>data frame</code>-t kapjuk vissza, ennek az eredménylistának a 0. indexű elemét külön ki kell venni <code>[0]</code> kódrészlettel a végén.<br>
Lássuk is hát a konkrét Python kódokat és az eredményül kapott <code>data frame</code>-et!</p>
<div class="sourceCode" id="cb985"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb985-1"><a href="többváltozós-ols-regresszió-alapjai.html#cb985-1" tabindex="-1"></a>BetaTablaHTML <span class="op">=</span> nagymodell.summary().tables[<span class="dv">1</span>].as_html()</span>
<span id="cb985-2"><a href="többváltozós-ols-regresszió-alapjai.html#cb985-2" tabindex="-1"></a>BetaTabla_df <span class="op">=</span> pd.read_html(BetaTablaHTML, header<span class="op">=</span><span class="dv">0</span>, index_col<span class="op">=</span><span class="dv">0</span>)[<span class="dv">0</span>]</span></code></pre></div>
<pre><code>## &lt;string&gt;:1: FutureWarning: Passing literal html to &#39;read_html&#39; is deprecated and will be removed in a future version. To read from a literal string, wrap it in a &#39;StringIO&#39; object.</code></pre>
<div class="sourceCode" id="cb987"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb987-1"><a href="többváltozós-ols-regresszió-alapjai.html#cb987-1" tabindex="-1"></a>BetaTabla_df</span></code></pre></div>
<pre><code>##               coef  std err       t  P&gt;|t|  [0.025  0.975]
## const      -9.0189    0.779 -11.580  0.000 -10.547  -7.491
## Terulet     0.2975    0.010  29.153  0.000   0.277   0.318
## Terasz      0.3105    0.021  15.022  0.000   0.270   0.351
## Szoba       0.6898    0.349   1.977  0.048   0.005   1.374
## Felszoba   -0.3851    0.406  -0.949  0.343  -1.181   0.411
## Furdoszoba  5.1301    0.682   7.526  0.000   3.793   6.467
## Emelet      0.0545    0.132   0.412  0.680  -0.205   0.314
## DeliTaj     1.1916    0.458   2.604  0.009   0.294   2.089
## Buda        6.2197    0.475  13.091  0.000   5.288   7.152</code></pre>
<p>Ha megvan a <code>data frame</code>, akkor pedig rendezzük növekvő sorrendbe a 4. (3. indexű) oszlop, azaz a <span class="math inline">\(\beta_j\)</span> együtthatók <strong>p-értékei</strong> szerint. Előtte a tengelymetszet (<span class="math inline">\(\beta_0\)</span>) sorát, a <code>const</code>-t kihagyjuk a <code>data frame</code>-ből, mert ugyebár az nem egy magyarázóváltozó együtthatója a regressziós egyenletben.</p>
<div class="sourceCode" id="cb989"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb989-1"><a href="többváltozós-ols-regresszió-alapjai.html#cb989-1" tabindex="-1"></a>BetaTabla_df.iloc[<span class="dv">1</span>:<span class="dv">9</span>,:].sort_values(by<span class="op">=</span>BetaTabla_df.columns[<span class="dv">3</span>])</span></code></pre></div>
<pre><code>##               coef  std err       t  P&gt;|t|  [0.025  0.975]
## Terulet     0.2975    0.010  29.153  0.000   0.277   0.318
## Terasz      0.3105    0.021  15.022  0.000   0.270   0.351
## Furdoszoba  5.1301    0.682   7.526  0.000   3.793   6.467
## Buda        6.2197    0.475  13.091  0.000   5.288   7.152
## DeliTaj     1.1916    0.458   2.604  0.009   0.294   2.089
## Szoba       0.6898    0.349   1.977  0.048   0.005   1.374
## Felszoba   -0.3851    0.406  -0.949  0.343  -1.181   0.411
## Emelet      0.0545    0.132   0.412  0.680  -0.205   0.314</code></pre>
<p>Láthatjuk, hogy a Terület a legfontosabb magyarázóváltozó, míg a pl. szobák száma a <em>3. legkevésbé fontos</em> magyarázóváltozó.</p>
</div>
<div id="konfidencia-intervallumok-és-a-t-próba-kapcsolata" class="section level2 hasAnchor" number="13.5">
<h2><span class="header-section-number">13.5</span> 5. Konfidencia-intervallumok és a t-próba kapcsolata<a href="többváltozós-ols-regresszió-alapjai.html#konfidencia-intervallumok-és-a-t-próba-kapcsolata" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A többváltozós regressziós modell együtthatóira (béták) is lehet egy adott megbízhatósági szintű konfidencia-intervallumot is készíteni Pythonban a regressziós modellek <code>confint</code> metódusának segítségével.<br>
Pl. <strong>egy 97% megbízhatóságú konfidencia-intervallum <span class="math inline">\(\beta_j\)</span>-re azt adja meg, hogy 97%-os valószínűséggel milyen értékhatárok között mozoghat <span class="math inline">\(\beta_j\)</span> együttható a megfyigelt lakásokon túli világban</strong>.</p>
<p>Nézzük is meg a Python számítást:</p>
<div class="sourceCode" id="cb991"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb991-1"><a href="többváltozós-ols-regresszió-alapjai.html#cb991-1" tabindex="-1"></a>nagymodell.conf_int() <span class="co"># alapból 95%-os megbízhatóságú</span></span></code></pre></div>
<pre><code>##                     0         1
## const      -10.546693 -7.491181
## Terulet      0.277475  0.317511
## Terasz       0.269945  0.351035
## Szoba        0.005311  1.374306
## Felszoba    -1.180769  0.410579
## Furdoszoba   3.792974  6.467229
## Emelet      -0.204826  0.313728
## DeliTaj      0.293935  2.089167
## Buda         5.287680  7.151671</code></pre>
<div class="sourceCode" id="cb993"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb993-1"><a href="többváltozós-ols-regresszió-alapjai.html#cb993-1" tabindex="-1"></a>nagymodell.conf_int(alpha <span class="op">=</span> <span class="fl">0.03</span>) <span class="co"># de lehet pl. 97%-os is (alfa = 1-0.97)</span></span></code></pre></div>
<pre><code>##                     0         1
## const      -10.710745 -7.327129
## Terulet      0.275325  0.319660
## Terasz       0.265591  0.355389
## Szoba       -0.068191  1.447808
## Felszoba    -1.266210  0.496020
## Furdoszoba   3.649391  6.610811
## Emelet      -0.232668  0.341570
## DeliTaj      0.197548  2.185555
## Buda         5.187601  7.251750</code></pre>
<p>Pl. az első eredménytábla alapján a <strong>Terulet</strong> változó <span class="math inline">\(\beta\)</span>-ja 95%-os valószínűséggel 0.277 és 0.317 között kötne ki valahol, ha nem 1406 budapesti lakást vizsgálnánk, hanem az össeset (azaz a lakások sokaságát).</p>
<p>Az eredményből megjelenik egy olyan összefüggés is, miszerint, <strong>ha egy <span class="math inline">\(X_j\)</span> nem szignifikáns <span class="math inline">\(\alpha\)</span> szignifikancia-szinten, akkor az <span class="math inline">\(1-\alpha\)</span> megbízhatóságú konfidencia-intervallumának határai előjelet váltanak</strong>.<br>
legjobb példa a <strong>Szoba</strong> változó esete: azt mondtuk rá, hogy hatása az árakra 5%-on még épp szignifikáns -&gt; a 95%-os megbízhatóságú intervalluma még épp nem vált előjelet. Viszont a változó 3%-on már nem szignifikáns, így az intervalluma előjelet vált.</p>
<p>Ezzel egy érdekes nézőponthoz jutottunk: <em>ha egy <span class="math inline">\(X_j\)</span> változó nem szignifikáns <span class="math inline">\(\alpha\)</span>-n az azt jelenti, hogy <span class="math inline">\(1-\alpha\)</span> megbízhatósági szinten azt sem tudom eldönteni, hogy minden más változatlansága mellett +1 egység <span class="math inline">\(X_j\)</span> növeli vagy csökkenti-e az eredmányváltozót a mintán kívüli világban</em>.</p>
<p>A háttérben amúgy annyi történik, hogy a Python kiszámolja a parciális t-próba esetén is alkalmazott <span class="math inline">\(n-p=n-k-1\)</span> szabadságfokú t-eloszlás inverz értékét <span class="math inline">\(1-\alpha/2\)</span> valószínűség mellett, és az ezzel beszorzott standard hibát adja hozzá és vonja le <span class="math inline">\(\forall \beta_j\)</span>-ből:</p>
<div class="sourceCode" id="cb995"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb995-1"><a href="többváltozós-ols-regresszió-alapjai.html#cb995-1" tabindex="-1"></a>BetaTabla_df</span></code></pre></div>
<pre><code>##               coef  std err       t  P&gt;|t|  [0.025  0.975]
## const      -9.0189    0.779 -11.580  0.000 -10.547  -7.491
## Terulet     0.2975    0.010  29.153  0.000   0.277   0.318
## Terasz      0.3105    0.021  15.022  0.000   0.270   0.351
## Szoba       0.6898    0.349   1.977  0.048   0.005   1.374
## Felszoba   -0.3851    0.406  -0.949  0.343  -1.181   0.411
## Furdoszoba  5.1301    0.682   7.526  0.000   3.793   6.467
## Emelet      0.0545    0.132   0.412  0.680  -0.205   0.314
## DeliTaj     1.1916    0.458   2.604  0.009   0.294   2.089
## Buda        6.2197    0.475  13.091  0.000   5.288   7.152</code></pre>
<div class="sourceCode" id="cb997"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb997-1"><a href="többváltozós-ols-regresszió-alapjai.html#cb997-1" tabindex="-1"></a>alfa <span class="op">=</span> <span class="fl">0.02</span></span>
<span id="cb997-2"><a href="többváltozós-ols-regresszió-alapjai.html#cb997-2" tabindex="-1"></a>p <span class="op">=</span> <span class="bu">len</span>(BetaTabla_df) <span class="co"># így a tengelymetszetet is beszámítjuk p-be</span></span>
<span id="cb997-3"><a href="többváltozós-ols-regresszió-alapjai.html#cb997-3" tabindex="-1"></a>n <span class="op">=</span> <span class="bu">len</span>(BP_Lakas) <span class="co"># mintaelemszám</span></span>
<span id="cb997-4"><a href="többváltozós-ols-regresszió-alapjai.html#cb997-4" tabindex="-1"></a>szorzo <span class="op">=</span> stats.t.ppf(<span class="dv">1</span><span class="op">-</span>alfa<span class="op">/</span><span class="dv">2</span>, df <span class="op">=</span> n<span class="op">-</span>p)</span>
<span id="cb997-5"><a href="többváltozós-ols-regresszió-alapjai.html#cb997-5" tabindex="-1"></a></span>
<span id="cb997-6"><a href="többváltozós-ols-regresszió-alapjai.html#cb997-6" tabindex="-1"></a>Terulet_AH <span class="op">=</span> BetaTabla_df.iloc[<span class="dv">1</span>,<span class="dv">0</span>] <span class="op">-</span> szorzo <span class="op">*</span> BetaTabla_df.iloc[<span class="dv">1</span>,<span class="dv">1</span>] <span class="co"># Terulet 98% alsó határ</span></span>
<span id="cb997-7"><a href="többváltozós-ols-regresszió-alapjai.html#cb997-7" tabindex="-1"></a>Terulet_FH <span class="op">=</span> BetaTabla_df.iloc[<span class="dv">1</span>,<span class="dv">0</span>] <span class="op">+</span> szorzo <span class="op">*</span> BetaTabla_df.iloc[<span class="dv">1</span>,<span class="dv">1</span>] <span class="co"># Terulet 98% felső határ</span></span>
<span id="cb997-8"><a href="többváltozós-ols-regresszió-alapjai.html#cb997-8" tabindex="-1"></a><span class="bu">print</span>([Terulet_AH, Terulet_FH])</span></code></pre></div>
<pre><code>## [0.2742097984822436, 0.3207902015177564]</code></pre>
<p>Formális képlettel leírva a műveletet:</p>
<center>
<img src="BetaCI.jpg" style="width:50.0%" />
</center>
</div>
<div id="nominális-magyarázóváltozók---használtautó-adatok" class="section level2 hasAnchor" number="13.6">
<h2><span class="header-section-number">13.6</span> Nominális magyarázóváltozók - Használtautó adatok<a href="többváltozós-ols-regresszió-alapjai.html#nominális-magyarázóváltozók---használtautó-adatok" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Most egy új, <a href="https://github.com/KoLa992/Kovetkezteto-Statisztika-Python-Jegyzet/blob/main/auto.xlsx" target="_blank">auto.xlsx</a> fájlból fogunk dolgozni, ami 100 db használtautóról tartalmaz 8 változót:</p>
<ul>
<li>Vetelar: Vételár Ft-ban</li>
<li>Kor: Az autó kora években</li>
<li>Kilometerora: A kilóméteróra állása</li>
<li>Teljes_tomeg: Az autó tömege kg-ban</li>
<li>Hengerurtartalom: Hengerűrtartalom <em>ccm</em>-ben (köbcenti)</li>
<li>Teljesitmeny: A motor teljesítménye Kw/h-ban</li>
<li>Allapot: Az autó állapota szöveges minősítéssel</li>
<li>Uzemanyag: Üzemanyag típusa (benzin/dízel)</li>
</ul>
<p>Láthatjuk, hogy ez nem <em>csv</em>, hanem Excel, azaz <em>xlsx</em> fájl. Úgyhogy olvassuk is be egy pandas <code>data frame</code>-be!</p>
<div class="sourceCode" id="cb999"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb999-1"><a href="többváltozós-ols-regresszió-alapjai.html#cb999-1" tabindex="-1"></a>autok <span class="op">=</span> pd.read_excel(<span class="st">&quot;auto.xlsx&quot;</span>)</span>
<span id="cb999-2"><a href="többváltozós-ols-regresszió-alapjai.html#cb999-2" tabindex="-1"></a>autok.info()</span></code></pre></div>
<pre><code>## &lt;class &#39;pandas.core.frame.DataFrame&#39;&gt;
## RangeIndex: 100 entries, 0 to 99
## Data columns (total 8 columns):
##  #   Column            Non-Null Count  Dtype 
## ---  ------            --------------  ----- 
##  0   Vetelar           100 non-null    int64 
##  1   Kor               100 non-null    int64 
##  2   Kilometerora      100 non-null    int64 
##  3   Teljes_tomeg      100 non-null    int64 
##  4   Hengerurtartalom  100 non-null    int64 
##  5   Teljesitmeny      100 non-null    int64 
##  6   Allapot           100 non-null    object
##  7   Uzemanyag         100 non-null    object
## dtypes: int64(6), object(2)
## memory usage: 6.4+ KB</code></pre>
<p>Minden szupinak néz ki! Megvan mind a 100 megfigyelési egység és a 8 db változó.</p>
<p>Vessünk még egy pillantást arra, hogy az <strong>Allapot</strong> változónak milyen lehetséges értékei vannak:</p>
<div class="sourceCode" id="cb1001"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb1001-1"><a href="többváltozós-ols-regresszió-alapjai.html#cb1001-1" tabindex="-1"></a>autok.Allapot.unique()</span></code></pre></div>
<pre><code>## array([&#39;Normal&#39;, &#39;Kituno&#39;, &#39;Megkimelt&#39;, &#39;Serulesmentes&#39;, &#39;Ujszeru&#39;],
##       dtype=object)</code></pre>
</div>
<div id="dummy-változók-és-működésük-pythonban" class="section level2 hasAnchor" number="13.7">
<h2><span class="header-section-number">13.7</span> Dummy változók és működésük Pythonban<a href="többváltozós-ols-regresszió-alapjai.html#dummy-változók-és-működésük-pythonban" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>No, ha egy sima OLS regresszióba magyarázóváltozóként nominális változót akarunk bevenni, mint amilyen jelen példánkban az <strong>Allapot</strong> vagy az <strong>Uzemanyag</strong>, akkor az R az úgynevezett <strong>dummy-kódolást</strong> veti be. A nominális változó lehetséges értékeiből kiválaszt egyet, mint <strong>referencia kategória</strong>, azt “<em>elteszi</em>”, és a maradéknak pedig csinál külön-külön egy <em>bináris = dummy</em> változót, aminek értéke 1, ha a megfigyelés a vizsgált szöveges változóban épp a dummy változónak megfelelő értéket vesz fel, egyébként 0:</p>
<center>
<img src="Dummy.jpg" style="width:50.0%" />
</center>
<p>A fenti táblázatban az <span class="math inline">\(R_A\)</span> és <span class="math inline">\(R_B\)</span> lennének a regresszióban használt dummy változók, és a referencia kategória a <span class="math inline">\(C\)</span> érték. Ezt a <span class="math inline">\(C\)</span> kategóriát azért nem szabad a modellben szerepeltetni, mert egyértelmű, hogy ha <span class="math inline">\(D_A=0\)</span> és <span class="math inline">\(D_B=0\)</span>, akkor <span class="math inline">\(D_C=1\)</span>. Ezzel egy teljesen redundáns magyarázóváltozót raknánk a modellbe, amitől az egész rendszer megdöglik, mert a <span class="math inline">\(\beta\)</span>-k becslése során alkalmazott <span class="math inline">\(\beta=(X^TX)^{-1}X^Ty\)</span> képletben az <span class="math inline">\((X^TX)^{-1}\)</span> inverzet nem lehet elvégezni, ha <span class="math inline">\(X\)</span> mátrix oszlopai olyanok, hogy az egyiket hibátlanul elő lehet állítani a többiből. Ez a jelenség az <strong>egzakt multikollinearitás</strong> nevet kapta a keresztségben.</p>
<p>Ezekkel a megfontolásokkal lássunk is neki a dummy változóink legyártásához a két nominális változónk (<strong>Uzemanyag</strong> és <strong>Allapot</strong>) esetében!<br>
Először a <code>pandas</code> csomag <code>get_dummies</code> függvényével létrehozzuk a két szöveges változó minden kategóriájához a megfelelő 0/1, azaz dummy változókat. A függvény első paramétere az érintett változókat tartalmazó <code>data frame</code>, a második (<code>columns</code>) azon oszlopnevek listája, amelyekből dummy változókat akarunk csinálni, még az utolsó, <code>dtype</code> paraméterben a dummy változók adattípusát lehet megadni. Ez utolsó paraméter azért szükséges, mert egy dummy változó logikusan lehet akár <code>bool</code> adattípusú, de ad abszurdum <code>int</code> is. Most mi ez utóbbi opcióval megyünk, mert a <code>statsmodels</code> csomag nem tud <code>bool</code> típusú váltizókkal dolgozni.</p>
<div class="sourceCode" id="cb1003"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb1003-1"><a href="többváltozós-ols-regresszió-alapjai.html#cb1003-1" tabindex="-1"></a>autok_dummy <span class="op">=</span> pd.get_dummies(autok, columns<span class="op">=</span>[<span class="st">&#39;Uzemanyag&#39;</span>, <span class="st">&#39;Allapot&#39;</span>], dtype<span class="op">=</span><span class="bu">int</span>)</span>
<span id="cb1003-2"><a href="többváltozós-ols-regresszió-alapjai.html#cb1003-2" tabindex="-1"></a>autok_dummy.info()</span></code></pre></div>
<pre><code>## &lt;class &#39;pandas.core.frame.DataFrame&#39;&gt;
## RangeIndex: 100 entries, 0 to 99
## Data columns (total 13 columns):
##  #   Column                 Non-Null Count  Dtype
## ---  ------                 --------------  -----
##  0   Vetelar                100 non-null    int64
##  1   Kor                    100 non-null    int64
##  2   Kilometerora           100 non-null    int64
##  3   Teljes_tomeg           100 non-null    int64
##  4   Hengerurtartalom       100 non-null    int64
##  5   Teljesitmeny           100 non-null    int64
##  6   Uzemanyag_Benzin       100 non-null    int32
##  7   Uzemanyag_Dizel        100 non-null    int32
##  8   Allapot_Kituno         100 non-null    int32
##  9   Allapot_Megkimelt      100 non-null    int32
##  10  Allapot_Normal         100 non-null    int32
##  11  Allapot_Serulesmentes  100 non-null    int32
##  12  Allapot_Ujszeru        100 non-null    int32
## dtypes: int32(7), int64(6)
## memory usage: 7.6 KB</code></pre>
<p>Szuper, megvan minden szükséges új változó, és a megfelelő, azaz <code>int</code> adattípuson is vannak!</p>
<p>Ezek után lássunk hozzá a regressziós modell legyártásához, amely az autók vételárát magyarázza az összes többi változóval a táblában. Arra kell figyelni, hogy a magyarázóváltozók (<span class="math inline">\(X\)</span> mátrix) kijelölésénél ne válasszuk ki a két nominális változó refrencia kategóriáinak oszlopait. Legyen most az <strong>Uzemanyag</strong> változó esetén a kihagyott refrencia kategória a <em>Benzin</em> (6. oszlopindex), míg <strong>Allapot</strong> esetén a <em>Kituno</em> (8. oszlopindex).</p>
<div class="sourceCode" id="cb1005"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb1005-1"><a href="többváltozós-ols-regresszió-alapjai.html#cb1005-1" tabindex="-1"></a>Y <span class="op">=</span> autok_dummy.Vetelar</span>
<span id="cb1005-2"><a href="többváltozós-ols-regresszió-alapjai.html#cb1005-2" tabindex="-1"></a>X <span class="op">=</span> autok_dummy.iloc[:,[<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">7</span>,<span class="dv">9</span>,<span class="dv">10</span>,<span class="dv">11</span>,<span class="dv">12</span>]] <span class="co"># megfelelő oszlopindexek kiválasztása</span></span>
<span id="cb1005-3"><a href="többváltozós-ols-regresszió-alapjai.html#cb1005-3" tabindex="-1"></a>X <span class="op">=</span> sm.add_constant(X)</span>
<span id="cb1005-4"><a href="többváltozós-ols-regresszió-alapjai.html#cb1005-4" tabindex="-1"></a></span>
<span id="cb1005-5"><a href="többváltozós-ols-regresszió-alapjai.html#cb1005-5" tabindex="-1"></a><span class="co"># létrehozzuk az új regressziót</span></span>
<span id="cb1005-6"><a href="többváltozós-ols-regresszió-alapjai.html#cb1005-6" tabindex="-1"></a>autos_modell <span class="op">=</span> sm.OLS(Y, X).fit()</span>
<span id="cb1005-7"><a href="többváltozós-ols-regresszió-alapjai.html#cb1005-7" tabindex="-1"></a></span>
<span id="cb1005-8"><a href="többváltozós-ols-regresszió-alapjai.html#cb1005-8" tabindex="-1"></a><span class="co"># lássuk az eredménytáblát</span></span>
<span id="cb1005-9"><a href="többváltozós-ols-regresszió-alapjai.html#cb1005-9" tabindex="-1"></a><span class="bu">print</span>(autos_modell.summary())</span></code></pre></div>
<pre><code>##                             OLS Regression Results                            
## ==============================================================================
## Dep. Variable:                Vetelar   R-squared:                       0.728
## Model:                            OLS   Adj. R-squared:                  0.697
## Method:                 Least Squares   F-statistic:                     23.81
## Date:                 H, 30 jún. 2025   Prob (F-statistic):           4.10e-21
## Time:                        15:22:30   Log-Likelihood:                -1345.2
## No. Observations:                 100   AIC:                             2712.
## Df Residuals:                      89   BIC:                             2741.
## Df Model:                          10                                         
## Covariance Type:            nonrobust                                         
## =========================================================================================
##                             coef    std err          t      P&gt;|t|      [0.025      0.975]
## -----------------------------------------------------------------------------------------
## const                  2.323e+06   6.15e+05      3.777      0.000     1.1e+06    3.55e+06
## Kor                   -7.273e+04   9353.425     -7.776      0.000   -9.13e+04   -5.41e+04
## Kilometerora             -2.4542      0.362     -6.784      0.000      -3.173      -1.735
## Teljes_tomeg           -164.4405    371.805     -0.442      0.659    -903.210     574.329
## Hengerurtartalom         42.0239    160.600      0.262      0.794    -277.084     361.132
## Teljesitmeny           4647.0879   1600.722      2.903      0.005    1466.488    7827.688
## Uzemanyag_Dizel       -3.763e+04   4.67e+04     -0.806      0.422    -1.3e+05    5.51e+04
## Allapot_Megkimelt      4.186e+04   5.08e+04      0.824      0.412   -5.91e+04    1.43e+05
## Allapot_Normal        -1.192e+05   4.95e+04     -2.411      0.018   -2.18e+05    -2.1e+04
## Allapot_Serulesmentes -9418.8363   1.13e+05     -0.084      0.934   -2.33e+05    2.15e+05
## Allapot_Ujszeru        2.266e+05   1.14e+05      1.980      0.051    -742.588    4.54e+05
## ==============================================================================
## Omnibus:                        8.736   Durbin-Watson:                   1.598
## Prob(Omnibus):                  0.013   Jarque-Bera (JB):                8.434
## Skew:                          -0.646   Prob(JB):                       0.0147
## Kurtosis:                       3.597   Cond. No.                     6.58e+06
## ==============================================================================
## 
## Notes:
## [1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
## [2] The condition number is large, 6.58e+06. This might indicate that there are
## strong multicollinearity or other numerical problems.</code></pre>
<p>Úgy néz ki rendben vagyunk, a magyarázóváltozók együttesen <span class="math inline">\(72.8\%\)</span>-ban magyraázzák az autók vételárának alakulását.</p>
<p>Nézzük meg a nominális magyarázóváltozókhoz köthető dummy változók <span class="math inline">\(\beta_j\)</span> együtthatóinak értelmezését! Az eddigi okoskodásaink alapján alapján az egyes együtthatók értelmezése mindig a <strong>referencia kategóriához</strong> képest értednő:</p>
<ul>
<li><span class="math inline">\(\beta_{Dizel}=-37630\)</span>: Minden más magyarázóváltozó változatlansága mellett egy dízelautó várhatóan 37630 Ft-al lesz olcsóbb, mint egy <em>benzines</em>.</li>
<li><span class="math inline">\(\beta_{Normal}=-119200\)</span>: Minden más magyarázóváltozó változatlansága mellett egy normál állapotú autó várhatóan kb. 119 200 Ft-tal lesz olcsóbb, mint egy <em>kitűnő</em> állapotban lévő.</li>
</ul>
<div id="referencia-kategória-megváltoztatása" class="section level3 hasAnchor" number="13.7.1">
<h3><span class="header-section-number">13.7.1</span> Referencia kategória megváltoztatása<a href="többváltozós-ols-regresszió-alapjai.html#referencia-kategória-megváltoztatása" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Az előző modellben nem feltétlenül a legszerencsésebb az, ha a <em>Kituno</em> a referencia kategória az <strong>Allapot</strong> változóban. Logikusabb lenne a <em>Normal</em> állapotot referenciának venni. A módosítást simán meg tudjuk tenni. Egyszerűen az <span class="math inline">\(X\)</span> mátixból a 10. oszlopindexet hagyom ki a 8. helyett, és így újrafuttatom a modellt.</p>
<p>Alapvetően a <code>levels</code> függvény eredményéből látható, hogy a referencia kategória az <strong>Allapot</strong> változóban azért a volt a <em>Kituno</em>, mert az van betűrend szerint a legelöl az <strong>Allapot</strong> változó lehetséges értékei közül:</p>
<div class="sourceCode" id="cb1007"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb1007-1"><a href="többváltozós-ols-regresszió-alapjai.html#cb1007-1" tabindex="-1"></a>X <span class="op">=</span> autok_dummy.iloc[:,[<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">7</span>,<span class="dv">8</span>,<span class="dv">9</span>,<span class="dv">11</span>,<span class="dv">12</span>]] <span class="co"># megfelelő oszlopindexek kiválasztása</span></span>
<span id="cb1007-2"><a href="többváltozós-ols-regresszió-alapjai.html#cb1007-2" tabindex="-1"></a>X <span class="op">=</span> sm.add_constant(X)</span>
<span id="cb1007-3"><a href="többváltozós-ols-regresszió-alapjai.html#cb1007-3" tabindex="-1"></a></span>
<span id="cb1007-4"><a href="többváltozós-ols-regresszió-alapjai.html#cb1007-4" tabindex="-1"></a><span class="co"># újra lefuttatjuk a regressziót</span></span>
<span id="cb1007-5"><a href="többváltozós-ols-regresszió-alapjai.html#cb1007-5" tabindex="-1"></a>autos_modell <span class="op">=</span> sm.OLS(Y, X).fit()</span>
<span id="cb1007-6"><a href="többváltozós-ols-regresszió-alapjai.html#cb1007-6" tabindex="-1"></a></span>
<span id="cb1007-7"><a href="többváltozós-ols-regresszió-alapjai.html#cb1007-7" tabindex="-1"></a><span class="co"># lássuk az eredménytáblát</span></span>
<span id="cb1007-8"><a href="többváltozós-ols-regresszió-alapjai.html#cb1007-8" tabindex="-1"></a><span class="bu">print</span>(autos_modell.summary())</span></code></pre></div>
<pre><code>##                             OLS Regression Results                            
## ==============================================================================
## Dep. Variable:                Vetelar   R-squared:                       0.728
## Model:                            OLS   Adj. R-squared:                  0.697
## Method:                 Least Squares   F-statistic:                     23.81
## Date:                 H, 30 jún. 2025   Prob (F-statistic):           4.10e-21
## Time:                        15:22:30   Log-Likelihood:                -1345.2
## No. Observations:                 100   AIC:                             2712.
## Df Residuals:                      89   BIC:                             2741.
## Df Model:                          10                                         
## Covariance Type:            nonrobust                                         
## =========================================================================================
##                             coef    std err          t      P&gt;|t|      [0.025      0.975]
## -----------------------------------------------------------------------------------------
## const                  2.204e+06   6.08e+05      3.626      0.000    9.96e+05    3.41e+06
## Kor                   -7.273e+04   9353.425     -7.776      0.000   -9.13e+04   -5.41e+04
## Kilometerora             -2.4542      0.362     -6.784      0.000      -3.173      -1.735
## Teljes_tomeg           -164.4405    371.805     -0.442      0.659    -903.210     574.329
## Hengerurtartalom         42.0239    160.600      0.262      0.794    -277.084     361.132
## Teljesitmeny           4647.0879   1600.722      2.903      0.005    1466.488    7827.688
## Uzemanyag_Dizel       -3.763e+04   4.67e+04     -0.806      0.422    -1.3e+05    5.51e+04
## Allapot_Kituno         1.192e+05   4.95e+04      2.411      0.018     2.1e+04    2.18e+05
## Allapot_Megkimelt      1.611e+05   4.35e+04      3.704      0.000    7.47e+04    2.48e+05
## Allapot_Serulesmentes  1.098e+05   1.09e+05      1.007      0.317   -1.07e+05    3.27e+05
## Allapot_Ujszeru        3.458e+05   1.15e+05      3.015      0.003    1.18e+05    5.74e+05
## ==============================================================================
## Omnibus:                        8.736   Durbin-Watson:                   1.598
## Prob(Omnibus):                  0.013   Jarque-Bera (JB):                8.434
## Skew:                          -0.646   Prob(JB):                       0.0147
## Kurtosis:                       3.597   Cond. No.                     6.50e+06
## ==============================================================================
## 
## Notes:
## [1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
## [2] The condition number is large, 6.5e+06. This might indicate that there are
## strong multicollinearity or other numerical problems.</code></pre>
<p>Így már azt mondhatom, hogy egy kitűnő állapotban lévő autó várhatóan <span class="math inline">\(\beta_{Kituno}=+119200\)</span> Ft-tal kerül többe egy normál állapotú autónál minden egyéb változó változatlansága mellett. Teljesen logikus módon abszolút értékben ugyan akkora a hatás az árakra, mint az előző modellben, ahol a <em>Kituno</em> vot a referencia kategória és <span class="math inline">\(\beta_{Normal}=-119200\)</span>-t viszgáltuk, csak ellentétes előjelű.</p>
</div>
</div>
<div id="a-korrigált-r-négyzet-mutató" class="section level2 hasAnchor" number="13.8">
<h2><span class="header-section-number">13.8</span> A korrigált R-négyzet mutató<a href="többváltozós-ols-regresszió-alapjai.html#a-korrigált-r-négyzet-mutató" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Az előző fejezet végi modell eredménytáblázatát elnézegetve azt láthatjuk, hogy a modell két legkevésbé fontos, azaz legmagasabb p-értékű magyarázóváltozója a <strong>Hengerurtartalom</strong> és a <strong>Teljes_tomeg</strong>. Ha ezeknek a változóknak tényleg nincs közük az autók vételárához, akkor egy logikus gondolat, hogy potyogtassuk is ki őket a modellünkből! Ha emlékszünk még az <code>autok_dummy</code> táblára, akkor tudhatjuk, hogy ez a két változó rendre a 4. és 3. oszlopindexen futott, szóval csak ezeket az oszlopokat kell kiszedni az <span class="math inline">\(X\)</span> mátrixból, és már meg is szabadultunk ezektől a azvaró tényezőktől.</p>
<div class="sourceCode" id="cb1009"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb1009-1"><a href="többváltozós-ols-regresszió-alapjai.html#cb1009-1" tabindex="-1"></a>X_szuk <span class="op">=</span> autok_dummy.iloc[:,[<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">5</span>,<span class="dv">7</span>,<span class="dv">8</span>,<span class="dv">9</span>,<span class="dv">11</span>,<span class="dv">12</span>]] <span class="co"># megfelelő oszlopindexek kiválasztása</span></span>
<span id="cb1009-2"><a href="többváltozós-ols-regresszió-alapjai.html#cb1009-2" tabindex="-1"></a>X_szuk <span class="op">=</span> sm.add_constant(X_szuk)</span>
<span id="cb1009-3"><a href="többváltozós-ols-regresszió-alapjai.html#cb1009-3" tabindex="-1"></a></span>
<span id="cb1009-4"><a href="többváltozós-ols-regresszió-alapjai.html#cb1009-4" tabindex="-1"></a><span class="co"># újra lefuttatjuk a regressziót</span></span>
<span id="cb1009-5"><a href="többváltozós-ols-regresszió-alapjai.html#cb1009-5" tabindex="-1"></a>autos_modell_szuk <span class="op">=</span> sm.OLS(Y, X_szuk).fit()</span>
<span id="cb1009-6"><a href="többváltozós-ols-regresszió-alapjai.html#cb1009-6" tabindex="-1"></a></span>
<span id="cb1009-7"><a href="többváltozós-ols-regresszió-alapjai.html#cb1009-7" tabindex="-1"></a><span class="co"># lássuk az eredménytáblát</span></span>
<span id="cb1009-8"><a href="többváltozós-ols-regresszió-alapjai.html#cb1009-8" tabindex="-1"></a><span class="bu">print</span>(autos_modell_szuk.summary())</span></code></pre></div>
<pre><code>##                             OLS Regression Results                            
## ==============================================================================
## Dep. Variable:                Vetelar   R-squared:                       0.727
## Model:                            OLS   Adj. R-squared:                  0.703
## Method:                 Least Squares   F-statistic:                     30.33
## Date:                 H, 30 jún. 2025   Prob (F-statistic):           1.50e-22
## Time:                        15:22:31   Log-Likelihood:                -1345.4
## No. Observations:                 100   AIC:                             2709.
## Df Residuals:                      91   BIC:                             2732.
## Df Model:                           8                                         
## Covariance Type:            nonrobust                                         
## =========================================================================================
##                             coef    std err          t      P&gt;|t|      [0.025      0.975]
## -----------------------------------------------------------------------------------------
## const                  1.968e+06   1.79e+05     10.982      0.000    1.61e+06    2.32e+06
## Kor                   -7.279e+04   9027.563     -8.063      0.000   -9.07e+04   -5.49e+04
## Kilometerora             -2.4477      0.353     -6.942      0.000      -3.148      -1.747
## Teljesitmeny           4754.5406   1086.245      4.377      0.000    2596.848    6912.234
## Uzemanyag_Dizel       -3.822e+04   4.02e+04     -0.952      0.344   -1.18e+05    4.15e+04
## Allapot_Kituno         1.164e+05   4.83e+04      2.408      0.018    2.04e+04    2.12e+05
## Allapot_Megkimelt      1.619e+05    4.3e+04      3.762      0.000    7.64e+04    2.47e+05
## Allapot_Serulesmentes  1.031e+05   1.07e+05      0.964      0.338   -1.09e+05    3.16e+05
## Allapot_Ujszeru         3.45e+05   1.13e+05      3.055      0.003    1.21e+05    5.69e+05
## ==============================================================================
## Omnibus:                        8.420   Durbin-Watson:                   1.624
## Prob(Omnibus):                  0.015   Jarque-Bera (JB):                8.060
## Skew:                          -0.639   Prob(JB):                       0.0178
## Kurtosis:                       3.550   Cond. No.                     1.98e+06
## ==============================================================================
## 
## Notes:
## [1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
## [2] The condition number is large, 1.98e+06. This might indicate that there are
## strong multicollinearity or other numerical problems.</code></pre>
<p>Első ránézésre minden rendben, de nézzük csak össze ennek a szűkített modellnek az <span class="math inline">\(R^2\)</span> értékét az eredeti modell <span class="math inline">\(R^2\)</span> értékével, ami még tartalmazta a hengerűrtartalmat és a teljes tömeget! Ezt legkönnyebben úgy tudjuk megkérdezni, hogy mindkét modellnek lekérdezzük az <code>rsquared</code> tulajdonságát.</p>
<div class="sourceCode" id="cb1011"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb1011-1"><a href="többváltozós-ols-regresszió-alapjai.html#cb1011-1" tabindex="-1"></a>[autos_modell.rsquared, autos_modell_szuk.rsquared]</span></code></pre></div>
<pre><code>## [0.7279480731232686, 0.7272297252691152]</code></pre>
<p>Ajjaj! A modellünk magyarázóereje leromlott <span class="math inline">\(72.72\%\)</span>-ra az eredeti <span class="math inline">\(72.79\%\)</span>-ról! De hát azért eléggé nem szignifikánsnak kinéző változókat szedtünk ki! A legalacsonyabb t-próba p-érték <span class="math inline">\(65.9\%\)</span> volt a kihagyott magyarázóváltozók között (<strong>Teljes_tomeg</strong>)! Miért csökken az <span class="math inline">\(R^2\)</span>?</p>
<p>Sajnos a jó öreg <span class="math inline">\(R^2\)</span> nem fog soha javulni akkor, ha a modellből elhagyunk egy magyarázóváltozót. Legyen az bármennyire is haszontalan.</p>
<p>Miért is? Ugye <span class="math inline">\(R^2=1-\frac{SSE}{SST}\)</span> és hát <span class="math inline">\(SSE\)</span> minimalizálásával szüljük meg a <span class="math inline">\(\beta_j\)</span> együtthatókat. Konkrétan úgy választjük meg az értéküket, hogy a MEGFIGYELT <span class="math inline">\(y\)</span> értékekre a lehető legjobban illeszkedjen a regresszióból nyert <span class="math inline">\(\hat{y}\)</span> becslés!</p>
<p>Ezt az illeszkedést pedig egy újabb magyarázóváltozó bevonása biztosan NEM RONTJA el, legyen bármennyire irreleváns <span class="math inline">\(y\)</span> szempontjából. Hiszen eggyel több <span class="math inline">\(\beta_j\)</span> van arra, hogy minimalizáljuk a modellhibát (<span class="math inline">\(SSE\)</span>). De ha kilépünk a megfigyeléseinken túli világba (sokaságba), akkor már az <span class="math inline">\(\hat{y}\)</span> becslések jóságát elrontják ezek az irreleváns magyarázóváltozók a modellben. Ez a jelenség a <strong>túltanítás</strong> jelensége!</p>
<p>Nézzük ezt meg az alábbi képen:</p>
<center>
<img src="Tultan1.jpg" style="width:100.0%" />
</center>
<p>A pontokra illesztett görbék mögött a következő egyenletek vannak:</p>
<ul>
<li>Lineáris = <span class="math inline">\(5.13x-0.46\)</span></li>
<li>Harmadfokú = <span class="math inline">\(2.48x^3+3.17x^2−1.06x +1.08\)</span></li>
<li>Hetedfokú = <span class="math inline">\(−7426x^7+28047x^6−42886x^5+33991x^4−14814x^3+3457x^2−380x+14\)</span></li>
</ul>
<p>Az ábráról láthatjuk, hogy a pontokra a legreálisabb illeszkedést a 3 db magyarázóváltozót (<span class="math inline">\(x^3, x^2, x\)</span>) használó <em>Harmadfokú</em> görbe adja. De az <span class="math inline">\(R^2\)</span> mégis a legtöbb magyarázóváltozót használó Hetedfokú opciót részesíti előnyben a <em>túltanulás</em> miatt!</p>
<p>Ennek kiküszöbölésére bevezetjük a korrigált <span class="math inline">\(R^2\)</span> mutatót:</p>
<center>
<img src="AdjR2.jpg" style="width:50.0%" />
</center>
<p>A korrekciós képlet lényege, hogy ez a mutató csökkenhet is, ha irreleváns (erősen nem szignifikáns) magyarázóváltozókat vonunk be a modellbe. Ezért van a képletben a megfigyelések száma (<span class="math inline">\(n\)</span>) mellett a magyarázóváltozók száma, <span class="math inline">\(k\)</span> is.</p>
<p>Láthatjuk, hogy a korábbi példánkban <span class="math inline">\(\bar{R}^2\)</span> már a harmadfokú modellt preferálja, nagyon helyesen!</p>
<center>
<img src="Tultan2.jpg" style="width:100.0%" />
</center>
<p>A <span class="math inline">\(\bar{R}^2\)</span> mutató értékét megtaláljuk a sima <code>summary</code> függvény eredménytáblájában is, de praktikusabb lekérdezni, mint a regressziós modellek <code>rsquared_adj</code> tulajdonsága.</p>
<div class="sourceCode" id="cb1013"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb1013-1"><a href="többváltozós-ols-regresszió-alapjai.html#cb1013-1" tabindex="-1"></a>[autos_modell.rsquared_adj, autos_modell_szuk.rsquared_adj]</span></code></pre></div>
<pre><code>## [0.697380440889928, 0.7032499208971693]</code></pre>
<p>Hurrá! Láthatjuk, hogy a korrigált R-négyzet már heylesen azt mutatja, hogy a nem szignifikáns változók kihagyásával kapott szűkített modell magyarázóereje nagyobb (<span class="math inline">\(70.3\%\)</span>), mint az eredeti modellé (<span class="math inline">\(69.7\%\)</span>), amiben ez a két haszontalan változó is benne volt.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="kétváltozós-lineáris-regresszió.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "night",
"family": "sans",
"size": 1
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/12-TobbvaltReg.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
